### ISSUE TITLE
Does not work with `js` entry points

### ISSUE THREAD

**Issue by CarltonHowell** [webpro/knip#10]
Any way to get this working with `.js` entry points? Renaming my entry point from `index.js` to `index.ts` fixes the issue, but I have a large code base where this isn't so practicle.

Cheers

**Comment by webpro** [comment]
Do you have `allowJs: true` in `tsconfig.json`?

**Comment by CarltonHowell** [comment]
Great this fixed it! Cheers :)

**Comment by webpro** [comment]
Great! Feel free to follow up with any issues or questions you may have.
