### ISSUE TITLE
Issue with ignoring dependency in monorepo

### ISSUE THREAD

**Issue by XDoubleU** [webpro/knip#104]
I'm using the following pnpm monorepo structure:
- apps/
  - api/
  - web/
- packages/
  - ...
 
Inside apps/api/package.json I have helmet as a dependency. Because of some issues with that library it's usage is not being detected by knip. I can't seem to be able to ignore it using this knip.json:
```
{
  "exclude": [
    "classMembers"
  ],
  "ignore": [
    "apps/api/src/cli/**",
    "apps/api/src/main.ts",
    "integration/script.js",
    "packages/mikro-orm-config/src/migrations/**",
    "packages/mikro-orm-config/src/seeders/**"
  ],
  "ignoreWorkspaces": [
    "packages/eslint-config-custom"
  ],
  "ignoreDependencies": [
    "only-allow", "helmet"
  ]
}
```

**Comment by webpro** [comment]
Maybe there's a helmet plugin in both root `package.json` and `apps/api/package.json`?

As shown at https://github.com/webpro/knip#workspaces-monorepos, you might want to be more specific about configuration per workspace.

You can use `--debug` to see the actual config used per workspace.

**Comment by XDoubleU** [comment]
There is no helmet plugin in both root `package.json` and `apps/api/package.json`.
After running with the `--debug` flag I get following output: 
[debug.txt](https://github.com/webpro/knip/files/11082696/debug.txt)

The only thing I see in there that could be causing the issue is that `knip.json` is on root level. The `helmet` package is only in the ignoreDependencies of the root level in the debug, not in the ignoreDependencies of the `apps/api`. Is this possible? Would it be possible as a solution to add additional config on workspace level?

Thanks in advance

**Comment by webpro** [comment]
> Would it be possible as a solution to add additional config on workspace level?

Yeah that's what you should do as shown in the docs.

Not sure if relevant, but another issue I can see from that debug log (`pkgName: undefined`) is that the root `package.json` does not have a `name` and/or `version`? That might influence things.

**Comment by XDoubleU** [comment]
How would I add this additional config in `pnpm-workspace.yaml`?
I tried: 
```
packages:
  - "packages/*"
  - "apps/*"
  - "apps/api":
      entry: "src/main.ts"
      project: "**/*.ts"
```

But got an error of `configuration-chief`

**Comment by webpro** [comment]
In `knip.json`, here's just a few things to get an idea:

```json
{
  "ignoreWorkspaces": [
    "packages/eslint-config-custom"
  ],
  "workspaces": {
    ".": {},
    "apps/api": {
      "ignore": ["src/cli/**"],
      "ignoreDependencies": ["helmet"]
    }
  }
}
```

**Comment by XDoubleU** [comment]
Awesome! Got it working using this `knip.json`:
```
{
  "exclude": [
    "classMembers"
  ],
  "ignoreWorkspaces": [
    "packages/eslint-config-custom"
  ],
  "workspaces": {
    ".": {
      "ignore": ["integration/script.js"],
      "ignoreDependencies": ["only-allow"]
    },
    "apps/api": {
      "entry": "src/main.ts",
      "ignore": ["src/cli/**"],
      "ignoreDependencies": ["helmet"]
    },
    "packages/mikro-orm-config": {
      "ignore": [
        "src/migrations/**",
        "src/seeders/**"
      ]
    }
  }
}
```

Many thanks for the help and quick responses!
Loving the library this far btw!

**Comment by webpro** [comment]
Great! I must admit when looking at the docs they do need some attention, thanks for reminding me.
