### ISSUE TITLE
Add detection for execa

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#107]
Similar to #96, https://github.com/sindresorhus/execa is pretty great. And it works similarly. Would you be open to a feature PR adding support for detecting packages run by `execa`?

```ts
import { $ } from 'execa';

await $`pnpm all-contributors generate`;
```

Maybe this is when I get to send my first real PR here 😄

**Comment by webpro** [comment]
Yes, that sounds great! Be my guest 😃
