### ISSUE TITLE
add class useless property resolver

### ISSUE THREAD

**Issue by KlausBai** [webpro/knip#11]
there's lots of class's properties in my project. can knip support remove these properties?

**Comment by webpro** [comment]
Knip is in a good position to try and support this. If you can share a public repository with your use case, or open a pull request with a minimal example project in the test/fixtures folder, that would help a lot.

Depending on feasibility and performance, we can see if it should be the default or optional to find unused class members.

**Comment by webpro** [comment]
I have released an initial version to support this. Any chance you could give it a shot on your repo(s)? Two issue types "class members" and "enum members" have been added. It's a pre-release ([v0.13.0-members.0](https://github.com/webpro/knip/releases/tag/0.13.0-members.0)), it can be installed like this:

```
npm install knip@members
```

Thanks in advance for your feedback.

**Comment by webpro** [comment]
This was added in [v0.13.0](https://github.com/webpro/knip/releases/tag/0.13.0)
