### ISSUE TITLE
Add detection for stylelint

### ISSUE THREAD

**Issue by navin-moorthy** [webpro/knip#110]
- Add support for detecting stylelint [configuration file.](https://stylelint.io/user-guide/configure)
- Add support for detecting installed & used stylelint configs.

**Comment by webpro** [comment]
Sounds like we need a new plugin. Any chance you'd like to create it? Otherwise I will pick it up, no worries.

There's a guide, but maybe even easier to copy a similar one.

**Comment by navin-moorthy** [comment]
I would like to do it. 😇

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.15.0. See [Release 2.15.0](https://github.com/webpro/knip/releases/tag/2.15.0) for release notes._

**Comment by webpro** [comment]
Added a rudimentary version, feel free to follow up with feedback/improvements.

**Comment by navin-moorthy** [comment]
> I would like to do it. 😇

Couldn't find time to do it, because of other priorities 😔

**Comment by webpro** [comment]
> Couldn't find time to do it, because of other priorities 😔

No worries! First things first ❤️
