### ISSUE TITLE
Add `sharp` detection for Next.js

### ISSUE THREAD

**Issue by navin-moorthy** [webpro/knip#111]
`sharp` is [required to be installed](https://nextjs.org/docs/deployment#nodejs-server) when using `next/image` in the project to run `next start`.

`next start` is used to run the production code in nodejs server, which in turn requires `sharp`

**Comment by webpro** [comment]
I guess `sharp` is not an (optional) peer dependency of `next`, but it should be?

So your idea is to see whether `next/image` is referenced in code somewhere, and then report `sharp` as unlisted if necessary? Sounds pretty custom 😃

Perhaps a task for the Next.js ESLint plugin, although not sure whether that would be possible. Not sure what that's capable of.

**Comment by navin-moorthy** [comment]
Started a [discussion in next.js repo](https://github.com/vercel/next.js/discussions/47727)

**Comment by webpro** [comment]
From https://github.com/vercel/next.js/pull/19216#issuecomment-729832697:

> We're looking to eliminate Sharp ASAP though, so this shouldn't be a problem for long.

Either way, for such exceptions you can use `ignoreDependencies` and e.g. `sharp` will not be reported as unused. Open to better ideas here :)

**Comment by webpro** [comment]
Alright then.
