### ISSUE TITLE
Describe unlisted binaries as unlisted binaries, not bin: dependencies?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#117]
I received knip output like this:

```plaintext
Unlisted dependencies (2)
bin:cat  script/setup.js
bin:gh   script/setup.js
```

My first instinct was to file #116. My _second_ instinct was to add the unlisted dependencies to `ignoreDependencies`:

```json
{
  "ignoreDependencies": ["bin:cat", "bin:gh"]
}
```

...but that didn't change anything. The solution was to re-read the README.md exhaustively to learn to add them to `ignoreBinaries`:

```json
{
  "ignoreBinaries": ["cat", "gh"]
}
```

That was confusing given that they were listed as unlisted _dependencies_. Could we have a separate reporting list for unlisted _binaries_?

Proposal:

```plaintext
Unlisted binaries (2)
cat  script/setup.js
gh   script/setup.js
```

**Comment by webpro** [comment]
This was on my mind after the "bins" from scripts got separated better from the package names recently. Thanks for reminding me, definitely on the list.
