### ISSUE TITLE
Add `grep` to global binaries 

### ISSUE THREAD

**Issue by navin-moorthy** [webpro/knip#118]
Here is the knip failure on `grep` detection for the binaries - https://github.com/JoshuaKGoldberg/template-typescript-node-package/actions/runs/4657657020/jobs/8242462242#step:4:12

References: 
https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/367#pullrequestreview-1377522650

What do you think, is it good to add `grep` to global binaries?

**Comment by webpro** [comment]
Yes, that's a good idea.

FYI, I personally don't see this as a bug. To me, it's a matter of where to draw the line. It's like a heuristic of sorts to pray that the `grep` package, or a package that has `grep` defined as a `bin` in `package.json`(!), was likely not what was meant to be referred to.

At this point I'm drawing the line at "more than a few years old", but it's fuzzy. I just created [last-publish](https://npm.im/last-publish) to help with this.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.9.0. See [Release 2.9.0](https://github.com/webpro/knip/releases/tag/2.9.0) for release notes._

**Comment by navin-moorthy** [comment]
Cool 🚀
