### ISSUE TITLE
Why Knip tries to load my "webpack.config.ts" file?

### ISSUE THREAD

**Issue by tal-rofe** [webpro/knip#121]
I'm using `knip@2.9.0`.
I'm running: `knip -c ./knip.json`.

Here is my `knip.json` file:
```json
{
	"$schema": "https://unpkg.com/knip@2/schema.json",
	"entry": "./src/index.ts",
	"project": ["./src/**/*"]
}
```

and then I get this error:
```
> knip -c ./knip.json

Analyzing workspace (.)...
Error loading /webpack.config.ts
Reason: await is only valid in async functions and the top level bodies of modules
```

Ok, for some reason `knip` fails to read this file as for top-level `await` statement. Just as a side note, I'm using `ESNext` with `typescript@5`, and `node@18` so it is valid.
Well, this is not the matter here anyway.

**Why Knip tries to read this file?**
As far as I understand, I configured Knip to read **only** the `src` folder. So why does it care about `webpack.config.ts`?

**Comment by tal-rofe** [comment]
> The [Webpack plugin](https://github.com/webpro/knip/tree/main/src/plugins/webpack) is enabled and that's what loads your `webpack.config.ts`. The reason it loads that file is to find dependencies used by your Webpack configuration.
> 
> Loading "foreign" JavaScript and TypeScript is a risky thing to do for Knip, and unfortunately you hit a bug here.
> 
> Until the bug is fixed, you can turn off the Webpack plugin by adding `webpack: false` to your configuration.

I see. As a side question, is it possible to ignore specific dependencies? There are some dependencies this tool detects as `Unused devDependencies` but are in use. Something like `depcheck.ignores` feature?

**Comment by webpro** [comment]
Yes, please see https://github.com/webpro/knip#ignore. Feel free to open an issue for this with relevant details so Knip can reduce false positives :)
