### ISSUE TITLE
Unused export not detected

### ISSUE THREAD

**Issue by rentalhost** [webpro/knip#123]
I'm trying to find pieces of my code that are unused. I found this package that might help with this, but I don't know if I understood it well.

For example, I created an `export const unused = () => 123` which was not detected, and is literally unused anyway. And it also has suggested that `ts-node` was not used, despite it being an optional dependency on `jest` to work with typescript.

https://github.com/rheactor/mariadb-alt/blob/knip-test/src/ConnectionPool.ts#L34-L36

> **npx knip**
_Unused files (2)_
.env.d.ts
jest.config.build.ts
_Unused devDependencies (1)_
ts-node  package.json

> **npx knip --production**
_Unused files (5)_
.env.d.ts
jest.config.build.ts
tests/Fixtures/InitialHandshakePacket.ts
tests/Fixtures/TestConnection.ts
tests/Fixtures/Utils.ts
_Unused exports (10)_
Capabilities                     src/Protocol/Enumerations.ts
Collations                       src/Protocol/Enumerations.ts
ServerStatus                     src/Protocol/Enumerations.ts
createUInt24LE                   src/Utils/BufferUtil.ts
createUInt64LE                   src/Utils/BufferUtil.ts
getFieldsPositions               src/Utils/BufferUtil.ts
readIntEncoded                   src/Utils/BufferUtil.ts
readNullTerminatedStringEscaped  src/Utils/BufferUtil.ts
readStringEncoded                src/Utils/BufferUtil.ts
toIntEncoded                     src/Utils/BufferUtil.ts
_Unused exported class members (8)_
isZeroed         DateFormat      src/Formats/DateFormat.ts
toNativeDate     DateFormat      src/Formats/DateFormat.ts
toNativeDate     DateTimeFormat  src/Formats/DateTimeFormat.ts
toNativeDate     TimeFormat      src/Formats/TimeFormat.ts
hasCapability    Handshake       src/Protocol/Handshake/Handshake.ts
hasServerStatus  Handshake       src/Protocol/Handshake/Handshake.ts
rest             BufferConsumer  src/Utils/BufferConsumer.ts
off              EventEmitter    src/Utils/EventEmitter.ts

But do not found `unused` variable.

So I'm not sure if I misunderstood or I'm not knowing how to configure.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.10.2. See [Release 2.10.2](https://github.com/webpro/knip/releases/tag/2.10.2) for release notes._

**Comment by webpro** [comment]
You were unfortunate enough to hit a bug with that `unused` export. It was caused by a re-export from an entry file without re-exporting the thing that's unused.

> And it also has suggested that `ts-node` was not used, despite it being an optional dependency on `jest` to work with typescript.

Looks like Knip has no way see that `ts-node` is used. Knip currently does take `peerDependencies` into account, but not `optionalDependencies`.

**Comment by rentalhost** [comment]
Nice! Now it works:

> **Unused exports (1)**
`unused`  src/ConnectionPool.ts
