### ISSUE TITLE
Allow ignoring unused exported types that are used by something exported

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#127]
In TypeScript-land, I like exporting types corresponding to used values, even if those types aren't directly used by anything.

For example, `greet` here would be allowed but `GreetOptions` would be complained about:

```ts
// greet.ts
export interface GreetOptions {
  message: string;
  repeat?: number;
}

export function greet(options: GreetOptions) {
  console.log(options);
}
```

```ts
// index.ts
import { greet } from "./greet";

greet({ message: "Hello, world!" });
```

```plaintext
$ knip

Unused exported types (1)
GreetOptions  interface  greet.ts
```

Could we have an option to allow these used-indirectly-but-not-directly types please? I'd be happy to send a PR!

**Comment by webpro** [comment]
https://github.com/webpro/knip#public-exports

Is this what you're after?

**Comment by JoshuaKGoldberg** [comment]
I don't think so - I'd rather not have to mark all these things as `@public`. And I'd still want to be told if there's something exported that _isn't_ used by anything.
