### ISSUE TITLE
Enable webpack plugin in Next.js project

### ISSUE THREAD

**Issue by oceandrama** [webpro/knip#130]
Could we enable `webpack` plugin If next.config.js has `webpack` field?
It could be usefull if you use custom config with custom loaders, because now it marks as unused (`@svgr/webpack`, for example) and should be added to ignore

**Comment by webpro** [comment]
This is a bit tricky. It essentially requires two plugins to work together. Not impossible, but I don't want to rush it.

Adding some notes:

- see if the `next` dependency is enabled
- add custom dependency resolver in next plugin and load `next.config.js`
- from this loaded module/object, execute the `webpack` prop/function with specific arguments (multiple times?)
- pass resulting webpack config to webpack custom dependency resolver
- ignore dependencies already shipped with Next.js?

Also see https://nextjs.org/docs/pages/api-reference/next-config-js/webpack

**Comment by webpro** [comment]
Needs more testing with complex configurations, but it's a start. Published `knip@next-webpack`, any chance you could try it? You can install using e.g. `npm install knip@next-webpack` (tag [2.13.0-next-webpack.0](https://github.com/webpro/knip/releases/tag/2.13.0-next-webpack.0)).

**Comment by webpro** [comment]
Guess the world is moving on and Next.js no longer uses Webpack by default. So I'm going to close this one. Feel free to discuss further or open a new issue.
