### ISSUE TITLE
Enable postcss plugin in Next.js project

### ISSUE THREAD

**Issue by oceandrama** [webpro/knip#131]
Could we enable postcss plugin If there is `next` dependency and `postcss.config.json` file exist? Because `next.js` doesn't require to install `postcss` package to use custom configuration

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.12.0. See [Release 2.12.0](https://github.com/webpro/knip/releases/tag/2.12.0) for release notes._
