### ISSUE TITLE
Is it possible to report unused exports in entry files in folders that are not being 'used' or 'imported' throughout the project?

### ISSUE THREAD

**Issue by VladSez** [webpro/knip#142]
Hello, thanks for a wonderful library ❤️

I have a question regarding unused exports
I have a project (not a monorepo), which looks like this (simplified):

[Reproduction](https://github.com/VladSez/knip-test)
```
/src
- /module1
- - index.ts
- /module2
- - index.ts
- /module3
- - index.ts
```

```ts
file: src/module1/index.ts
========
// this is NOT reported by knip, because we don't import anything throughout the app from 'module1/index.ts'
export function sum(a: number, b: number) {
  return a + b;
}

// this is NOT reported by knip, because we don't import anything throughout the app from 'module1/index.ts'
export function multiply(a: number, b: number) {
  return a * b;
}

file: src/module2/index.ts
========
// this function is imported in module3/index.ts
export function subtract(a: number, b: number) {
  return a - b;
}

// this is reported by knip correctly, because we import 'subtract()' at 'module3/index.ts
export const test = 23;

file: src/module3/index.ts
=======

import { subtract } from "../module2/index.js";

// this is NOT reported by knip, because we don't import anything throughout the app from 'module3/index.ts'
export function calculate(a: number, b: number) {
  return subtract(a, b);
}

// this is NOT reported by knip, because we don't import anything throughout the app from 'module3/index.ts'
export const smth = 'smth;

```

knip.json
```json
{
  "project": ["src/**/*.ts"]
}
```

package.json
```json
{
  "name": "knip-test",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "module1": "tsx src/module1/index.ts",
    "module2": "tsx src/module2/index.ts",
    "module3": "tsx src/module3/index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "knip": "2.13.0",
    "tsx": "3.12.7",
    "typescript": "5.1.3"
  }
}
```

if I run `npx knip` I get:

```
Unused exports (1)
test  src/module2/index.ts
```

Is it possible to make `knip` detect unused exports for `module1` and `module3`?

I have found this in docs: https://github.com/webpro/knip/blob/main/docs/handling-issues.md#unused-exports
But still not quite clear for me, if I can do anything to report those unused exports..

Also I have found that `--include-entry-exports` flag have been [removed](https://github.com/webpro/knip/issues/73) in `v2`, maybe this is related to this problem?

**Comment by webpro** [comment]
Thanks for your detailed reporting. I'm working on #140 which is related, and I'm planning to have a fix in the coming days.

**Comment by VladSez** [comment]
@webpro thanks for the quick fix
I have tried on the above example, it works as expected now

But I have tried on another project

and I am getting `prettier` `lint-staged` and `vite` config files as reported
on `knip: 2.13.0` I wasn't getting this

```
knip: 2.14.0-next.0

Unused exports (5)
default  .prettierrc.cjs       
default  knip.ts               
default  lint-staged.config.cjs
LABELS   src/cli/index.ts  ---> this is reported correctly
default  vite.config.ts
```

**Comment by webpro** [comment]
Thanks for trying so quickly.

Yeah I was kinda afraid of such results, that's why I did a pre-release first.

It is expected, but not desired. I think I need to make a difference between regular source code entry files versus entry files added by plugins. WIP :)

**Comment by webpro** [comment]
I've released another `next` pre-release.

I should add that for files referenced in scripts like this:

```
"module1": "tsx src/module1/index.ts"
```

The unused exports won't be reported. Maybe these should be added to `entry` explicitly? E.g.:

```json
{
  "entry": ["src/*/index.ts"],
  "project": ["src/**/*.ts"]
}
```

**Comment by VladSez** [comment]
@webpro thank you, I have tried the latest version and it works as you mentioned, but in my opinion this behavious is a bit confusing

in `package.json` I have

```
{
  "scripts": {
    "start:cli": "tsx src/cli/index.ts",
    "start:server": "tsx src/server/index.ts"
  }
}
```

and in knip:

```
{
  "entry": ["src/*/index.ts"],
  "project": ["src/**/*.ts"]
}
```

and with this setup `src/cli/index.ts` and `src/server/index.ts` are not reported, if I remove these scripts from `package.json` everything is reported correctly.

But, I think, it's useful to keep thoose scripts in `package.json`, but that breaks knip `--include-entry-exports` flag reporting

Is there any solution here?

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.14.0. See [Release 2.14.0](https://github.com/webpro/knip/releases/tag/2.14.0) for release notes._

**Comment by webpro** [comment]
Gave it a little more thought and I think it makes sense to include script files when using the `--include-entry-exports` flag.

By the way, I didn't mean to say you should include scripts in both `entry` config and npm scripts. Only in one place should be enough indeed.

**Comment by VladSez** [comment]
@webpro thanks for your effort, everything works now 🎉
