### ISSUE TITLE
Add support for tslib

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#144]
[tslib](https://www.npmjs.com/package/tslib) is a package to reduce the typescript compiled code size by offloading used helper functions to a unified source. To use it, the `tsconfig.json` file must contain this configuration:

```json
{
    "compilerOptions": {
        "importHelpers": true,
        "paths": {
           "tslib": ["./node_modules/tslib/tslib.d.ts"]
        }
    }
}
```
It would be great to include this check (as a plugin).

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.14.2. See [Release 2.14.2](https://github.com/webpro/knip/releases/tag/2.14.2) for release notes._

**Comment by webpro** [comment]
Thanks @ElPrudi! Knip looks at the `importHelpers` value and adds `tslib` to dependencies if `true`.

**Comment by ElPrudi** [comment]
Thanks for the info, great job! :D

**Comment by lo1tuma** [comment]
FWIW: this doesn’t work when using typescript project references. In my case the root tsconfig.json file only contains references to other ts projects (nested multiple times). So the root config doesn’t have any ts compiler options. A project config usually has those compiler options but indirectly via `extends` which imports a `tsconfig.base.json`.
