### ISSUE TITLE
jest moduleNameMapper dependencies are seen as unused

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#145]
I am working with a framework that wants to use css modules. To use these modules in tests, ES6 proxies have to be used, as seen [here](https://jestjs.io/docs/29.1/webpack#mocking-css-modules). 

I am using the jest plugin and it can find the `ts-jest` dependency, but it doesn't check for `moduleNameMapper` dependencies.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.14.2. See [Release 2.14.2](https://github.com/webpro/knip/releases/tag/2.14.2) for release notes._

**Comment by webpro** [comment]
Thanks @ElPrudi, the values of `moduleNameMapper` are returned as dependencies.

**Comment by ElPrudi** [comment]
Wonderful, thank you! :D
