### ISSUE TITLE
Import assets with alias

### ISSUE THREAD

**Issue by ds-pankov** [webpro/knip#146]
Hi, thanks for the good tool.

I can't exclude the import of assets (pictures) with the `ts` + `vite` alias. How can you defeat this?

<img width="900" alt="Screenshot 2023-06-21 at 10 18 56" src="https://github.com/webpro/knip/assets/3008966/1838d758-968e-4dee-9c2d-72608996e8a3">

tsconfig:

```json
"paths": {
  "@openquiz/*": ["../../packages/*/src"],
  "@/*": ["./src/*"],
}
```

vite.config.ts:

```ts
resolve: {
  alias: {
    '@': path.resolve(__dirname, './src')
  }
}
```

**Comment by webpro** [comment]
Do you have a repo you can link to? Or reproduction? Or could you add something to the test/fixtures folder in a PR?

**Comment by ds-pankov** [comment]
@webpro made a demo repository https://github.com/ds-pankov/issue-demo. Alias is configured in vite.config.ts.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.14.2. See [Release 2.14.2](https://github.com/webpro/knip/releases/tag/2.14.2) for release notes._

**Comment by webpro** [comment]
When TypeScript doesn't resolve such a module I'm using a brittle heuristic to decide whether its importing an external dependency or not. When using the `@` to prefix paths this is unfortunate. In your case this is fixed now (using a path prefix like `@assets/img/*` might result in a "missing" external dependency).

**Comment by ds-pankov** [comment]
Thanks.
