### ISSUE TITLE
Incorrectly reporting exports in namespace that are used in the current file

### ISSUE THREAD

**Issue by Jym77** [webpro/knip#147]
MWNE:
```typescript
namespace Foo {
  export type Bar = number
  export const bar = 2
}

type FooBar = Foo.Bar
const foobar = Foo.bar
```

When running `knip` (default configuration), I get:
```
Unused exports (1)
bar  src/knip.ts
Unused exported types (1)
Bar  type  src/knip.ts
```
yet both exports are actually used in the same file, and removing the `export` keyword would be a mistake.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.14.3. See [Release 2.14.3](https://github.com/webpro/knip/releases/tag/2.14.3) for release notes._

**Comment by webpro** [comment]
Thanks for reporting this @Jym77. Guess it's not very common, but valid use case.

**Comment by Jym77** [comment]
Amazing 🎉 Thank you.
