### ISSUE TITLE
[BUG] error count seems to not work as expected

### ISSUE THREAD

**Issue by juliensnz** [webpro/knip#15]
Hello, when I run knip on my project, I get unused types in my report but the command still returns 0 as exit code.

By reading the code [here](https://github.com/webpro/knip/blob/8c815a247996c0536485eb16eb699f2a2bcda2e3/src/cli.ts#L90-95)

```typescript
const reportGroup = report.files ? 'files' : (Object.keys(report) as IssueGroup[]).find(key => report[key]);
const counterGroup = reportGroup === 'unlisted' ? 'unresolved' : reportGroup;
if (counterGroup) {
  const count = counters[counterGroup];
  if (count > Number(maxIssues)) process.exit(count);
}
```

It seems to always take the file counter instead of aggregating all the counters. Is it expected?

I can do a pull request if you need help :)

**Comment by webpro** [comment]
Thanks for raising this. I had some reasoning to this, but an aggregate count is definitely very reasonable to expect. Now I'm thinking it only makes sense to use the total count. Just exclude types that should not make CI jobs fail. Would you be up for a PR?

**Comment by juliensnz** [comment]
Yes, of course!

**Comment by juliensnz** [comment]
There you go :) #17
