### ISSUE TITLE
Use of release tag (`@public`) and overloads

### ISSUE THREAD

**Issue by Jym77** [webpro/knip#150]
OK, I didn't made my mind on what the behaviour should be here, so opening the discussion to see what you think about it 😄 

For code that is meant to be exported to consumers, Knip requires us to add a release tag `@public` in a JSdoc block to mark it as such and not report it. This is pretty awesome.
For overloads, Knip wants the tag to be on the implementation, not on the overloads. This is the correct way:
```typescript
export function f(x: number): string;
export function f(x: boolean): number;
/** @public */
export function f(x: number | boolean): string | number {
  // …some code here…
}
```

---
However, in [TSdoc](https://tsdoc.org/pages/tags/public/) (and API extractor), the [release tags](https://api-extractor.com/pages/tsdoc/doc_comment_syntax/#release-tags) are expected on the overload declaration, and moreover [can differ between overloads](https://api-extractor.com/pages/messages/ae-different-release-tags/) (e.g. to introduce a new API that isn't stable yet):
```typescript
/** @public */
export function f(x: number): string;
/** @beta */
export function f(x: boolean): number;
export function f(x: number | boolean): string | number {
  // …some code here…
}
```

---
Additionally, API extractor automatically inherits release tags from ancestor namespaces, while Knip needs them specifically at each level. This is normal (and good). Knip is precisely here to figure out that this `export` is not needed, API extractor just tries to make our life easier by requesting less typing…

---
So, both tools use the release tags in different ways (this is good) and in different places (this is maybe less good). Making both tools happy becomes a bit WET:
```typescript
/** @public (API extractor wants that) */
export function f(x: number): string;
/** @beta (API extractor wants that) */
export function f(x: boolean): number;
/** @public (Knip wants that) */
export function f(x: number | boolean): string | number {
  // …some code here…
}
```

But then, I'm not sure whether this is truly a problem and especially if it is how to improve on it 😅 
The somewhat obvious idea is that Knip could look at release tags on overloads, and maybe accept an export if at least one of the overloads is marked as `@public`, but that makes things suddenly pretty ugly inside namespaces:
```typescript
/** @public (prevents Knip from complaining, and mark API as public) */
export namespace Foo {
  /** @public (mark at least one overload as public to make Knip happy, but is totally redundant for APi extraction) */
  export function f(x: number): string;
  /** Should Knip also require a release tag here? Clearly not since the export is required on all overload/implementation
    * as soon as it is on one. But then the code becomes very asymmetrical and the first overload gets a special meaning,
    * which is also not satisfying…
    */
  export function f(x: boolean): number;
  export function f(x: number | boolean): string | number {
    // …some code here…
  }
}
```

On the other hand, we can keep the situation as it currently is, considering that different tools use different indications and this is OK since they have different goals… The situation inside namespaces is also more satisfying by not breaking the symmetry between overloads unless needed (i.e. on of them is actually not `@public`):
```typescript
/** @public (prevents Knip from complaining, and mark API as public) */
export namespace Foo {
  export function f(x: number): string;
  export function f(x: boolean): number;
  /** @public (make Knip happy, API extractor doesn't care) */
  export function f(x: number | boolean): string | number {
    // …some code here…
  }
}
```

---
So here I am, not sure what the good solution should be or whether I'm just totally overthinking it…

**Comment by webpro** [comment]
I'll investigate a bit and see what Knip should do. Currently it's just a check on the exported node using `ts.getJSDocPublicTag`, interesting to look around a bit if there's more to this.

**Comment by webpro** [comment]
What Knip currently does is that it ends up considering only the implementation, also in terms of JSDoc tags. The rest is basically ignored. This still feels like the right and simple solution (as you point out, different tools have different goals), so I'm going to close this one. I actually looked into merging the tags of overloads into that of the implementation, but it has the downside of no longer "lazy loading" the JSDoc tags only when needed, which has a negative effect on performance.

You (or anyone else) can feel free to open another issue to discuss further.
