### ISSUE TITLE
Other release tags should be accepted on exported symbols

### ISSUE THREAD

**Issue by Jym77** [webpro/knip#151]
So, Knip considers that stuff marked as `@public` is OK to be exported if not used since it is intended for external consummers of the code.

I think it should do the same for some of the other [release tags](https://api-extractor.com/pages/tsdoc/doc_comment_syntax/#release-tags):
* `@internal` => report. This is intended for internal use only, if it is not used, it should be pruned.
* `@beta`, `@public` => do not report. These are meant (also) for third party usage.
* `@alpha` => I'm less sure 😅 I'd say do not report since it show that the intention is to open it later (even if 3rd party are encouraged to not use it…)

This pretty much prevents the use of `@beta` tags on external API since having both `@beta @public` is a big no, and Knip will keep reporting on the unused `@beta` symbol.

**Comment by Jym77** [comment]
They do exist in [TS doc](https://tsdoc.org/). Iirc, only in API extractor I've seen them called "release tags".

Also seems like TS, TS doc and API extractor are more or less the same people at Microsoft: https://tsdoc.org/#whos-involved

The fact that there is an official TS doc spec hint that Knip should likely respect it when dealing with TS code 🤔

**Comment by webpro** [comment]
I've added `@beta` as a tag like `@public`, should be released soon!

Added some tests. Also see #193.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.19.7. See [Release 2.19.7](https://github.com/webpro/knip/releases/tag/2.19.7) for release notes._

**Comment by webpro** [comment]
Should have been a minor bump (new feature), not a patch bump. Oh well.

**Comment by Jym77** [comment]
Awesome. Thanks.
