### ISSUE TITLE
tsconfig path resolution fails without baseUrl

### ISSUE THREAD

**Issue by spwhitt** [webpro/knip#152]
When `baseUrl` is omitted from tsconfig, the paths should be resolved relative to the `tsconfig` file: https://www.typescriptlang.org/tsconfig#paths.

I have a monorepo with `tsconfig` files which are not located at the project root. For these tsconfig files, knip fails to resolve imports correctly. Adding `baseUrl: "."` to the tsconfig file fixes the issue.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.15.0. See [Release 2.15.0](https://github.com/webpro/knip/releases/tag/2.15.0) for release notes._

**Comment by webpro** [comment]
Thanks for reporting this, @spwhitt. Think this surfaced since a refactoring, now fixed it again and added tests. Please let me know if it works for you too :)
