### ISSUE TITLE
Jest configuration reports false "Unlisted Dependencies" when used with ts-jest and ESM

### ISSUE THREAD

**Issue by ozum** [webpro/knip#156]
Hi,

This may be related to #145.

I have the following configuration for jest as suggested by [ESM support for `ts-jest`](https://kulshekhar.github.io/ts-jest/docs/28.0/guides/esm-support/)

```js
export default {
  moduleNameMapper: { "^(\\.{1,2}/.*)\\.js$": "$1" }
}
```

knip reports:

```
Unlisted dependencies (1)
-------------------------
$1  jest.config.js
```

Also the following won't help:

```json
{
  "ignoreDependencies": ["$1"]
}
```

Any suggestion?

Kind Regards,

**Comment by ozum** [comment]
I added a naive PR here: #157. It ignores all strings starting with `$`. I don't know whether it conflicts with other use cases. Consider merging until a more robust solution is found because there is currently no workaround for this problem and it stops CI build.

**Comment by webpro** [comment]
Fixed in linked PR.
