### ISSUE TITLE
In the monorepo, How are webpack aliases properly addressed

### ISSUE THREAD

**Issue by zhongmeizhi** [webpro/knip#16]
example：

```dir
common
  |-- index.js
src
  |-- monoA
     |-- entry.js
  |-- monoB
     |-- entry.js
```
   
and `npm run monoA`, webpack alias `"@": 'dir/monoA'`
and `npm run monoB`, webpack alias `"@": 'dir/monoB'`
 

then: How are aliases properly addressed

**Comment by webpro** [comment]
Just to be sure: you mean `resolve.alias` from https://webpack.js.org/configuration/resolve/#resolvealias?

Unfortunately Webpack aliases are not addressed at all with Knip. Do you know of a tool to find unused things that does support Webpack aliases?

That said, without knowing the complexity of it all, at first sight it looks similar to TypeScript `paths` configuration, so it might be doable to add (Webpack plugins are also on my mind for #7).

Let's keep this ticket open. Not highest priority, though. Do you have a repository I could see and explore things?

**Comment by brizer** [comment]
Is it supported?  Many project has alias such as `@` . So it is very necessary.

**Comment by webpro** [comment]
I'm planning on supporting this in v1.1. At this time I'm working towards a v1.0 which is in a beta phase.

It will also be very helpful if you have examples/repositories available.

**Comment by webpro** [comment]
The feature to add `paths` has been added in [v1.6.0](https://github.com/webpro/knip/releases/tag/1.6.0). Also see the docs at https://github.com/webpro/knip#paths.
