### ISSUE TITLE
npx scripts reported as unlisted

### ISSUE THREAD

**Issue by ozum** [webpro/knip#160]
Hi,

I have some npx scripts in `package.json`. I don't want them to be installed or listed as a dependency. For example:

```
{
  scripts: "npx only-allow pnpm"
}
```

`knip` reports `only-allow` as an `unlisted dependency`. I think `npx` scripts should be ignored.

Kind regards,

**Comment by ozum** [comment]
@webpro Thanks for the answer and `--no` and `--yes` is enough for my use case.

I created two simple PRs for adding a tip about `npx` to the docs .

**Comment by webpro** [comment]
Thanks, this also led me to fix a tiny bug (`--no` is an alias for --no-install` and not `-n).
