### ISSUE TITLE
Unable to ignore node_modules/.bin binaries from package.json

### ISSUE THREAD

**Issue by ervamate** [webpro/knip#161]
I generated a project with NestJS. One of the scripts it generates looks like this:

```json
{
  "scripts": {
    "test:debug": "node --inspect-brk -r tsconfig-paths/register node_modules/.bin/jest --runInBand",
  }
}
```

The knip output shows the following:

```
Unresolved imports (1)
.bin  package.json
```

I'm not sure how to ignore that, I've tried the following in my `.knip.jsonc` file

```jsonc
{
  // attempt to ignore both .bin and the actual file doesn't work
  "ignore": [".bin", "node_modules/.bin/jest"]
  // binaries also don't work
  "ignoreBinaries": [".bin", "node_modules/.bin/jest", "jest"]
}
```

I'm using knip `2.15.5`.

---

I also ran with the --debug, and I noticed that it shows this:

```
[knip] Unable to resolve /<path-to-project>/.bin (from /<path-to-project/package.json)
```

Hopefully, that helps to debug it!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.16.0. See [Release 2.16.0](https://github.com/webpro/knip/releases/tag/2.16.0) for release notes._

**Comment by webpro** [comment]
Thanks for reporting this, should be fixed now: hopefully you no longer need to ignore it.

It's not a very pretty recommendation though, it essentially means `node node_modules/.bin/jest`, while such a binary is to be ran on its own without `node`. Still shouldn't result in the behavior from Knip as you experienced.

**Comment by ervamate** [comment]
Thank you! It works like a charm

**Comment by darky** [comment]
Seems it's returned, since `5.34.0` I receive error

```
Unlisted dependencies (1)
.bin  package.json
```

Of course I don't have `.bin` dependency in `package.json`

**Comment by webpro** [comment]
In what kind of file is it referenced and how?

**Comment by darky** [comment]
I removed some legacy part of my package.json like 

`"test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",`

And it helps 👍

**Comment by webpro** [comment]
Should be fixed anyway. Thanks for reporting!
