### ISSUE TITLE
Support for vue dynamic import components

### ISSUE THREAD

**Issue by levchak0910** [webpro/knip#164]
Dynamically defined&imported component in vue files are reported as unused while it is actually used

```vue
// parent.vue
<script lang="ts">
import { defineComponent, defineAsyncComponent } from "vue";

const child1 = defineAsyncComponent(() => import("./child1.vue")) 

export default defineComponent({
  components: {
    child1,
    child2: defineAsyncComponent(() => import("./child2.vue"))},
});
</script>

<template>
  <child1></child1>
  <child2></child2>
</template>
```

```vue
// child1.vue and child2.vue
<template></template>
<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({});
</script>
```

```ts
// knip.ts
const compiler = /<script\b[^>]*>([\s\S]*?)<\/script>/gm;

export default {
  ignore: '*.d.ts',
  entry: ['parent.vue'],
  project: '**/*.{ts,vue}',
  compilers: {
    vue: text => {
      const scripts = [];
      let match;
      while ((match = compiler.exec(text))) scripts.push(match[1]);
      return scripts.join(';');
    },
  },
};
```

Result:

```
Unused exports (1)
default  child2.vue
```
but child2.vue is used

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.16.1. See [Release 2.16.1](https://github.com/webpro/knip/releases/tag/2.16.1) for release notes._

**Comment by webpro** [comment]
Thanks @levchak0910, there was indeed a case for import calls that didn't return `default` but anonymous (as if it was a side-effect import. Not specific to Vue, but added Vue fixtures nonetheless for extra test coverage.

**Comment by levchak0910** [comment]
@webpro thanks for a quick fix )
and for the project overall, I was looking for such a project for a long time and finally found, it works perfectly )

**Comment by Demivan** [comment]
This does not detect when import is passed to a function. @webpro Should I create a separate issue for this?

Example of using Quasar Dialog plugin:
```js
function showDialog(componentImport) {
  Dialog.create({
    component: defineAsyncComponent(componentImport),
  })
}

showDialog(() => import('./DialogComponent.vue'))
```

**Comment by webpro** [comment]
> This does not detect when import is passed to a function. @webpro Should I create a separate issue for this?

Yes please
