### ISSUE TITLE
Vue async component imports are not detected when used as function arguments

### ISSUE THREAD

**Issue by Demivan** [webpro/knip#166]
Vue async component imports are not detected when used as function arguments.

Example of using Quasar Dialog plugin:

```js
function showDialog(componentImport) {
  Dialog.create({
    component: defineAsyncComponent(componentImport),
  })
}

showDialog(() => import('./DialogComponent.vue')) // This import is not detected
showDialog(defineAsyncComponent(() => import('./DialogComponent.vue'))) // This is not detected either

// But this one works
const component = defineAsyncComponent(() => import('./DialogComponent.vue'))
showDialog(component)
// And this works too
const componentImport = () => import('./DialogComponent.vue')
showDialog(componentImport)
```

Edit: Actually file is marked as used but not the `default` export.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.16.2. See [Release 2.16.2](https://github.com/webpro/knip/releases/tag/2.16.2) for release notes._

**Comment by Demivan** [comment]
@webpro Thanks for a quick fix and an awesome tool!

**Comment by nicooprat** [comment]
Hi there, sorry for bumping. Just had this issue, it seems that the "verbose" syntax is not caught by Knip:

```ts
// ok
const AdminPage = defineAsyncComponent(() =>
  import('./components/AdminPageComponent.vue')
)

// not ok
const AsyncComp = defineAsyncComponent({
  loader: () => import('./Foo.vue'),
})
```

Docs: https://vuejs.org/guide/components/async#loading-and-error-states
Related: https://github.com/webpro-nl/knip/blob/c5b94c91ca3d7a606209ac76f3263952fa0a7bc7/packages/knip/fixtures/plugins/vue-webpack/parent.vue

Tell me if a new issue is needed 👍 

Thanks.

**Comment by webpro** [comment]
Any dynamic `import()` call should just work. Is there a test incorrectly passing? Would be great if you could set up a minimal repro indeed!

**Comment by nicooprat** [comment]
I struggled to reproduce, but it looks like only one dynamic import is supported, the other ones seem ignored:

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/b16304f5-e12d-4e63-be61-77c460b78a52">

If I invert the two lines, the other component is marked as unused:

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/cfe3ff6b-a75a-49e6-989f-cc517f44e9c4">

Declaring them outside of the `components` field fixes it:

<img width="1432" alt="image" src="https://github.com/user-attachments/assets/30575244-3cae-474c-b9b8-f9a452f63994">

Hope it makes sense...

**Comment by nicooprat** [comment]
Hmm... I have to admit I can't reproduce it on StackBlitz, I may have missed something... I'm leaving it here in case someone finds something someday 😬 Anyway the workaround above works for us for now...

https://stackblitz.com/edit/github-cc5zlh-1kbnjx?file=app.vue
