### ISSUE TITLE
Support glob Vite imports

### ISSUE THREAD

**Issue by Demivan** [webpro/knip#168]
Would be nice if `knip` supported Vite glob imports:

https://vitejs.dev/guide/features.html#glob-import

Example:

```js
const ratingStars = import.meta.glob('./assets/stars/*.png')
```

This would import all `png` files in `assets/stars` folder.

Webpack supports this too, but using different syntax: https://github.com/webpack/docs/wiki/context#requirecontext

I had an idea to implement it using a custom compiler, but the compiler function does not receive a path to a file that is being transformed. That would be nice to have too.

**Comment by webpro** [comment]
Up until now Knip didn't go into such dynamic/template paths territory and tries to use as much static analysis as possible.

The `*` in your example seems trivial, but what about something like `/path/${type}/file-${var}.ts`, which files should be included now?

Such tooling often has its own proprietary logic/characteristics (as you point out), and I wonder whether this could be implemented in a generic way?

Feel free to discuss further and/or take a stab at this, happy to look into a PR.

**Comment by Demivan** [comment]
I added PR that implements my second suggestion. This allows implementing more complex logic in custom compilers.

Going to investigate Vite and Webpack glob import implementations and get back to you in regard to generic implementation.

**Comment by Demivan** [comment]
I have investigated it a little bit. 
Vite glob imports are easy to do, all they use is fast-glob. So, just need to run fast-glob relative to file, that is being processed (and resolve Vite aliases).
Webpack's logic on the other hand is extremely complicated, it is mixed with other resolve logic.

For now, I solved it by adding a custom compiler that does a simple `string.replace`, as I don't have a lot of glob imports.

**Comment by webpro** [comment]
Thanks, glad you sorted this out.

Could be nice to add this "recipe" to the compilers doc page. Any chance you could share your solution here (or even open a PR)?

**Comment by Demivan** [comment]
My solution is full of hacks, so I don't think it needs to be in the docs :)
But here it is in case someone finds it useful:

```ts
function handleViteGlobImports(source: string, path: string) {
  if (path.includes('knip.ts') || path.includes('node_modules'))
    return source

  if (!source.includes('import.meta.glob'))
    return source

  const basePath = dirname(path)

  const regex = /import\.meta\.glob\(([^)]+)\)/gm
  let files = []

  let match: RegExpExecArray
  while ((match = regex.exec(source))) {
    const parsedParams = eval(`[${match[1]}]`)

    // Remove last element if it's an object (Vite import options)
    if (typeof parsedParams[parsedParams.length - 1] === 'object')
      parsedParams.pop()

    // Unwrap first element if it's an array (Glob pattern)
    if (Array.isArray(parsedParams[0]))
      parsedParams.unshift(...parsedParams.shift())

    // Resolve Vite aliases
    for (let i = 0; i < parsedParams.length; i++) {
      parsedParams[i] = parsedParams[i].replace(/^@alias/, relative(basePath, resolvedAliasPath)))
    }

    const foundFiles = glob.sync(parsedParams, { cwd: basePath })
    files.push(...foundFiles)
  }

  const imports = files.map(file => `import '${file}';`).join('\n')

  return imports + source
}
```

**Comment by webpro** [comment]
Thanks for sharing, @Demivan. Going to close this one.

For the record, `import.meta.glob` would be a rather easy "alias" for `require()` or `import()`, but since it supports globs it has not beed added to Knip.
