### ISSUE TITLE
Knip won't show version

### ISSUE THREAD

**Issue by ChristophP** [webpro/knip#173]
Hi,

I'm using the latest knip 2.17.0 on a Linux machine.

From running `npx knip --help` I got this line

```
 --V, version             Print version
```

However, none of the following commands give me the version

```
npx knip --V
npx knip version
npx knip -v
```
They give me the same help message as when I was passing `--help`

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.17.1. See [Release 2.17.1](https://github.com/webpro/knip/releases/tag/2.17.1) for release notes._

**Comment by webpro** [comment]
Thanks for reporting, @ChristophP. Should be `--version` or `-V` and this fixed in the help text now.

**Comment by ChristophP** [comment]
Great, I can confirm it works now. Thank you
