### ISSUE TITLE
Vitest plugin doesn't handle reporters that are Reporter instances

### ISSUE THREAD

**Issue by birtles** [webpro/knip#175]
Vitest allows configuring [`reporters`](https://vitest.dev/config/#reporters) as either strings or `Reporter` instances:

> Reporters can be [a Reporter instance](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/types/reporter.ts) or a string to select built in reporters:

However, the vitest plugin simply returns these `Reporter` instances as-is:

https://github.com/webpro/knip/blob/482396ecd79e31d47e35627ce934134bc5ba3fb1/src/plugins/vitest/helpers.ts#L32-L33

Then when we try to convert the dependencies using the `toPosix` helper:

https://github.com/webpro/knip/blob/482396ecd79e31d47e35627ce934134bc5ba3fb1/src/WorkspaceWorker.ts#L295-L298

we'll run into trouble:

```
export const toPosix = (value) => value.split(path.sep).join(path.posix.sep);
                                        ^

TypeError: value.split is not a function
    at toPosix (file:///home/birtles/project/node_modules/knip/dist/util/path.js:6:41)
    at Array.map (<anonymous>)
    at WorkspaceWorker.findDependenciesByPlugins (file:///home/birtles/project/node_modules/knip/dist/WorkspaceWorker.js:223:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WorkspaceWorker.findAllDependencies (file:///home/birtles/project/node_modules/knip/dist/WorkspaceWorker.js:235:9)
    at async main (file:///home/birtles/project/node_modules/knip/dist/index.js:167:30)
    at async run (file:///home/birtles/project/node_modules/knip/dist/cli.js:26:73)
    at async file:///home/birtles/project/node_modules/knip/dist/cli.js:70:1
```

Example Vitest config that generates this:

```ts
import { defineConfig } from 'vitest/config';
import GithubActionsReporter from 'vitest-github-actions-reporter';

export default defineConfig({
  test: {
    include: ['./src/**/*.test.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    reporters: process.env.GITHUB_ACTIONS
      ? ['default', new GithubActionsReporter()]
      : 'default',
  },
});
```

Should we just filter out any non-string values? (Or any values without stringifiers?)

**Comment by webpro** [comment]
> Should we just filter out any non-string values? (Or any values without stringifiers?)

Yes, exactly :)

Knip sometimes defines simple types to prevent having to pull in large dependencies. With the risk that [they're not always complete](https://github.com/webpro/knip/blob/482396ecd79e31d47e35627ce934134bc5ba3fb1/src/plugins/vitest/types.ts#L8). When filtered out, static analysis should still find the `vitest-github-actions-reporter` import.

Thanks for the detailed report, will fix. And of course, feel free to open a PR if you're up to it!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.17.2. See [Release 2.17.2](https://github.com/webpro/knip/releases/tag/2.17.2) for release notes._

**Comment by birtles** [comment]
Thank you so much! Sorry I didn't make up a PR in time but thank you for taking care of it!

**Comment by webpro** [comment]
No worries Brian, I was too quick. Including this fix in the release only took a minute, apologies for not letting you contribute.

**Comment by birtles** [comment]
Not at all. Thank you for taking care of it!
