### ISSUE TITLE
knip should be quiet like ESLint is

### ISSUE THREAD

**Issue by Zamiell** [webpro/knip#177]
Hello and thanks for the awesome tool!

Currently, `knip` has the `--no-progress` flag, which is quite useful in CI in order to make the tool quieter. However, even if you provide the `--no-progress` flag, knip will still output a message upon finishing:

```
✂️  Excellent, Knip found no issues.
```

This message creates noise in CI and obfuscates the results from other tooling. Consider that the most popular JavaScript/TypeScript tool in the world right now is ESLint, which has a design such that it only outputs text if there are one or more errors. This design is fantastic because you can easily chain together multiple tools without having to artificially create output separators or otherwise filter the output.

Subsequently, I propose that the design of `knip` should follow the ESLint design as close as is possible, since that is the behavior that the ecosystem will expect when using linting tools of this nature.

Depending on how breaking of a change you are interested in, you could flip the flag such that `--progress` is required in order to get the current verbose output. Failing that, I would also be happy if just the "Knip found no issues" message was removed.

**Comment by webpro** [comment]
Knip detects CI so it defaults to `--no-progress` there (without a TTY). Is that not working properly for you?

I agree the message could be removed altogether in that case.

**Comment by Zamiell** [comment]
> Knip detects CI so it defaults to --no-progress there (without a TTY). Is that not working properly for you?

Ah, thanks. It is working properly for me. Is this behavior documented somewhere? Can we please add that to the README?

**Comment by Zamiell** [comment]
I can do a PR for these two things if it is helpful for you.

**Comment by webpro** [comment]
Absolutely! Much appreciated 🙏
