### ISSUE TITLE
feature request: a way to ignore unused class members

### ISSUE THREAD

**Issue by Zamiell** [webpro/knip#181]
`knip` is a fantastic upgrade over `ts-prune` in that it offers the ability to find unused class members.

However, in some cases, I want to ignore unused class members, like a `$schema` field that is only intended to provide type-safety for the class when it is written to a JSON file later on.

Currently, from what I can tell, the only solution is to ignore the entire file by adding it to the `ignore` field in the `knip.json` file. However, this isn't granular enough.

Imagine that a file has two classes in it. In this situation, it would be better if we could ignore the specific class, as otherwise we would miss possible bugs in the other class.

But even that isn't enough, because in this situation, even if we had the ability to ignore a specific class, then we are in a similar problem. By ignoring the entire class, we are missing possible bugs in the other non-ignored fields of the class.

So I think the best solution would be to have the ability to both ignore individual classes and individual fields of a class.

I suspect that conveying this information to `knip` would best be done with a class prefix. Something like:

#### `knip.json`
```json
{
  "ignoreClassFields": ["Foo.field1"]
}
```

If it were just specified as "field1", then that would not be granular enough, as it would also ignore `Bar.field1`. Note that this scheme would fail on projects with multiple classes of the same name; I don't know if you are worried about that case.

**Comment by webpro** [comment]
You can use [the `@public` tag](https://github.com/webpro/knip#public-exports) to mark classes and members as public, excluding them from being reported as unused. Would that be sufficient?

**Comment by Zamiell** [comment]
Yeah, that's good enough I think, thank you.
