### ISSUE TITLE
feature request: more possible config file names

### ISSUE THREAD

**Issue by Zamiell** [webpro/knip#182]
Currently, `knip` supports these configuration names:

- knip.json
- knip.jsonc
- .knip.json
- .knip.jsonc
- knip.ts
- knip.js
- package.json#knip

However, I think this should be expanded. First of all, it is common to name `.ts` and `.js` files with an extension according to whether or not the file is CommonJS / ESM. Meaning that `knip` should support:

- knip.mts
- knip.cts
- knip.mjs
- knip.cjs

Additionally, I think that Knip should follow the style of the existing tools in the ecosystem. Most notably, ESLint has a config file of `eslint.config.js` and Prettier has a config file of `prettier.config.mjs` and Jest has a config file of `jest.config.mjs`. So, I think Knip should support:

- knip.config.ts
- knip.config.mts
- knip.config.cts
- knip.conifg.js
- knip.config.mjs
- knip.config.cjs

Furthermore, the docs should actively recommend that people use this config file naming format so that we match the rest of the ecosystem.

Additionally, note that this is more than a semantic or stylistic issue. TypeScript throws errors for a `knip.ts` when it is inside of a CommonJS project. Renaming the file to `knip.mts` fixes the problem, but then `knip` no longer picks up the file. ~~So this is a blocker.~~ (This can be worked around with the `--config` flag.)

**Comment by Zamiell** [comment]
I can try a PR for this if needed.

**Comment by Zamiell** [comment]
> You can use --config [file] (or -c) for this.

You're right, so this isn't a blocking issue, but rather a nice-to-have convivence for end-users.

**Comment by webpro** [comment]
Just wondering, is there any tool out there that tries to read all of those variations?

**Comment by Zamiell** [comment]
- [Prettier does](https://prettier.io/docs/en/configuration.html).
- [Jest does](https://jestjs.io/docs/configuration).
- [TypeDoc does](https://typedoc.org/options/configuration/). (It doesn't support ESM yet, but the file extensions will be expanded when it does.)

Note that [ESLint explicitly does not](https://github.com/eslint/eslint/issues/16580), but many users are mad/frustrated about this because it goes against the rest of the ecosystem and Node.js itself!

**Comment by webpro** [comment]
Thanks. Not sure whether all of them offer similar to what you request here though ;)

Anyway, I'm in camp "explicit is usually better", which is also one of the ideas in ESM (explicit extension). The mess with migrating from CJS to ESM is unfortunate, but I'm not sure whether tooling should also maintain the same state of hybrid/complexity.

Over time the list of conventions keeps growing and growing. It would be great if the ecosystem adopted a convention such as a `config` folder. But that would probably only increase the problem for the same reason.

Since Knip offers a solution for cases that need a different solution I'm going to close this issue.

**Comment by what1s1ove** [comment]
> Thanks. Not sure whether all of them offer similar to what you request here though ;)
> 
> Anyway, I'm in camp "explicit is usually better", which is also one of the ideas in ESM (explicit extension). The mess with migrating from CJS to ESM is unfortunate, but I'm not sure whether tooling should also maintain the same state of hybrid/complexity.
> 
> Over time the list of conventions keeps growing and growing. It would be great if the ecosystem adopted a convention such as a `config` folder. But that would probably only increase the problem for the same reason.
> 
> Since Knip offers a solution for cases that need a different solution I'm going to close this issue.

I understand you, but I still think it would be cool to have `knip.config.js` as a possible config file name, as most other configuration files have this prefix or plan to have it (usually with a migration to ESM). It seems to me that it's like a standard now.

<img width="435" alt="image" src="https://github.com/webpro/knip/assets/42296182/569cf386-6cbe-4ab7-9c4b-96d2b6f5f8a8">

**Comment by webpro** [comment]
Thanks for the input.  What does red strike-through mean?

Just checked one sample: turns out release-please has only `release-please-config.json` (note the dashes) as a default config file it looks at.

**Comment by webpro** [comment]
Just had someone else expecting `knip.config.js` to work as well, so I'm leaning towards adding it to the list (in upcoming v4 release). I don't want to be annoying here (I know I am), it's just all so fragmented.

**Comment by what1s1ove** [comment]
> Thanks for the input. What does red strike-through mean?
> 
> Just checked one sample: turns out release-please has only `release-please-config.json` (note the dashes) as a default config file it looks at.

I simply used the native browser search (Command + F) to find the word 'config' in one of my repositories (highlighted in yellow).

I crossed out in red those configs that have 'config' in their name but are not actually configs. The ones highlighted in red are what you don't need to look at. Just focus on the yellow color.

**Comment by Zamiell** [comment]
@webpro https://github.com/eslint/eslint/issues/17863
Given that ESLint has changed its stance on this, and that Prettier already supports this format, maybe Knip should reconsider?

**Comment by Zamiell** [comment]
> It would be great if the ecosystem adopted a convention such as a config folder. But that would probably only increase the problem for the same reason.

Also, I've seen this link floating around in some of the places I frequent: https://dot-config.github.io/
If you agree, then it also might be worth supporting this out of the box in Knip.
For more interesting discussion, see:
- https://twitter.com/iansu/status/1126512410313891841
- https://github.com/nodejs/tooling/issues/79

**Comment by webpro** [comment]
> @webpro [eslint/eslint#17863](https://github.com/eslint/eslint/issues/17863) was opened 2 days ago. Given that ESLint has changed its stance on this, and that Prettier already supports this format, maybe Knip should reconsider?

That's a different discussion. The new ESLint flat config file name is `eslint.config.js`, this discussion is about also supporting the `.mjs` and `.cjs` extension for flat configs.

> > It would be great if the ecosystem adopted a convention such as a config folder. But that would probably only increase the problem for the same reason.
> 
> I've seen this link floating around in some of the places I frequent: https://dot-config.github.io/ If you agree, then it also might be worth supporting ".config/knip.json" out of the box in Knip. For more interesting discussion, see:
> 
> * https://twitter.com/iansu/status/1126512410313891841
> * [the creeping scourge of tooling config files in project root directories nodejs/tooling#79](https://github.com/nodejs/tooling/issues/79)

This doesn't make it better? Unless the ecosystem reaches consensus about the folder name:  `/.config` or `/config`

**Comment by Zamiell** [comment]
I think the idea of the authors is that the ecosystem should specifically converge around `/.config`.

![image](https://github.com/webpro/knip/assets/5511220/fe2605f2-6d3e-48c2-b320-258a4bd82ce0)

**Comment by Zamiell** [comment]
> That's a different discussion. The new ESLint flat config file name is eslint.config.js, this discussion is about also supporting the .mjs and .cjs extension for flat configs.

Sorry, you're right, I didn't re-read this thread carefully enough.

**Comment by webpro** [comment]
> I think the idea of the authors is that the ecosystem should specifically converge around `/.config`.

Others think it should be an un-dotted `config`, e.g. https://github.com/natemoo-re/proload (but it's really just one example).

Interesting discussion still, but as much as I love to have a common default everyone & everything actually respects, I'm not very confident this will ever happen.

**Comment by Zamiell** [comment]
> Others think it should be an un-dotted config, e.g. https://github.com/natemoo-re/proload (but it's really just one example).

Interesting. I opened up an issue over there, I am curious to see what they think about the recent push for ".config" instead of "config".

> Interesting discussion still, but as much as I love to have a common default everyone & everything actually respects, I'm not very confident this will ever happen.

Well, we got most of the ecosystem to converge around Prettier, so you never know. =p

**Comment by webpro** [comment]
One of the reasons I think it's hard to reach consensus is that the `.config` idea mainly originates from the XDG spec. But the frontend world is that Linux/dotfiles oriented (there's also Windows in that area), and config files are often even authored in JS/TS (in contrast to INI/TOML/what have you). Hiding dotfiles, which is often the default when listing directory items (e.g. when using `ls` or in macOS Finder), might be too big of a change for frontend folks.

Either way, as mentioned, I'm leaning towards adding the `knip.config.*` file convention to the list.

**Comment by webpro** [comment]
It's not a breaking change, but I'd like to add it to the v4 changelog. You can try v4 canary today including this change with e.g. `npm install knip@canary`. Documented at https://knip.dev/v4/overview/configuration#location.

**Comment by Zamiell** [comment]
What about adding ".config.json" and ".config.jsonc"? Was that intentionally skipped?

**Comment by webpro** [comment]
> What about adding ".config.json" and ".config.jsonc"? Was that intentionally skipped?

No, it was not even requested.

**Comment by Zamiell** [comment]
Ah, well that might be worth adding as well. CSpell already supports ".config.json" and ".config.jsonc", for example.

**Comment by aryaemami59** [comment]
@webpro While I appreciate the `--config` option I wanted to ask if you would consider just adding **`knip.config.mts`** files? I'd be happy to submit a PR for it.
