### ISSUE TITLE
Yarn heuristics

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#184]
These are easy to ignore, but would be nice to have out-of-the-box:

```
Unused files

.yarn/plugins/@yarnpkg/plugin-constraints.cjs
.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
.yarn/plugins/@yarnpkg/plugin-typescript.cjs
.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
.yarn/releases/yarn-3.6.1.cjs

Unused devDependencies

@org/foo  packages/bar/package.json

Unlisted binaries

run  packages/bar/package.json
foo  packages/bar/package.json
```

`packages/bar/package.json`:

```jsonc
{
  // ...
  "scripts": {
    "a": "foo --arg",
    "b": "run a"
  },
  "devDependencies": {
    "@org/foo": "1.0.0"
  }
  // ...
}
```

Yarn aliases `yarn run` to `run` in its shell, and puts all binaries in `PATH`. And `.yarn` can be ignored altogether without consequences, I think, along with `.pnp.cjs` in the root.

**Comment by webpro** [comment]
Related: #148. As more people keep mentioning it I can see how to improve things.

The issue you mention with `run` and `foo`, not sure whether that's specifically related to Yarn? Either way, Knip should see that `@org/foo` has a `foo` binary in its `package.json`, but maybe Knip can't find it, because of how Yarn install things? Please open a separate issue if you think it's not Yarn related.

**Comment by alecmev** [comment]
Here's a minimal repro of both: https://github.com/alecmev/knip-repro-184

`node_modules` looks like this:

```bash
ls -Al node_modules/@org                                                                                                                                                                                          
# bar -> ../../packages/bar
# foo -> ../../packages/foo
```

And `run` is, indeed, Yarn-specific:

```bash
npm run b                                                                                                                                                                                                               
# sh: line 1: run: command not found
```

Let me know if you'd like me to report any of this separately :wink:

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.19.0. See [Release 2.19.0](https://github.com/webpro/knip/releases/tag/2.19.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.19.0. See [Release 2.19.0](https://github.com/webpro/knip/releases/tag/2.19.0) for release notes._

**Comment by webpro** [comment]
The issues should be fixed, except for the odd `run` binary that Yarn adds.

**Comment by alecmev** [comment]
Thank you! You can see what Yarn puts in `PATH` here:

https://github.com/yarnpkg/berry/blob/8d70543e4ec7bb67d94ccaf9fa931c40a1acaeda/packages/yarnpkg-core/sources/scriptUtils.ts#L110-L211

So `run` and such are available even in separate scripts launched by Yarn.

**Comment by webpro** [comment]
Is that documented somewhere? I couldn't find `run` when looking for it the other day.

**Comment by alecmev** [comment]
I couldn't either, unfortunately, but [they do dogfood it](https://github.com/yarnpkg/berry/blob/8d70543e4ec7bb67d94ccaf9fa931c40a1acaeda/packages/yarnpkg-cli/package.json#L58-L59).

**Comment by webpro** [comment]
If it would be trivial I would be happy to add it, but this is too clumsy to implement now for an undocumented feature (which they might even remove at any point in time).

Also, I think I shouldn't add `run` to the global list of ignored binaries (although also not sure what it could conflict with.

**Comment by alecmev** [comment]
I've asked on their Discord and got this reply:

> It's mentioned in the [Rulebook](https://yarnpkg.com/advanced/rulebook#published-packages-should-avoid-using-npm-run-in-their-scripts):
>
> > Yarn also supports just calling `run <name>` without any mention of the package manager, but to this date no other package manager does.
>
> There are no plans to remove this. We should actually advocate it to other package managers, but it hasn't been a priority.

However, yes, this isn't urgent at all, easy to add to `ignoreBinaries` :wink:

**Comment by webpro** [comment]
Ah, nice, good idea. There's also https://github.com/pnpm/only-allow to prevent issues here. Would obviously be better if that package wouldn't need to exist.

(Btw, just trying to keep a tiny bit of sanity in the kitchen sink that Knip inevitable is. Thanks for all the reports, much appreciated, keep 'em coming!)

**Comment by alecmev** [comment]
I understand your position, thank you for being so active and forthcoming! :relaxed:
