### ISSUE TITLE
Analyze `*.d.ts` files, but don't report them as unused

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#185]
I don't want to ignore them because I still want Knip to look at the imports. Unless there's already a way to do that? Or maybe it doesn't make sense for some reason?

**Comment by webpro** [comment]
It's actually an actual issue in Knip, it doesn't read them automatically like TypeScript does. Knip only gets/uses `compilerOptions` from `tsconfig.json` file(s). This already resulted in quite a few reported issues, so I really need to dive into this.

**Comment by webpro** [comment]
Opened https://github.com/webpro/knip/pull/206 for this

**Comment by webpro** [comment]
Including dts files is done in [v2.28.0](https://github.com/webpro/knip/releases/tag/2.28.0). This includes them so they're not reported as unused. However, the `declare module '*.svg'` pattern is not resolved yet.
