### ISSUE TITLE
Nested `extends` not considered in `tsconfig.json`

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#187]
I have the following setup:

```jsonc
// ./boilerplate/tsconfig.base.json
{
  "extends": [
    "@tsconfig/node20/tsconfig.json",
    "@tsconfig/strictest/tsconfig.json",
    "@tsconfig/esm/tsconfig.json"
  ]
  // ...
}
```

```jsonc
// ./tsconfig.json
{
  "extends": "./boilerplate/tsconfig.base.json"
  // ...
}
```

Knip reports all three `@tsconfig/*` packages as unused, despite having them in the base config. If I put them in `./tsconfig.json` directly then everything is fine.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.18.0. See [Release 2.18.0](https://github.com/webpro/knip/releases/tag/2.18.0) for release notes._

**Comment by alecmev** [comment]
Thank you! There's a mistake here:

https://github.com/webpro/knip/blob/a4de561935d99f16aff2471c2c0c5042f9ea0c0d/src/plugins/typescript/index.ts#L22

`isInternal` expects a string, but `config.extends` may also be an array. Need to iterate over it, same as here:

https://github.com/webpro/knip/blob/a4de561935d99f16aff2471c2c0c5042f9ea0c0d/src/plugins/typescript/index.ts#L36

**Comment by webpro** [comment]
Ouch, indeed. I copy-pasted the code from the Jest plugin. Oh, the irony that the types were not set properly in the TypeScript plugin.

This fix will be in the next release. Thanks again!
