### ISSUE TITLE
`plugin:@typescript-eslint/disable-type-checked` config is reported as an unlisted dependency

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#188]
One more exception could be added [here](https://github.com/webpro/knip/blob/d080ed2d59e2f497cbe3ba5bbb10e00d15f98292/src/plugins/eslint/helpers.ts#L80-L94), but does it make sense?

**Comment by webpro** [comment]
That is such a mess indeed. I remember I looked at ESLint's own config parser, to no avail. One of the reasons ESLint is moving to a normal config system now, but in the meantime I guess I can just shove in another ugly line in there.

**Comment by alecmev** [comment]
What's the reason for being specific with `\/(eslint-)?(recommended.*|stylistic.*|strict.*|all)`? Is there some sort of potential false-positive if matching just `\/.+`?

**Comment by webpro** [comment]
Yes. You can see for instance in [this fixture](https://github.com/webpro/knip/blob/main/fixtures/plugins/eslint/.eslintrc.js) what the strings should translate to in [this test](https://github.com/webpro/knip/blob/main/tests/plugins/eslint.test.ts#L25).

**Comment by alecmev** [comment]
Hmm, I think that test would pass if you throw away everything after the last slash as long as `specifier` starts with `plugin:`?

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.18.0. See [Release 2.18.0](https://github.com/webpro/knip/releases/tag/2.18.0) for release notes._

**Comment by webpro** [comment]
Added some unit tests just for that helper for future reference. Thanks again!

**Comment by webpro** [comment]
After publishing a fix yesterday I suddenly saw the light. If I just consider `@typescript-eslint/` as an exception, the rest is pretty straightforward. It's just odd that this org is handled differently than others.

**Comment by alecmev** [comment]
Thank you! It works :+1:

**Comment by webpro** [comment]
Related: #195
