### ISSUE TITLE
How to handle `.elm` files?

### ISSUE THREAD

**Issue by ChristophP** [webpro/knip#190]
Hi,

thanks for making this amazingly useful tool.

I have one question:

In my project knip finds an import of an [Elm file](https://elm-lang.org/).

![grafik](https://github.com/webpro/knip/assets/5880236/1f17275a-ba98-46d3-aa41-59863ebdd3c6)

Knip marks it as an unresolved import. I am using the parcel bundler to build my project which [compiles Elm files out-of-the-box](https://parceljs.org/languages/elm/).

![grafik](https://github.com/webpro/knip/assets/5880236/dcfeb642-0807-467b-a97f-e13a03a5ef92)

What's the best way to handle this? The file at `src/elm/Main.elm` exist at the correct path

**Comment by webpro** [comment]
You can look at [compilers](https://github.com/webpro/knip/blob/main/docs/compilers.md). Depending on how those files look like etc. you would need a real compiler (better/recommended) or you might get away with some regular expression (fast/simple?), as shown in the examples.

**Comment by ChristophP** [comment]
Ah I see, the compilers are seem to be a nice concept. Thank you.

I was able to silence the `unresolvedImport` error I got by simply adding

```js
  compilers: { elm: () => "" }
```

I also looked at these two examples, and was trying to get the regex import extraction to work for Elm code.

```js
export default {
  svelte: (text: string) => [...text.matchAll(/import[^;]+/g)].join('\n'),
  css: (text: string) => [...text.matchAll(/(?<=@)import[^;]+/g)].join('\n'),
};
```

However, there are a few things that aren't clear to me yet:
- Is the code returned from the compiler function supposed to be always be a string of JavaScript code?
- When trying to extract imports. I find that it doesn't matter what I return from the function. An empty string, will produce no error, just as for example `import "./file-that-does-not-exist"; ` will produce now error. Won't the imports in the generated code get checked again by knip? If not, what's the purpose of extracting the imports there?

FYI, In the case of Elm, Elm would always compile all of the `*.elm` files in the project into a single JS file with no imports.  Maybe that somehow simplifies things.

**Comment by webpro** [comment]
> I was able to silence the unresolvedImport error I got by simply adding

Yes, Knip adds all object keys as accepted file extensions, so that alone should fix the unresolved import.

> Is the code returned from the compiler function supposed to be always be a string of JavaScript code?

Yes. String in, string out. It is fed to the TypeScript backend, which this is quite fault-tolerant.

> When trying to extract imports. I find that it doesn't matter what I return from the compiler function

That's odd. There's e.g. the [compilers-vue](https://github.com/webpro/knip/blob/9740b099977b681eea44c6e003ced9fd9f475494/fixtures/compilers-vue/knip.ts#L11) fixture and when I remove that line I'm seeing the expected unused files, etc.

> Elm would always compile all of the *.elm files in the project into a single JS file with no imports.

That sounds like the actual compiler is not useful here if Knip won't be able to find imports to other source files.

So eventually I'm not sure what's the difference between the Elm files and the examples provided.

**Comment by ChristophP** [comment]
I ah, ok I see what I was doing wrong.

> That's odd. There's e.g. the [compilers-vue](https://github.com/webpro/knip/blob/9740b099977b681eea44c6e003ced9fd9f475494/fixtures/compilers-vue/knip.ts#L11) fixture and when I remove that line I'm seeing the expected unused files, etc.

You're totally right this works as expected. I was confusing knip finding unused files with knip not telling me that I'm trying to import something that doesn't exist. I tried returning `import "./some-file-that-does-not-exist"` from the compiler function and got no errors (which might be like this by design but confused me for a moment).

So in the end it was just my confusion instead of knip not doing its job (which it does :-)).
However, if I may suggest one thing:
The term `unresolved import` from the JavaScript/frontend/bundler world usually means "this file does not exist". The way this term is used from knip seems to mean more like "I don't know how to handle this file extension". This thinking contributed to me not really making the connection between `unresolvedImport` and using a compiler to resolve it.
A clearer naming IMHO would be somehthing like `unknownFileType` along with a hint to use a compiler to resolve this.

Other than that, this issue is resolved. Thank you for your explanations and for making this great tool.

**Comment by webpro** [comment]
You have a valid point. It comes from not receiving a module from `ts.resolveModuleName()`, so I went with that. Yet for now I accept that these are reported in this category, even though there could be more to clarify (and Knip itself also has to check whether the file exists).
