### ISSUE TITLE
The config filename `knip.ts` collides with the module name `knip`

### ISSUE THREAD

**Issue by risu729** [webpro/knip#191]
While using a TypeScript config file with filename `kinp.ts`, VS Code TypeScript IntelliSense threw an error.
> Module '"knip"' has no exported member 'KnipConfig'.

`knip` as a config filename collides with `knip` in `node_modules`.
Could you consider changing or adding default config filenames?

Config file:
```ts
import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: ['src/index.ts'],
  project: ['src/**/*.ts'],
};

export default config;
```

## Workaround

Use `knip.config.ts` as a config filename to avoid collision and specify it by the `--config` option.
e.g. `knip --config knip.config.ts`

**Comment by webpro** [comment]
I can't seem to reproduce it in VS Code. Any more details, or even a repro? Are you using Yarn/pnpm PnP?

Also, I'm not terribly eager to introduce even more config file names (also see #182).

**Comment by risu729** [comment]
My apologies. I didn't check carefully the cause.

The cause was `tsconfig.json#compilerOptions.baseUrl`, which was set to `"."`, not knip.
https://github.com/risu729/knip-test

I understand your thoughts on adding config file names. I will close this issue.

**Comment by webpro** [comment]
No worries.
