### ISSUE TITLE
ESLint org scopes aren't supported (@typescript-eslint/eslint-plugin isn't special)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#195]
Coming over from https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/602#issuecomment-1666873499, regarding this:

https://github.com/webpro/knip/blob/9740b099977b681eea44c6e003ced9fd9f475494/src/plugins/eslint/helpers.ts#L87-L88

We're not doing anything fancy in our side or ESLint's 😄. ESLint just allows plugins to start with `@` scoped name prefixes. See: https://eslint.org/docs/latest/extend/plugins#name-a-plugin:

> Each plugin is an npm module with a name in the format of `eslint-plugin-<plugin-name>`, such as `eslint-plugin-jquery`. You can also use scoped packages in the format of `@<scope>/eslint-plugin-<plugin-name>` such as `@jquery/eslint-plugin-jquery` or even `@<scope>/eslint-plugin` such as `@jquery/eslint-plugin`.

`resolveExtendsSpecifier` should probably be modified to respect these scoped names, rather than bailing out for any specific scopes.

**Comment by webpro** [comment]
> ..or even..

This is the part that bugs me. By that logic I guess ESLint does fs lookups in `node_modules`?

Example of what I think are two different resolutions:

- `plugin:@typescript-eslint/recommended` → `@typescript-eslint/eslint-plugin` (not `@typescript-eslint/eslint-plugin-recommended`).
- `plugin:@next/next/core-web-vitals` → `@next/eslint-plugin-next`  (not `@next/eslint-plugin`).

Not to say I disagree with anything, just afraid Knip needs to look up the installed package.

**Comment by webpro** [comment]
The second example is a bit unfortunate, but looking at https://nextjs.org/docs/app/building-your-application/configuring/eslint, this is the same idea:

- `plugin:@next/next/recommended` → `@next/eslint-plugin-next`

**Comment by JoshuaKGoldberg** [comment]
Oh yeah Next does its own weird things. https://github.com/vercel/next.js/blob/b2a3ac60acc5efd9cebb0b04bef4f98c0e182326/packages/eslint-config-next/index.js has context & links to relevant projects.

...so I should say, while typescript-eslint special, Next.js is 😄

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.19.1. See [Release 2.19.1](https://github.com/webpro/knip/releases/tag/2.19.1) for release notes._

**Comment by webpro** [comment]
Thanks, Josh. Found the logic after all :)
