### ISSUE TITLE
Equivalent of ts-prune-ignore-next

### ISSUE THREAD

**Issue by eppisapiafsl** [webpro/knip#198]
Hey! 

I'm looking for a way to ignore "new code" that is added to be detected as unused/deadcode

Is there an equivalent of `// ts-prune-ignore-next` ?

**Comment by voxpelli** [comment]
Can you describe the use case?

Is this because you run `knip` in a commit hook and wants to be able to commit in-progress code? Or is it because you run it on save?

Personal reflection is that if it's only for new code then I would want it to expire somehow. How does it work for ts-prune?

**Comment by webpro** [comment]
Next to `ignore` the whole file, there are currently a few ways to handle this: https://github.com/webpro/knip/blob/main/docs/handling-issues.md#unused-exports

If that's not what you need, I also like to know the use case. And if there's something Knip should fix or handle better I'm all ears :)

**Comment by TkDodo** [comment]
if I read this correctly, marking an exported function as `/** @public */` would be the equivalent, right?

```diff

- // ts-prune-ignore-next
+ /** @public */
export function myUnusedFunction() { ... }
```

**Comment by webpro** [comment]
That's effectively the same thing indeed.

**Comment by eppisapiafsl** [comment]
Thanks `/** @public */` works as expected 🚀
