### ISSUE TITLE
Detecting unused enum values

### ISSUE THREAD

**Issue by NeoPhi** [webpro/knip#20]
Not sure how possible it would be but the ability to detect unused enum values would be a nice addition.

**Comment by webpro** [comment]
Kind of the same idea as #11. Will take this into account then!

**Comment by webpro** [comment]
I have released an initial version to support this. Any chance you could give it a shot on your repo(s)? Two issue types "class members" and "enum members" have been added. It's a pre-release ([v0.13.0-members.0](https://github.com/webpro/knip/releases/tag/0.13.0-members.0)), it can be installed like this:

```
npm install knip@members
```

Thanks in advance for your feedback.

**Comment by NeoPhi** [comment]
I was able to successfully run this on two of our code bases and it correctly identified unused class members and unused enum members.

**Comment by webpro** [comment]
Thanks @NeoPhi! This was added in [v0.13.0](https://github.com/webpro/knip/releases/tag/0.13.0)
