### ISSUE TITLE
Astro support

### ISSUE THREAD

**Issue by DaniFoldi** [webpro/knip#201]
Hi :wave:

I recently discovered knip, and love its simplicity! I was in the process of converting some projects to use knip, however I discovered that .astro is not currently supported.

Unfortunately, I don't have enough knowledge in the world of js compilers to integrate the compiler myself, however it seems that other than supporting the frontmatter syntax, creating a plugin should be rather straightforward, as astro is easy to find in a project (dev/dependency of `astro`), and entry files are simple to match (4 possible config files and src/pages/**).

**Comment by webpro** [comment]
Extensions that are not JS/TS/JSX are not supported. Same for MDX, Vue, Svelte, etc.

Not an Astro user myself, However, adding the Astro as a custom compiler should be possible. I tried briefly before a few months back, but got stuck on the Astro compiler not playing nice with `esm-loader` (which was later replaced by jiti).

Perhaps even just some regexes to extract the import statements (and configuring the entry files you mention) might get you pretty far.

Did you see the examples in https://github.com/webpro/knip/blob/main/docs/compilers.md?

**Comment by webpro** [comment]
We can close this now that @DaniFoldi implemented the plugin and a configuration example is documented.
