### ISSUE TITLE
Unresolved imports for ?raw

### ISSUE THREAD

**Issue by pkolt** [webpro/knip#202]
Hi guys 🖐️!

I used React component with `?raw` import:

```jsx
import CalendarIcon from './icons/calendar.svg?raw';
import GitHubIcon from './icons/github.svg?raw';
import TwitterIcon from './icons/twitter.svg?raw';
import LinkedInIcon from './icons/linkedin.svg?raw';

// ...
```

[https://github.com/pkolt/pkolt.ru/blob/master/src/components/Icon/index.tsx](https://github.com/pkolt/pkolt.ru/blob/master/src/components/Icon/index.tsx)

When I run `npx knip` i see an error:

```
Unresolved imports (4)
./icons/calendar.svg?raw  src/components/Icon/index.tsx
./icons/github.svg?raw    src/components/Icon/index.tsx
./icons/linkedin.svg?raw  src/components/Icon/index.tsx
./icons/twitter.svg?raw   src/components/Icon/index.tsx
```

As far as I understand, the book does not see such imports (with `?raw`). Can this be fixed somehow?

Thanks!

**Comment by webpro** [comment]
You might have luck with something like `ignore: ["**/*.svg?raw"]`

However, Knip should probably feature import mapper functionality and/or custom module resolver(s). Not there yet!

**Comment by pkolt** [comment]
> You might have luck with something like `ignore: ["**/*.svg?raw"]`

Thanks for your reply. But unfortunately it didn't help, it still outputs:

```
Unresolved imports (4)
./icons/calendar.svg?raw  src/components/Icon/index.tsx
./icons/github.svg?raw    src/components/Icon/index.tsx
./icons/linkedin.svg?raw  src/components/Icon/index.tsx
./icons/twitter.svg?raw   src/components/Icon/index.tsx
```

**Comment by webpro** [comment]
Perhaps Knip can remove the `?` and everything behind it in import specifiers (and then `.svg` would end up as an extension to ignore). This reminds me of Webpack. I'll look into that too.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.19.5. See [Release 2.19.5](https://github.com/webpro/knip/releases/tag/2.19.5) for release notes._

**Comment by gajus** [comment]
Not clear what's the unblock here. @webpro 

The import:

```
import logoWithGradient from './logo-with-gradient.svg?url';
import logoWithName from './logo-with-name.svg?url';
import logoWithoutName from './logo-without-name.svg?url';
import { Box, type BoxProps } from '@/components/Primitives/Box.js';
```

The error:

```
Unresolved imports (3)
./logo-with-gradient.svg?url  src/components/Logo/src/Logo.tsx
./logo-with-name.svg?url      src/components/Logo/src/Logo.tsx
./logo-without-name.svg?url   src/components/Logo/src/Logo.tsx
```

I tried adding:

`"**/*.svg"` and `"**/*.svg?url"` to ignore paths with no luck.

If relevant, the types are declared such way:

```ts
declare module '*.svg?url' {
  const value: string;

  export default value;
}
```

**Comment by webpro** [comment]
That's odd, can't reproduce it here. You should not need to manually ignore such patterns. Unfortunately the module declaration `*.svg?url` is still mysteriously not actually used by the underlying TypeScript program. But such paths are sanitized from the `?...` suffix and then `.svg` will be ignored.

There's some test coverage and fixtures around this, e.g. in https://github.com/webpro/knip/blob/main/fixtures/unresolved/src/index.ts

Happy to look into a case if this is in a public repo?

**Comment by ryanwilsonperkin** [comment]
Hey @webpro, I'd be interested in reopening this issue, I've created a public repo with a reproduction here (albeit using `?url` instead of `?raw`)

https://github.com/ryanwilsonperkin/knip-issue-asset-suffix

In this scenario, we're trying to configure Knip to find any unused `.svg` assets. Knip appears to be correctly stripping the `?url` suffix from the import to find the underlying asset, but it then reports the asset as unused, presumably because the full filepath does not match the URL that was seen (which included the suffix).

**Comment by webpro** [comment]
Should be good now, @ryanwilsonperkin

**Comment by ryanwilsonperkin** [comment]
Thank you!
