### ISSUE TITLE
Even though it is a library that is imported and used, some libraries are subject to the Unused Dependencies policy.

### ISSUE THREAD

**Issue by siosio34** [webpro/knip#203]
Hello Even though many of the libraries that are imported and used are used, it seems to be displayed as Unused dependencies. Has any of you had the same problem and solved this problem?

**Comment by webpro** [comment]
It sounds like you're seeing false positives. This is normal. Knip is not magic, in most projects you need to help it with some configuration, such as providing `entry` paths. Please read the documentation carefully and give more details about what you've tried, what you're seeing and why. Is the repository you're working in open so I can take a look?

**Comment by siosio34** [comment]
sorry. There was only project: ['src/**/*.ts''] in the knip setting, but it was resolved after modifying project: ['src/**/*.ts', 'src/**/*.tsx'] as follows It has been.
