### ISSUE TITLE
Bug: binary/dependency not detected from execa's $ with options

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#207]
https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/227afa261074a57b59c91d436892e6da19f744ac/script/hydrate-test-e2e.js#L10-L12 is an end-to-end test that uses [`execa`](https://github.com/sindresorhus/execa)'s [`$`](https://github.com/sindresorhus/execa/blob/88ee3bd6fa7c42e99452127f1903bee36519862c/docs/scripts.md) to run [`c8`](https://www.npmjs.com/package/c8). Trimming the code down a bit:

```jsonc
// package.json
{
	"devDependencies": {
		"c8": "^8.0.1",
		"execa": "^7.2.0"
	}
}
```

```js
// script/hydrate-test-e2e.js
import { $ } from "execa";

await $({ stdio: "inherit" })`c8 node hydrate.js`;
```

That script causes Knip to complain about `c8` being unused:

```plaintext
$ knip

Unused devDependencies (1)
c8  package.json

$ knip --version

2.19.5
```

Note that Knip produces no complaints if the script is switched to <code>$`c8 script.js`</code> (no options).

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.19.6. See [Release 2.19.6](https://github.com/webpro/knip/releases/tag/2.19.6) for release notes._
