### ISSUE TITLE
Enable plugins for dependencies listed in the top-level package.json in monorepos.

### ISSUE THREAD

**Issue by yvan33** [webpro/knip#213]
In a monorepo using yarn or npm workspaces, a shared dependency can be listed in the top level package.json.
When that is the case, knip currently doesn't detect it and doesn't enable the plugin associated to it in the monorepo packages.
Knip only enable plugins if the associated dependencies are listed in the given package's `package.json`.

It would be nice if knip could enable plugins for packages when the dependency is listed in the top level `package.json`.

Example: In my monorepo, I have 3 packages that are all using the same Cypress version. This is best for me to have the `cypress` dependency in the root `package.json` so I can easily upgrade it for all packages and ensure all packages stay on the same version. I would love for knip to enable the cypress plugin for all my packages but that's currently not the case.

**Comment by webpro** [comment]
Knip is supposed to work as you expected: it enable plugins in descendant workspaces if an ancestor workspace has it enabled.

Coincidentally, [one of the fixtures even uses `cypress` as an example](https://github.com/webpro/knip/blob/main/fixtures/workspaces/package.json#L10).

When I run Knip in this fixture folder in debug mode (`-d`) I see:

```
[knip] Enabled plugins (.)
[ 'Cypress', 'TypeScript' ]
```

And then in the other workspaces (that does not have `cypress` listed in `package.json`) I see `Cypress` as well:

```
[knip] Enabled plugins (apps/backend)
[ 'Cypress', 'Next.js', 'PostCSS', 'TypeScript' ]
```

So now I wonder whether Knip has a bug or why the plugin is not enabled in your root workspace. Any chance you could share more details or even your repository?

**Comment by yvan33** [comment]
Hi @webpro, 

Thanks for your answer. I am able to reproduce what you are seeing.
As an example, Cypress plugin is properly enabled for the `apps/frontend` package when I run `npx knip --debug` from the `fixtures/workspaces` folder:
![image](https://github.com/webpro/knip/assets/4263846/76a56357-9114-4c34-b6b7-95b483e0e8fc)


That being said, if I run `knip` on a specific workspace with `npx knip --debug --workspace apps/frontend`, then the plugin is not enable for the specified workspace, and this is the issue.
![image](https://github.com/webpro/knip/assets/4263846/a0839e6d-56dc-4ad3-8c64-6b8d2b66cf30)

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.21.1. See [Release 2.21.1](https://github.com/webpro/knip/releases/tag/2.21.1) for release notes._

**Comment by webpro** [comment]
Thanks for the report @yvan33, now I saw the issue was that when using `--workspace [dir` ancestor workspaces were no longer included since a refactoring a few minors ago (probably v2.17.2).

**Comment by yvan33** [comment]
Thank you for fixing it so fast @webpro ! Highly appreciated!
