### ISSUE TITLE
NextJS with `src` in monorepo support

### ISSUE THREAD

**Issue by t1mmen** [webpro/knip#218]
I've got a yarn monorepo with the below structure, in addition to other `/packages/*` and `/apps/*` (that are analyzed just fine)

```
/apps
  /integrations-cloud <-- nextjs project
    /src
      /pages
```

The error:
```
~/work/monorepo  add-integration-cloud ✗                                                     52m ⚑ ◒  ⍉
▶ yarn knip -V
2.19.11

~/work/monorepo  add-integration-cloud ✗                                                      52m ⚑ ◒
▶ yarn knip
Analyzing workspace (apps/integration-cloud)...
/Users/timm/work/monorepo/apps/integration-cloud/node_modules/next/dist/lib/find-pages-dir.js:54
        throw new Error("> Couldn't find any `pages` or `app` directory. Please create one under the project root");
              ^

Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
    at findPagesDir (/Users/timm/work/monorepo/apps/integration-cloud/node_modules/next/dist/lib/find-pages-dir.js:54:15)
    at /Users/timm/work/monorepo/apps/integration-cloud/node_modules/next/dist/build/jest/jest.js:120:75
    at async module.exports (/Users/timm/work/monorepo/apps/integration-cloud/jest.config.js:43:24)
    at async Module.findJestDependencies (file:///Users/timm/work/monorepo/node_modules/knip/dist/plugins/jest/index.js:62:18)
    at async WorkspaceWorker.findDependenciesByPlugins (file:///Users/timm/work/monorepo/node_modules/knip/dist/WorkspaceWorker.js:217:46)
    at async WorkspaceWorker.findAllDependencies (file:///Users/timm/work/monorepo/node_modules/knip/dist/WorkspaceWorker.js:235:9)
    at async main (file:///Users/timm/work/monorepo/node_modules/knip/dist/index.js:168:30)
    at async run (file:///Users/timm/work/monorepo/node_modules/knip/dist/cli.js:26:73)
    at async file:///Users/timm/work/monorepo/node_modules/knip/dist/cli.js:71:1

Node.js v18.17.1
```

Knip works fine if I run it from /apps/integrations-cloud, so presumably a NextJS plugin issue. https://github.com/webpro/knip/blob/main/src/plugins/next/index.ts#L17 appears to support the `src` dir, but it seems NextJS (v13.4.15) gets confused before that is reached?

PS: Just found this project, and I'm loving it already. Thank you for building it!

**Comment by webpro** [comment]
Seeing Jest in there too. Do you have a repo(r) I can look at?

**Comment by t1mmen** [comment]
@webpro I'm afraid I can't share this repo, but you're probably on to something. Given your pointer, I suspect it may be related to https://gist.github.com/t1mmen/fe0caae1b068bafbeaef1e738693d793#file-jest-config-js-L18 (the jest config in question)

If the `src` dir should otherwise work in a monorepo, it's likely a configuration error on my side. Feel free to close, and I'll re-post if the issue persists.

Knip was very helpful in identifying some other issues we're having with the merging of two monorepos, but lots of work remains on that still, so this issue got knocked down on the priority list of things to look at.

Appreciate the speedy reply, thank you!

**Comment by webpro** [comment]
More pointers:

- #189
- https://discord.com/channels/1143209786612125696/1143209787140620310/1143573153017254002

Bottom line: use absolute paths when possible, sometimes external helpers use incorrect process.cwd()

**Comment by t1mmen** [comment]
@webpro Ref [my Jest config](https://gist.github.com/t1mmen/fe0caae1b068bafbeaef1e738693d793#file-jest-config-js-L5), the change required turned out to be:

```diff
const createJestConfig = nextJest({
-  dir: './',
+  dir: __dirname, 
});

Not sure if this is something your could or should do anything about in knip itself, but now you know the workaround :)

**Comment by wjureczka** [comment]
It worked, thanks!
