### ISSUE TITLE
InvalidOperationError: A child of the kind Identifier was expected.

### ISSUE THREAD

**Issue by fxOne** [webpro/knip#22]
I wanted to try this great tool for our project, but I get this error message:
```
Processing: packages/store/src/Reducer/OptimisticReduce.ts
/var/www/html/node_modules/@ts-morph/common/dist/ts-morph-common.js:448
            throw new InvalidOperationError(typeof errorMessage === "string" ? errorMessage : errorMessage());
                  ^

InvalidOperationError: A child of the kind Identifier was expected.
    at Object.throwIfNullOrUndefined (/var/www/html/node_modules/@ts-morph/common/dist/ts-morph-common.js:448:19)
    at FunctionDeclaration.getFirstChildByKindOrThrow (/var/www/html/node_modules/ts-morph/dist/ts-morph.js:3776:36)
    at file:///var/www/html/node_modules/knip/dist/runner.js:115:54
    at Array.forEach (<anonymous>)
    at file:///var/www/html/node_modules/knip/dist/runner.js:85:34
    at Map.forEach (<anonymous>)
    at file:///var/www/html/node_modules/knip/dist/runner.js:84:36
    at Array.forEach (<anonymous>)
    at findIssues (file:///var/www/html/node_modules/knip/dist/runner.js:61:29)
    at main (file:///var/www/html/node_modules/knip/dist/index.js:108:40)

Node.js v18.12.0
```
Is there anything I can do to find out where the problem is in `OptimisticReduce.ts`?

I'm using the latest version of knip.

**Comment by webpro** [comment]
Any chance you could share `OptimisticReduce.ts`? Or perhaps just something you think might be the issue?

Not sure what to suspect here. The error is coming from [this block](https://github.com/webpro/knip/blob/main/src/runner.ts#L144-L151) so fwiw it should be a function, class, type, interface or enum declaration.

**Comment by fxOne** [comment]
Looks good so far. Now I just have to analyze the result ;)

**Comment by webpro** [comment]
@fxOne Great! Any chance you could still share the file contents? I'd still like to know what exactly the culprit was here, maybe Knip can find something unused even though that `Identifier` is missing.
