### ISSUE TITLE
How to deal with peer dependencies?

### ISSUE THREAD

**Issue by MidnightDesign** [webpro/knip#220]
I'm trying Knip for the first time right now, and I'm thoroughly enjoying it so far. I've deleted a couple of unused files and un-exported many symbols that weren't used outside the declaring module.

Now I'm just left with a bunch of `Unused devDependencies` that I've explicitly installed because they are peer dependencies of other dev dependencies. What's the "correct" way of dealing with them? Just put them in the list of ignored dependencies in the Knip config? That seems kinds wrong because then I'll never know when I can _actually_ remove them.

**Comment by MidnightDesign** [comment]
Wait, are they reported because the dependencies that list them as peer dependencies are themselves unused?

**Comment by webpro** [comment]
> Wait, are they reported because the dependencies that list them as peer dependencies are themselves unused?

Yeah, this is the idea indeed :)

(Also see #194 re. optional peer dependencies)

**Comment by MidnightDesign** [comment]
Alright, "works as intended" then. Thanks for the reply.
