### ISSUE TITLE
False positive unused-export in class override

### ISSUE THREAD

**Issue by eppisapiafsl** [webpro/knip#224]
Hello! 

I'm running Knip to only check `unused-exports` with `knip --include exports --no-gitignore`, but face a weird report when the export value is used in a override method 

So I have some constant object declare like:
```typescript
// File stateValue.ts

export const supportState_1 = { 
      assets: ["1", "2", "3"],
      location: "Spain",
      ...
 }
 
 export const supportState_2 = { 
      assets: ["1", "4", "8"],
      location: "Barcelona",
      ...
 }
 ```
 
 And two classes in separated files that import the respective constant object
 ```
 // File: MadridState.ts
 
 export class SpainStateMachine extends BaseStateMachine {
  override getStateMachine() {
    return supportState_1;
  }
  
// File: BarcelonaState.ts
 export class BarcelonaStateMachine extends SpainStateMachine {
  override getStateMachine() {
    return supportState_2;
  }
```

Knip report `supportState_2` as unused export even that is being imported by `BarcelonaState.ts`

Any hint what could cause the Knip report the `supportState_2` as unused? 

### System
Knip@2.19.3
Node 18.15.0
TS 5.1.6

**Comment by webpro** [comment]
No, any chance you could give a full yet minimal rep(r)o?
