### ISSUE TITLE
Docs: Broken README.md #handling-issues link

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#227]
https://github.com/webpro/knip/blob/d9e597dee2fe99662e6d8925bbb068791b8a0dd8/README.md?plain=1#L827

This doesn't exist. Should it be merged into `[50]`?

https://github.com/webpro/knip/blob/d9e597dee2fe99662e6d8925bbb068791b8a0dd8/README.md?plain=1#L829

**Comment by webpro** [comment]
Thanks a lot, Josh. This is now fixed and I also installed a Markdown link checker to prevent regressions.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.21.2. See [Release 2.21.2](https://github.com/webpro/knip/releases/tag/2.21.2) for release notes._
