### ISSUE TITLE
Unused exports in namespaces

### ISSUE THREAD

**Issue by irekrog** [webpro/knip#229]
In version 2.20.1 there are no errors, but since version 2.20.2 there is `Unused exports in namespaces`

Here is the repo https://github.com/irekrog/test-knip

Steps to reproduce:
1. install knip v2.20.1
2. run `yarn knip`
3. no errors
4. install knip v2.20.2 (or the latest v2.21.1)
5. run `yarn knip`
6. `Unused exports in namespaces (1) MyButton  src/components/my-button/index.ts`

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.21.2. See [Release 2.21.2](https://github.com/webpro/knip/releases/tag/2.21.2) for release notes._

**Comment by webpro** [comment]
Thanks for the detailed report and repro, very helpful.

A fix in v2.20.2 revealed another bug, eventually caused by `ts.findReferences` (or at least the one in Knip) having issues looking up deep star imports. It should now be faster in large projects, so that's a bonus :)
