### ISSUE TITLE
`eslint-plugin-prettier` possible regression

### ISSUE THREAD

**Issue by a-ursino** [webpro/knip#230]
Hi

I'm aware of https://github.com/webpro/knip/issues/128 but noticed a similar behaviour using latest knip.

I've created a demo that uses `npx create vue@latest` as starting point to reproduce the issue https://github.com/a-ursino/vue-knip-demo/pull/1

**Comment by a-ursino** [comment]
I've installed both `eslint-config-prettier` and `eslint-plugin-prettier` and added `plugin:prettier/recommended` in the extends in my PR https://github.com/a-ursino/vue-knip-demo/pull/1/files.
Am I missing something else?

**Comment by webpro** [comment]
Ah no my apologies, the issue is indeed with the `/recommended` path. I'll fix it shortly.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.22.0. See [Release 2.22.0](https://github.com/webpro/knip/releases/tag/2.22.0) for release notes._

**Comment by webpro** [comment]
Thanks for the rep(r)o @a-ursino, very helpful.

**Comment by a-ursino** [comment]
Thanks for the amazing tool and quick fix.
