### ISSUE TITLE
`lefthook` reported as unused devDependencies

### ISSUE THREAD

**Issue by a-ursino** [webpro/knip#231]
Hi

In a basic vue app created with `npx create vue@latest` and knip, adding lefthook dep and config results in knip reporting lefthook unused.
Here a reproduction https://github.com/a-ursino/vue-knip-demo/pull/2.

**Comment by webpro** [comment]
I remember having `lefthook` referenced in e.g. the `package.json#postinstall` script. How would you use it? It's not referenced anywhere?

**Comment by a-ursino** [comment]
It should be the `postinstall` inside lefthook that does the setup (on `npm i`) for the git hooks. I did try to clone https://github.com/a-ursino/vue-knip-demo and with only a `npm i` I have lefthook in `node_modules/.bin/lefthook` and running with `pre-commit`.

**Comment by webpro** [comment]
Now I see that the workflow (with `"postinstall": "lefthook install"` in my own `package.json`) was removed with v1.

The good news is that the lefthook plugin can probably copy most of husky's plugin logic (i.e. read the actual hook scripts and look for executables, which will include `lefthook` itself). Stay tuned :)

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.22.0. See [Release 2.22.0](https://github.com/webpro/knip/releases/tag/2.22.0) for release notes._

**Comment by webpro** [comment]
Got a bit hairier than I wanted, but should be OK now. Thanks for bearing with me and helping me out!

**Comment by a-ursino** [comment]
Thanks for addressing this @webpro 
It does indeed fix the issue when I run it locally (after installing knip 2.22.0). However, when I run it on CI it fails.
I've updated the PR https://github.com/a-ursino/vue-knip-demo/pull/2 to add Github actions to run knip there after the update https://github.com/a-ursino/vue-knip-demo/actions/runs/6107110520/job/16573473827?pr=2
Is there a special CI mode that I need to use for knip in CI. 
I'm pretty sure that lefthook does things differently on CI (e.g. https://github.com/evilmartians/lefthook/blob/master/packaging/npm/lefthook/postinstall.js#L5)

**Comment by webpro** [comment]
Knip checks whether there's hook scripts in the Git `core.hooksPath` location (default: `.git/hooks`). The scripts there should contain some reference to the installed package (`lefthook` or `@arkweid/lefthook`). Otherwise Knip assumes that the package is not in use.

I guess Lefthook doesn't do the `npm postinstall` thing to install those scripts in the hooks folder in the CI environment?

**Comment by a-ursino** [comment]
yeah, it is possible that lefthook does some magic in CI to avoid the installation. It would be useless to have it there.

**Comment by webpro** [comment]
From a Knip perspective, the alternative is to simply return `lefthook` as a dependency when `lefthook` is found in the list of `package.json#dependencies`, but that would defeat the purpose of the plugin (other than finding extra dependencies used by the scripts/hooks).

Not sure how to deal with this, the `if (process.env.CI) return;` thing in CI is difficult to understand while things run as expected locally. It's ugly, but maybe Knip should basically do the same thing: `if (process.env.CI) return ['lefthook'];` and call it a day.

**Comment by a-ursino** [comment]
I would say that check and maybe the presence of the config file
```
if (process.env.CI && lefthookConfigFile) return ['lefthook'];
``

**Comment by webpro** [comment]
Added this in v2.23.0, also added `@evilmartians/lefthook` as alias/enabler.

**Comment by a-ursino** [comment]
Thanks for addressing both bugs @webpro 💯
