### ISSUE TITLE
Unused exports are never detected with Next.js plugin in app router projects

### ISSUE THREAD

**Issue by jonahsnider** [webpro/knip#235]
https://github.com/webpro/knip/blob/838175cca9b6182cb8500ebf79a134167fd23b4e/src/plugins/next/index.ts#L16

When using the app router (where source code is in `app`), the only entrypoints possible are
- `instrumentation.{js,ts}`
- `middleware.{js,ts}`
- `app/{manifest,sitemap,robots}.{js,ts}`
- `app/**/{opengraph,twitter}-image.{js,ts,tsx}`, except for when any directory in the path starts with a `_`
- `app/**/{icon,apple-icon}-image.{js,ts,tsx}`, except for when any directory in the path starts with a `_`
- `app/**/{page,layout,error,not-found,template,loading}.{jsx,tsx}`, except for when any directory in the path starts with a `_`
- `app/**/route.{js,ts}`, except for when any directory in the path starts with a `_`
- All of those paths, but prefixed with `src/`

Right now the entrypoints in the Next.js plugin are effectively adding every single file in `app/**` as an entrypoint, which prevents Knip from catching any unused exports

**Comment by webpro** [comment]
Thanks @jonahsnider. Yeah that isn't great. Didn't use that app dir myself, I had no idea tbh.

- Can you come up with globs that also take the `_` exclusions into account?
- Can you open a pull request?

Just saying, you can override the `next` config locally. Obviously would love to welcome improvements into Knip for everyone to enjoy.

**Comment by jonahsnider** [comment]
> * Can you come up with globs that also take the `_` exclusions into account?

Maybe? I feel like a glob that matches that would be very inefficient to match against. It's also a semi niche use case, so I think it'd be fine to just not account for that.

> * Can you open a pull request?

Yes

> Just saying, you can override the `next` config locally.

That's what I have done in my project for now :)
