### ISSUE TITLE
Remix - Unable to load package.json for packages/remix-dev

### ISSUE THREAD

**Issue by revnandi** [webpro/knip#238]
Hi!

I'm trying to use knip with Remix but i get this error:
```
➜  project git:(master) ✗ npx knip
Analyzing workspace (packages/remix-dev)...
Unable to load package.json for packages/remix-dev
```
[This](https://github.com/webpro/remix/blob/feature/introduce-knip/knip.jsonc) is the knip.jsonc in the root folder
I'm using the [epic-stack](https://github.com/epicweb-dev/epic-stack) starter if that makes a difference

**Comment by webpro** [comment]
I'll look into it.

Looks odd at first sight. The issue sounds like a missing or invalid `package.json`, but that one seems fine.

**Comment by revnandi** [comment]
> Hi @revnandi
> 
> It sounds like you are working in a repository with directory layout from https://github.com/epicweb-dev/epic-stack
> 
> If that's the case you are not using workspaces and shouldn't have a `workspaces` key in your `knip.jsonc`

Thank you, it works now.
