### ISSUE TITLE
`@types/react-dom` marked as unused, despite being requested as a peer dependency

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#239]
Reproduction: https://github.com/alecmev/knip-repro-239 I thought about this for a bit, trying to figure out if it's Babylon.js' fault, but I don't think it is? They just want to pin the version, so that we don't run into any mismatch issues. I also don't think this is https://github.com/webpro/knip/issues/220, unless there's a bug?

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.25.1. See [Release 2.25.1](https://github.com/webpro/knip/releases/tag/2.25.1) for release notes._

**Comment by webpro** [comment]
Agreed :)

**Comment by alecmev** [comment]
Thank you! :ok_hand:
