### ISSUE TITLE
[Feature Request] @types/<package> for packages that already include types as Unused

### ISSUE THREAD

**Issue by dylang** [webpro/knip#241]
Hi, great project!

I noticed that Webpack 5 now includes types, so including `@types/webpack` is no longer necessary.

We probably have a lot of packages like this.

To figure out which packages now include types, maybe we can look in each dependency's `package.json` for a `"types"` key?

**Comment by webpro** [comment]
What is the issue you're seeing? Is `@types/webpack` being reported as a false positive?

**Comment by ElPrudi** [comment]
I see the potential too: If the dependency comes with it's own type definitions, and you have a `@types` dependency of it installed that is now deprecated, it's useless and should be removed, no matter if you included it or not.

**Comment by dylang** [comment]
In the example above, `@types/webpack` should be reported as unused.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.30.0. See [Release 2.30.0](https://github.com/webpro/knip/releases/tag/2.30.0) for release notes._

**Comment by webpro** [comment]
As far as I can see Knip just needs to check for the `types (or `typings`) field in `package.json`, so that's what it's doing now :)

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.32.0. See [Release 2.32.0](https://github.com/webpro/knip/releases/tag/2.32.0) for release notes._
