### ISSUE TITLE
Fix support for `baseUrl` in typescript projects

### ISSUE THREAD

**Issue by antoine-malliarakis** [webpro/knip#244]
### Issue description

In the context of our projects heavily rely on the usage of the `baseUrl` parameter in our typescript configurations. 

The issues is that intra workspace package dependencies (e.g. imports from other workspace packages) are not appropriately spotted, leading to project resources invalidly flagged as unused.

**Comment by webpro** [comment]
> (the idea being that any js file is being refered to directly)

This is the main issue here. Assuming you're in a monorepo, you should not be referencing files in other workspaces directly? But importing them properly using package identifiers and import maps. If you don't want to do that you can still opt into things like `ignoreWorkspaces` or `ignoreDependencies` or `@public` tags.

But maybe I'm missing something? Just guessing based in the input provided.

**Comment by antoine-malliarakis** [comment]
> > (the idea being that any js file is being refered to directly)
> This is the main issue here. Assuming you're in a monorepo, you should not be referencing files in other workspaces directly? But importing them properly using package identifiers and import maps. If you don't want to do that you can still opt into things like ignoreWorkspaces or ignoreDependencies or @public tags.
> 
> But maybe I'm missing something? Just guessing based in the input provided.

Actually we are importing resources using (classic ?) `<package_id>/<path_from_root_of_package>` identifiers, example `@sorare/core/src/components/card`.

From what I can see the `ignoreWorkspaces` and `ignoreDependencies` would actually be missing our point since they would be essentially configured to rule out our "shared" packages.

My use case would be essentially the following:

Let's say I have the below structure:

```
root
\-- packages
     +-- utilitary-package
          +-- package.json
          \-- src
              \-- index.js
     \-- web-app
          + package.json
          \-- src
              \-- index.js
```

If, in the `utilitary-package` (referenced from `web-app`) I define no entry point, only "projects" files, all files will be flagged as unused, even though they could be used by web-app.

The idea with this feature would be to allow such "private" workspace to enlist for being referenced to by other packages from the same workspace.

(To be honest I'm experimenting a lot and trying to tweak configurations so I may have missed something)

**Comment by webpro** [comment]
Any chance you could whip up a minimal rep(r)o for this? That would help a lot, then we can take it from there and look at our options.

**Comment by webpro** [comment]
Why would you use the empty array for `entry: []`? Now every workspace does not use any file. My advice would be to remove it.

In case you want to have the util packages not use the default entry file then you can either set that empty array for only that workspace, or use a different file name (i.e. not `index.ts`).

**Comment by antoine-malliarakis** [comment]
> Why would you use the empty array for entry: []? Now every workspace does not use any file. My advice would be to remove it.

Actually I only declared it to simplify declaration. It seems that the webapp-a manifest entry paths were actually used, unless I missed something ?

> In case you want to have the util packages not use the default entry file then you can either set that empty array for only that workspace, or use a different file name (i.e. not index.ts).

Will be altering the workspace configuration so that it's more explicit.

**Comment by webpro** [comment]
> Actually I only declared it to simplify declaration. It seems that the webapp-a manifest entry paths were actually used, unless I missed something ?

I understand the confusion: Knip reads the `main` field from `package.json` and also adds that as an entry file. That's not obvious indeed.

For future reference, running with the `--debug` flag could help. In this case it would show something like this:

```
[knip] Found entry paths from manifest (packages/webapp-a) (1)
[
  '[...]/packages/webapp-a/index.ts'
]
```

**Comment by homburg** [comment]
We use the same monorepo premise: importing files across workspaces in a monorepo, without `package.json`:`main` config.

In my test: https://github.com/homburg/hello-knip/pull/6 knip seems to understand this correctly:

- An unused library component (`Unused.tsx`) is marked as unused
- A used library component (`Hello.tsx`) is not listed/marked as used

I hope this will be supported in knip in the future as well

**Comment by antoine-malliarakis** [comment]
> We use the same monorepo premise: importing files across workspaces in a monorepo, without package.json:main config.

> In my test: https://github.com/homburg/hello-knip/pull/6 knip seems to understand this correctly:

> An unused library component (Unused.tsx) is marked as unused
> A used library component (Hello.tsx) is not listed/marked as used
> I hope this will be supported in knip in the future as well

By checking your code it seemed to do the trick but when I checked this out this morning it gave me:

```
Unused files (2)
libs/lib-1/components/Hello.tsx
libs/lib-1/components/Unused.tsx
Unused dependencies (2)
eslint              apps/next-site/package.json
eslint-config-next  apps/next-site/package.json
Unused devDependencies (1)
prettier  package.json
```

Would need to check what happened in your recent changes.

**Comment by homburg** [comment]
Hi @antoine-malliarakis

I can't seem to reproduce your result (`Hello.tsx` marked as unused) on https://github.com/homburg/hello-knip/pull/6

What commands are you using to run knip? I'm wondering if you running a particular version

My normal setup for running knip in the repo is:
- `bun install`
- `./node_modules/.bin/knip`

**Comment by antoine-malliarakis** [comment]
> Hi @antoine-malliarakis
> 
> I can't seem to reproduce your result (`Hello.tsx` marked as unused) on [homburg/hello-knip#6](https://github.com/homburg/hello-knip/pull/6)
> 
> What commands are you using to run knip? I'm wondering if you are running a particular version
> 
> My normal setup for running knip in the repo is:
> 
> * `bun install`
> * `./node_modules/.bin/knip`

Actually I wasn't using bun. I was using npm. Let me retry with that one.

**Comment by antoine-malliarakis** [comment]
@homburg so here we're in an awkward situation. Using bun it works.

Unfortunately I'm not sure that using bun is a viable plan in our build chain (could be checking but I doubt that "just so that knip passes" would be a sufficient motive).

Does the same issue occur for you if you try using npm ?

**Comment by homburg** [comment]
@antoine-malliarakis That's interesting :-) I'll try looking into how it works with `npm install`. 

I was using yarn (berry) before, which seemed to work as well

**Comment by homburg** [comment]
> To be fair we are using yarn 1. I was trying to use npm because it seemed to me that would be the closest to "bare metal" but then it seems that evidence is proving me wrong. Could that be related to the usage of "workspace:*" ? (We are not using such tricks on our side since we're using yarn 1)

An I was naively thinking that the package manager wouldn't affect the result :-) bun was just faster in github actions

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.26.0. See [Release 2.26.0](https://github.com/webpro/knip/releases/tag/2.26.0) for release notes._

**Comment by webpro** [comment]
Full disclosure. What was not supported yet: having non-entry files being imported from another workspace in the same monorepo AND at least one of the workspaces configured a `compilerOptions.baseUrl` in `tsconfig.json` (even if just a `"."`). That should be fixed now.

**Comment by antoine-malliarakis** [comment]
Thanks !
