### ISSUE TITLE
Jest rootDir using CWD instead of path of config

### ISSUE THREAD

**Issue by camjc** [webpro/knip#250]
Using knip 2.25.2

I have my jest config in
`/config/jest/jsdom.config.json`
so my 'rootDir' is `../../` (back up to the repo root).

Currently the jest plugin is doing this `../../` from the repo root.
This causes unresolved imports from the jest config

Instead of using CWD, can we use the dir that the jest config lives in?

Thanks!

**Comment by webpro** [comment]
Can you please provide a rep(r)o? There's a few things coming together here and this would save me some time. Thanks!

**Comment by webpro** [comment]
Closing this one due to inactivity. Looking at the plugin code it uses the dir of the configuration file as a basis, and if set, resolves `rootDir` compared from that. Then instances of `<rootDir>` are replaced with the result.
