### ISSUE TITLE
knip gives different results when package is installed vs. npx

### ISSUE THREAD

**Issue by robknight** [webpro/knip#251]
In https://github.com/proofcarryingdata/zupass/tree/rob/knip I've added `"knip": "npx -y knip --no-gitignore"` to the `scripts` in `package.json`. Running `yarn knip` works fine.

`knip` is not added as a dependency to `package.json`. If I add it, using `yarn add -D knip`, this means that the `npx` command will use the version of knip installed in `node_modules`, which is what I want (in fact, I can get rid of `npx` from the script entry, and just have `knip --no-gitignore`, since `yarn` will be able to find the binary once the package is installed).

However, when I do this, `knip` gives different results! In particular, it does not report any unused exports. I can't see why this would be the case.

To reproduce:
- Check out the branch mentioned
- Run `yarn knip` and observe that unused exports are listed
- Run `yarn add -D -W knip` to install knip locally
- Run `yarn knip` and observe that unused exports are _not_ listed

**Comment by webpro** [comment]
In general you'll want to populate the `node_modules` folder (i.e. run `yarn` or `npm install`) before running Knip, for most issue types. Can't guarantee Knip works well without. Maybe it's some oddity when mixing up `yarn` with `npx`? Not sure whether this is an issue with Knip at all? If it work fine with npm then that's usually leading for me.

**Comment by robknight** [comment]
Good points! I apologize for the slightly confusing issue - I was using `npx` as an alternative way of running `knip` without installing the package locally, because having the package installed seems to be what causes it to stop detecting unused exports.

This is a much simpler reproduction, without trying to show the scenario where it works properly via `npx` without the package installed:
- Check out the branch mentioned
- Run `yarn` to install packages
- Run `yarn knip` and observe that unused exports are not listed

**Comment by webpro** [comment]
I'm seeing unused exports:

```
$ yarn
yarn install v1.22.19
$ yarn knip
[...]
Unused exports (52)
Container                             apps/consumer-client/src/components/Core.tsx                                       
ExamplePageContainer                  apps/consumer-client/src/components/ExamplePage.tsx                                
IS_PROD                               apps/consumer-client/src/constants.ts                                              
openZKEdDSAEventTicketPopup           apps/consumer-client/src/pages/pcdpass-examples/zk-eddsa-event-ticket-proof.tsx    
openZKEdDSATicketPopup                apps/consumer-client/src/pages/pcdpass-examples/zkeddsa-proof.tsx                  
RippleLoaderInner                     apps/passport-client/components/core/RippleLoader.tsx                              
RippleLoaderWrapper                   apps/passport-client/components/core/RippleLoader.tsx                              
TextEllipsis                          apps/passport-client/components/core/index.tsx                                     
TextSecondary                         apps/passport-client/components/core/index.tsx                                     
Modal                                 apps/passport-client/components/modals/Modal.tsx                                   
HomeScreenImpl                        apps/passport-client/components/screens/HomeScreen.tsx                             
ArgInput                              apps/passport-client/components/shared/PCDArgs.tsx                                 
ArgTypeLabel                          apps/passport-client/components/shared/PCDArgs.tsx                                 
[...]
```

So I'm going this issue. Feel free to discuss further or open a new one as necessary.
