### ISSUE TITLE
Add CLI flag for process exit 0

### ISSUE THREAD

**Issue by avaly** [webpro/knip#26]
The [default process exit code](https://github.com/webpro/knip/blob/main/src/cli.ts#L76) with the total number of errors should probably be optional.

Here's our use case that caused issues recently:

- When I added `knip` in our stack I had to add a `knip ... || true` in our CI command that runs this tool, to not block the CI workflow
- We use automatic dependency upgrades with Renovate
- When v0.13.1 was released, which has a bug preventing it to run #25, the CI command executed successfully due to the `|| true` there, but in reality it errored out.

Proposal: Add an optional CLI flag to always use process exit code 0.

**Comment by webpro** [comment]
> to not block the CI workflow

Sometimes that exactly what you want. Sometimes the opposite.

The idea of Knip is that you can also use e.g. `knip --include files` (or whatever report interests you) to block CI (but not for issues you're not interested in).

But, there should definitely be an option to disable whatever the default is.

**Comment by avaly** [comment]
Ohh, I just noticed the `--max-issues` flag, which may be used to circumvent the behavior we're seeing. So I don't there's a need for another flag.

**Comment by webpro** [comment]
That's an escape hatch for now, I'll leave this ticket open for a better solution.

**Comment by webpro** [comment]
Feel free to install and try `knip@alpha` that has a `--no-exit-code` flag.

Not that there might be breaking errors depending on configuration, also see https://github.com/webpro/knip/blob/feature/workspaces-and-plugins/README.md

**Comment by webpro** [comment]
v1 is out, so this is in :)
