### ISSUE TITLE
Allow extending `IGNORED_FILE_EXTENSIONS`

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#269]
In our case, for example, we import `.gltf` and `.env` files. These are pretty niche, especially `.env`, so it probably doesn't make sense to add as defaults. Seems like a simple configuration option would do?

**Comment by webpro** [comment]
I did some refactorings with (declaration files) and module resolution, relative imports like `./any.ext` should work fine now. Except the `.env` dotfile with only the extension is still unresolved.

**Comment by alecmev** [comment]
Ah, awesome, thank you! In this case it's [a different type of `.env`](https://doc.babylonjs.com/features/featuresDeepDive/materials/using/HDREnvironment), so it works perfectly.
