### ISSUE TITLE
/dev/null/prepare-commit-msg error

### ISSUE THREAD

**Issue by gajus** [webpro/knip#271]
```bash
$ knip
Analyzing workspace (.)...
node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^

[Error: ENOTDIR: not a directory, stat '/dev/null/prepare-commit-msg'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '/dev/null/prepare-commit-msg'
}

Node.js v20.7.0
```

Started to get this error in the latest version of Knip.

**Comment by webpro** [comment]
Any chance if you could check whether this issue occurs in v2.21.0 (or earlier)?

**Comment by gajus** [comment]
Hm. This appears to be originating from an old version of Husky, strangely. Updating Husky fixed the issue.

**Comment by webpro** [comment]
Cool. Will be an interesting topic for Knip over time... tools with breaking changes in their configs. I could easily pass their version and deal with it inside the plugin (or split plugins), but still not something I fancy too much :)
