### ISSUE TITLE
Reporting incorrect unused files in monorepo

### ISSUE THREAD

**Issue by accordionpeas** [webpro/knip#272]
Hello,

This project looks great and I'm very keen to use it in my monorepo.

It seems that entry files and files that are imported by the entry file are incorrectly reported as unused when in a monorepo with a custom knip configuration. I have created a simple example here - https://github.com/accordionpeas/knip-demo

The project structure is:

```
- apps
    - app
        - src
            - server
                - index.ts
                - module.ts
    - package.json
- package.json
```

The root package.json is:

```
"scripts": {
    "knip": "knip"
}
...
"workspaces": [
    "apps/app"
],
...
"knip": {
    "entry": [
        "src/server/index.ts"
    ],
    "project": [
        "src/**/*.ts"
    ]
}
```

When I run `npm run knip` I get:

```
Unused files (2)
apps/app/src/server/index.ts
apps/app/src/server/module.ts
```

My understand is that these should not be reported as unused as `index.ts` is the entry file and it imports `module.ts`.

Hopefully I haven't misunderstood anything here! Thanks for your time.

**Comment by webpro** [comment]
I think you're missing the `"workspaces"` config, something like this should work:

```json
"knip": {
  "workspaces": {
    "apps/*": {
      "entry": [
        "src/server/index.ts"
      ],
      "project": [
        "src/**/*.ts"
      ]
    }
  }
}
```

**Comment by webpro** [comment]
The sharing basically happens with the `*` wildcard, even `*/*` or `**` work (but that's probably too wide). Or you could try something like `{apps,libs}/*`. Last but not least, you could go wild with a more dynamic `knip.ts` to prevent any duplication.
