### ISSUE TITLE
Find unsed methods of objects

### ISSUE THREAD

**Issue by lo1tuma** [webpro/knip#274]
I would like to see a possibility to track and find unused methods on exported objects, or objects created by exported functions.

Use Case:

Most of the time I wrap modules with side-effects in a factory function in order to do dependency-injection, e.g.

```ts
export function createMyModule(dependencies: MyDependencies): MyModule {
    const { logger, httpClient } = dependencies;

   return {
      async firstMethod() {
          logger.info('first');
          await httpClient.get('http://example.com')
      },

      async secondMethod() {
           logger.info('second');
          await httpClient.post('http://example.com')
      }
   }
}
```

Let’s say `secondMethod` is never used within my project, I want it to be flagged.

I know that this cannot be achieved in all circumstances, for example when the project is a library and those methods might by consumed by the consumers. But for app projects this is not an issue and such dead code be detected reliably. Therefore I think this feature should be disabled by default and needs to be opt-in.

**Comment by webpro** [comment]
Knip supports namespaced/star imports and class members, so some of the semantics are probably similar.

Returned values (e.g. objects) _created by exported functions_ is something Knip currently does not analyze. Not sure whether this could be implemented reliably. How to decide whether to include such a function?

Things combined, this feature might have noticeable to significant effects to performance. So yeah, opt-in as you suggest would probably make sense.

Feel free to dive into this and open a pull request, though (or anyone else). This feature request is currently not high on my priority list, but willing to assist with/look into a PR.

**Comment by lo1tuma** [comment]
> How to decide whether to include such a function?

Maybe we could simple check every function or method that end up to be exported somehow. Or if it is too hard to distinguish between exported and non-exported functions we could simply do it fall all function definitions. Although non-exported unused functions are already flagged by typescript itself and a bunch of ESLint rules. But non of those tools help to detect unused functions that are exported.

**Comment by webpro** [comment]
I'm going to close this issue. If anyone wants to pick it up, feel free to reach out and we can look into it.
