### ISSUE TITLE
Plugin for vike?

### ISSUE THREAD

**Issue by thomasjm** [webpro/knip#275]
[Vike](https://vike.dev) is a plugin for Vite which provides an improved SSR experience. It provides filesystem routing, where you create files like `pages/login.tsx`, which will then be available as `/login`. The details are described [here](https://vike.dev/filesystem-routing).

I think a Vike plugin would be useful, to automatically add all the pages as entry points for `knip`.

**Comment by webpro** [comment]
Interesting! Didn't know they renamed `vite-plugin-ssr` to Vike.

Maybe you're up for a pull request and [write a plugin](https://github.com/webpro/knip/blob/main/docs/writing-a-plugin.md)? Sounds like there are similar plugins, like the ones for Next or Remix.

**Comment by thomasjm** [comment]
I probably won't have time, but it does look pretty straightforward. Maybe there's some complexity if Vike's more advanced routing configuration is used.

**Comment by webpro** [comment]
Moved.
