### ISSUE TITLE
Allow explicit activation of plugins

### ISSUE THREAD

**Issue by christophflick-toast** [webpro/knip#276]
Instead of explicitly declaring dependencies like `jest` or `babel`, we're getting them as transitive dependencies from "configuration packages" that bundle different dependencies/configurations.
This leads to the corresponding knip plugins not being activated, as they rely on them being in the `package.json`.

Is there currently a way to explicitly activate plugins, or if not, could that be added?

**Comment by Dremora** [comment]
I actually have the same feature request, but for the opposite reason. Our monorepo currently has dependencies only installed at the root, which means that every workspace (we have over 100 of those) gets treated as having Next, Jest, Cypress, Storybook, etc., regardless of them actually being in use.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.31.0. See [Release 2.31.0](https://github.com/webpro/knip/releases/tag/2.31.0) for release notes._

**Comment by webpro** [comment]
Example: https://github.com/webpro/knip/blob/9c72ffbb36bc9527c45d2cfb04b2bd36bd592476/fixtures/workspaces-plugin-config/knip.json#L6-L8

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.32.0. See [Release 2.32.0](https://github.com/webpro/knip/releases/tag/2.32.0) for release notes._
