### ISSUE TITLE
import type reporting as Unused dependencies

### ISSUE THREAD

**Issue by accordionpeas** [webpro/knip#278]
Hello,

If I only import a type from a dependency e.g.

`import type { FormikProps } from 'formik'`

Then `formik` is listed as an unused dependency.

Thanks.

**Comment by accordionpeas** [comment]
Just realised it should be a dev dependency in that case!

**Comment by webpro** [comment]
Can you set up a reproduction please? It may sound like an obvious bug, but there are a few less obvious things at play here that I can't see.

**Comment by accordionpeas** [comment]
When trying to replicate this I realised that my knip config contained `"project": ["src/**/*.ts"]` - which wasn't catching `.tsx` files - apologies! Closing issue.
