### ISSUE TITLE
Unlisted dependencies with tsconfig paths and ts-jest

### ISSUE THREAD

**Issue by accordionpeas** [webpro/knip#280]
Hello,

Knip is reporting an unlisted dependency when there is a path alias in `tsconfig.json` and `pathsToModuleNameMapper` from `ts-jest` is used. 

For example if `tsconfig.json` contains this:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~types": ["src/types"]
    }
  }
}

```

And `jest.config.js` contains:

```
const { pathsToModuleNameMapper } = require('ts-jest')
const { compilerOptions } = require('./tsconfig.json')

module.exports = {
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths),
  'rootDir': './',
}
```

When I run `knip` I get

```
Unlisted dependencies (1)
src/types  jest.config.js
```

**Comment by accordionpeas** [comment]
Of course, here you go - https://github.com/accordionpeas/knip-ts-jest-demo

**Comment by accordionpeas** [comment]
I'm also seeing `@types/jest` as an unused devDependency - is that expected?

**Comment by webpro** [comment]
If you change this in `tsconfig.json`, Knip understands it's a relative path:

`"~types": ["src/types"]` → `"~types": ["./src/types"]`

It should not be necessary, since TypeScript is fine with it, but for now we'll have to work with this.

The unused `@types/jest` is expected, since `jest` has `package.json#type` i.e. it's shipped including types.

**Comment by accordionpeas** [comment]
Unfortunately `pathsToModuleNameMapper` doesn't work with relative paths. Even if I add the relative paths and a util to convert them for ts-jest e.g. 

```
const paths = Object.fromEntries(
   Object.entries(compilerOptions.paths).map(([key, value]) => ([
     key,
     value.map(path => path.replace(/^.\//, ''))
   ]))
)
```

Then the knip error still occurs.

**Comment by accordionpeas** [comment]
I guess if this can't be fixed then I'll have to ignore `jest.config.js` for now

**Comment by webpro** [comment]
- Knip loads and executes the `jest.config.js` file, so Knip works with whatever config object is being exported (i.e. the util runs before Knip receives the config).
- Maybe it's an option to (add `<rootDir>` in there and) make the paths absolute? That might work for Knip.
- If it's really just two entries, you could even hardcode `moduleNameMapper` and leave out `pathsToModuleNameMapper` entirely.

The thing is, none of the plugins do actual module resolution. I'm hoping they can stay as dumb/cheap as possible.

**Comment by accordionpeas** [comment]
Ok, thanks once again for your help
