### ISSUE TITLE
Expose line number and position of issues

### ISSUE THREAD

**Issue by webpro** [webpro/knip#288]
To be used by reporters.

(origin: https://github.com/webpro/knip/pull/287#issuecomment-1756080357)

**Comment by webpro** [comment]
@Codex- The `exports` and `types` issue types now have `row` and `col` numbers. It's in [v2.37.0](https://github.com/webpro/knip/releases/tag/2.37.0) and name of the reporter is `jsonExt` (should probably become the default `json` reporter in a next major).

I think this test shows best how to use it and what it looks like:

https://github.com/webpro/knip/blob/main/test/cli-reporter-jsonExt.test.ts

Would be eager to know what you think, and if it's useful!

**Comment by Codex-** [comment]
@webpro you're truly a legend, thank you! I just got my action posting comment reports but this week I'll look into implementing code annotations using this extended feature

I haven't tagged v1 yet but I'll let you know when I do, the rough version can be found under `knip-reporter` under my repos

**Comment by webpro** [comment]
Thanks, awesome! I'm going to close this issue, but feedback is always welcome.

Regarding line/col for the remaining issue types:

- Todo: [files](https://github.com/webpro/knip/issues/307)
- Todo: [unresolved](https://github.com/webpro/knip/issues/308)
- Most of the rest (`dependencies`/`devDependencies`/`unlisted`/`binaries`) is meant to be handled using the package manager (working on `--fix`), but still possible/nice to have.

**Comment by Codex-** [comment]
v1 of the `knip-reporter` [action](https://github.com/marketplace/actions/knip-reporter) has been released, this is just the comment reporting for now, working on the annotations side of things now :)

**Comment by Codex-** [comment]
@webpro I've noticed while testing that duplicates only return an object of type `{ name: string }` but in the reporter they're typed to return an `Item` with the line and pos 🤔

**Comment by webpro** [comment]
```ts
type Item = { name: string; pos?: number; line?: number; col?: number };
```

All of issue types `exports`, `types`, `duplicates`, `enumMembers`, `classMembers` indeed have this type, but `line` and `col` are optional. Sorry, it's simply a missing feature.

**Comment by Codex-** [comment]
Okay sounds good, thanks for clarifying!

**Comment by webpro** [comment]
The `duplicates` issue type now also has pos/line/col since v3.0.0-canary.1 (you could test/try using e.g. `npm install knip@canary`)
