### ISSUE TITLE
Import `*.js` files directly in `"type": "module"`

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#290]
This check can be extended to also allow `*.js` in ESM contexts:

https://github.com/webpro/knip/blob/cc0fbc69e2aef3570ec0e888b101e57e68239fba/src/util/loader.ts#L28-L32

Why? Hitting a couple of rough edges in Jiti:

No top-level await: https://github.com/unjs/jiti/issues/72
No `import.meta.resolve`: https://github.com/unjs/jiti/issues/101

Not high priority though, all of this is work-aroundable, just documenting it.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.41.1. See [Release 2.41.1](https://github.com/webpro/knip/releases/tag/2.41.1) for release notes._

**Comment by webpro** [comment]
Thanks Alec, good idea, `.js` modules now use native `import()`.

**Comment by alecmev** [comment]
Thank you!
