### ISSUE TITLE
Knip not working properly with bulk exports

### ISSUE THREAD

**Issue by thomasttvo** [webpro/knip#293]
The export method below leads to x, y, z being considered unused
```ts
export  { x, y, z };
```

**Comment by webpro** [comment]
This is... not a lot of information? I need something to reproduce, because just having multiple elements in a single export clause should not be a problem.

**Comment by thomasttvo** [comment]
weird, I thought this didn't work but after changing a few things and came back, it started working. Not sure what was changed but back then, I had to change them into `export const x = ....` in order for knip to ok it.
