### ISSUE TITLE
Support for `@knip-ignore` tag

### ISSUE THREAD

**Issue by thomasttvo** [webpro/knip#296]
In my project there are places where `@public` and `@beta` don't really make sense. Most of them are enums that we copy from the backend which contain values we have not yet used but good to be around for referencing purpose.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/knip/dist/ProjectPrincipal.js b/node_modules/knip/dist/ProjectPrincipal.js
index 73be2ee..a0022b5 100644
--- a/node_modules/knip/dist/ProjectPrincipal.js
+++ b/node_modules/knip/dist/ProjectPrincipal.js
@@ -178,7 +178,7 @@ export class ProjectPrincipal {
     findUnusedMembers(filePath, members) {
         return members
             .filter(member => {
-            if (getJSDocTags(member.node).has('@public'))
+            if (getJSDocTags(member.node).has('@public') || getJSDocTags(member.node).has('@knip-ignore'))
                 return false;
             const referencedSymbols = this.findReferences(filePath, member.pos);
             const files = referencedSymbols
diff --git a/node_modules/knip/dist/index.js b/node_modules/knip/dist/index.js
index b1927ad..afeb3c7 100644
--- a/node_modules/knip/dist/index.js
+++ b/node_modules/knip/dist/index.js
@@ -292,7 +292,7 @@ export const main = async (unresolvedConfiguration) => {
                     continue;
                 const importingModule = importedSymbols.get(filePath);
                 for (const [symbol, exportedItem] of exportItems.entries()) {
-                    if (exportedItem.jsDocTags.has('@public') || exportedItem.jsDocTags.has('@beta'))
+                    if (exportedItem.jsDocTags.has('@public') || exportedItem.jsDocTags.has('@beta') || exportedItem.jsDocTags.has('@knip-ignore'))
                         continue;
                     if (isIgnoreInternal && exportedItem.jsDocTags.has('@internal'))
                         continue;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by webpro** [comment]
In general, it's not a good practice to keep stuff around. Most people want to remove stuff that's not in use. Adding a tag like this is like "give an inch, take a mile", which is especially true for instance in large projects and people joining later might still not be sure of whether they can remove something or not (or they have extra work by going through all these ignore tags that might still be valid or not).

A few suggestions you could consider:

- Move the unused exports to a central file (or re-export them from there) and make that an entry file
- Make issue types like `types` or `enums` a warning by configuration (so they don't count as errors):

```json
{
  "rules": {
    "enums": "warn"
  }
}
```

**Comment by thomasttvo** [comment]
> which is especially true for instance in large projects and people joining later might still not be sure of whether they can remove something or not
I think this is a valid point. This is harder to manage at large scale. However, both suggestions run into the same issue and the first suggestion breaks the integrity of project structures. 

I think a good compromise is communication. A simple "why this needs to be around" explanation should be good enough. What do you think about requiring an explanation next to `@knip-ignore`, which can be a warning thrown when knip runs?

**Comment by webpro** [comment]
I'd like to refer to two articles I agree with:

- https://jfmengels.net/disable-comments/
- https://jfmengels.net/safe-dead-code-removal/#yagni-you-arent-gonna-need-it

So I'm open to suggestions, but I still don't fancy proprietary tags.

**Comment by webpro** [comment]
Closing this. I provided some reasoning and alternatives.
