### ISSUE TITLE
Add line numbers to reported issues (optional)

### ISSUE THREAD

**Issue by webpro** [webpro/knip#3]
In existing and/or new, more extensive reporter

**Comment by webpro** [comment]
Closing this one. Custom reporters can be implemented. Let's just wait and see what folks come up with.

**Comment by erheron** [comment]
Hello @webpro  👋🏻 
I'd be interested in implementing this. Do you think this feature has a potential to make it into the main repo, maybe as a CLI argument (e.g. `--includeLineNumbers`) or even be enabled by default in `compact` reporter?
