### ISSUE TITLE
Using knip's `$schema` may result in a warning about the `$schema` key

### ISSUE THREAD

**Issue by ericcornelissen** [webpro/knip#30]
Using the [knip schema for the config on the `next` branch](https://github.com/webpro/knip/tree/1052ec842606f63b9a26f2e25443f4b8bb9e06e7#usage), e.g.[^1]:

```json
{
  "$schema": "./node_modules/knip/schema.json",
  "entry": ["lib/index.ts!"],
  "project": ["lib/**/*.ts!"],
  "ignoreBinaries": ["actionlint"],
  "ignoreDependencies": [
    "@ericcornelissen/eslint-plugin-top",
    "eslint-v6",
    "eslint-v7",
    "eslint-v8"
  ]
}
```

results in the following warning by VSCode[^2]:

```json
[{
	"resource": ".../eslint-plugin-top/knip.json",
	"owner": "_generated_diagnostic_collection_name_#3",
	"severity": 4,
	"message": "Property $schema is not allowed.",
	"startLineNumber": 2,
	"startColumn": 3,
	"endLineNumber": 2,
	"endColumn": 12
}]
```

This seems to be the result of having the following line in the schema:

https://github.com/webpro/knip/blob/1052ec842606f63b9a26f2e25443f4b8bb9e06e7/schema.json#L43

as removing this line from the scheme makes the warning go away.

However, removing that lines makes the scheme stop complaining about all extraneous options. Hence, it might be better to add the `"$schema"` key to the schema like so:

```js
  // ...
  "properties": {
    "$schema": {
      "type": "string"
    },
    // ...
  },
  // ...
```

[^1]: Or with `"$schema": "https://unpkg.com/knip@alpha/schema.json"`.
[^2]: I don't know which schema validation library is used by VSCode under the hood, and I also couldn't quickly find a CLI to reproduce the issue...

**Comment by webpro** [comment]
Thanks Eric! I had something lined up the other day.

From [1.0.0-beta.3](https://github.com/webpro/knip/releases/tag/1.0.0-beta.3), this should fix it indeed:

```
"$schema": "https://unpkg.com/knip@next/schema.json",
```
