### ISSUE TITLE
Add pos/line/col to unresolved imports in `jsonExt` reporter

### ISSUE THREAD

**Issue by webpro** [webpro/knip#308]

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.0.0-canary.0. See [Release 3.0.0-canary.0](https://github.com/webpro/knip/releases/tag/3.0.0-canary.0) for release notes._

**Comment by Codex-** [comment]
FYI, got v2 of the action released which includes annotation support for `exports`, `types`, `duplicates`, `enumMembers` and `classMembers` 🎉 

I wanted to add `unresolved` annotation support but my local testing with knip 3.7 only returns an object with `name` and not the schema shown [here](https://github.com/webpro/knip/commit/50b8d7f3b49a045f9b643e5627626d0db71684e0#diff-90000bdc0fa8071b9cde808862307c292a6ab5ea4f35f99bda44612cc53b789fR22)

**Comment by webpro** [comment]
Awesome!

The `pos` info is not always available, but when it is, it is provided. Currently there are multiple locations in the code where unresolved imports can be found and it's not always in the context of an AST where this is available.

Feel free to open a new issue and I'll try to improve it.

The type is here: https://github.com/webpro/knip/blob/main/packages/knip/src/reporters/json.ts#L12-L28, I can expose it (like `KnipConfig`) if that helps?
