### ISSUE TITLE
absolute import css is reported as unlisted dependency

### ISSUE THREAD

**Issue by homburg** [webpro/knip#311]
Example: https://github.com/homburg/hello-knip/pull/19

I am importing a css file with an absolute import: https://github.com/homburg/hello-knip/pull/19/files#diff-aded68939b5a13b26d97ec50aea868b1027948f05b920d83f5305f6acef9f53dR2

Next resolves the absolute css import relative to `tsconfig.json`.`baseUrl` correctly.

But knip marks the import as an "unlisted dependency":
![image](https://github.com/webpro/knip/assets/235886/1e93c715-2a2d-4993-ac37-12aee48568ec)

I'd expect knip to recognize that this is an absolute path import and not an external dependency.

**Comment by webpro** [comment]
Yes, the combo of `tsonfig.json#compilerOptions.paths` for non-standard files (`.css`) is problematic for Knip. Knip does not have the toolchain Next.js has and TypeScript module resolution isn't easy to bend this way.

Solution: use relative paths.

**Comment by homburg** [comment]
That would absolutely be the pragmatic solution :-) @webpro 

Is there any way I can configure knip to ignore the css import at least?

I'm considering reproducing this issue for other bundlers as well: webpack, rollup, vite, etc? Would that make sense as separate issues?

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.38.2. See [Release 2.38.2](https://github.com/webpro/knip/releases/tag/2.38.2) for release notes._

**Comment by webpro** [comment]
I've added some kind of safeguard to ignore unresolved imports that have certain extensions.

Just in case, here's the full list: https://github.com/webpro/knip/blob/2c06dd33f0288692a1114840014a748f810563e9/src/constants.ts#L46-L66

**Comment by homburg** [comment]
Thanks! @webpro

**Comment by guipace** [comment]
@webpro I'm facing this exact issue, but with a slight variation in that my file has an extension of `.module.css`. I don't know if this is evaluated differently than `.css`.

Do you know if this could be the issue?

**Comment by webpro** [comment]
Are you on the latest version?

**Comment by guipace** [comment]
No, I wasn't. Just 3 days old and already way behind! Good job on the pace of development!
That solved the issue, thanks!

**Comment by webpro** [comment]
🫡
