### ISSUE TITLE
Storybook: `.storybook/preview.ts` is detected as unused

### ISSUE THREAD

**Issue by IanVS** [webpro/knip#313]
Sorry, but here's another Storybook issue I didn't notice before.  It seems that `.storybook/preview.ts` is detected as unused.  I checked other extensions like `.js` and `.tsx` and those were detected as unused as well.  From looking briefly at the code for the Storybook plugin, I'm confused why this would be, since you default to adding those files as entries.  

Reproduction is the same as last time: https://stackblitz.com/edit/github-z465pp?file=package.json

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.38.2. See [Release 2.38.2](https://github.com/webpro/knip/releases/tag/2.38.2) for release notes._

**Comment by webpro** [comment]
I've inter-twisted some logic here, should be fixed now :)

**Comment by IanVS** [comment]
Works, thanks!
