### ISSUE TITLE
Document the reason for needing NODE_ENV

### ISSUE THREAD

**Issue by gajus** [webpro/knip#316]
Started to see error:

> Reason: Have to set explicit NODE_ENV

But it does not explain anywhere why/what are the implications.

**Comment by webpro** [comment]
This error is not coming from Knip (there's no `NODE_ENV` in the program at all).

Knip loads and executes configuration files such as `webpack.config.js` and `vite.config.ts`, so my guess this is raised through one of the plugins.

Knip may help by setting that variable if the tool demands it.

**Comment by gajus** [comment]
> Knip loads and executes configuration files such as webpack.config.js and vite.config.ts, so my guess this is raised through one of the plugins.

That's indeed what's happening here!

I was thrown off because it started happening after attempting to update Knip, so I suppose Knip started loading these files whereas before it didn't.

I don't think Knip should do anything about. Maybe say which file threw an error if error was thrown.

**Comment by webpro** [comment]
> I was thrown off because it started happening after attempting to update Knip, so I suppose Knip started loading these files whereas before it didn't.

A few new plugins have been introduced recently. It could also be caused by extending existing globs for config files (such as `postcss.config.cjs`).
