### ISSUE TITLE
Scripts interpreter (getDependenciesFromScripts) interprets urls as dependencies

### ISSUE THREAD

**Issue by beaussan** [webpro/knip#318]
Currently, scripts that contains urls are interpreted as `http:` unlisted dependancies, but it shouldn't be.

Repro here :https://stackblitz.com/edit/stackblitz-starters-qj4jkx?file=package.json

Simplest package json for repro :

```json
{
  "scripts": {
    "generate": "npx swagger-typescript-api -p http://localhost:3030/swagger.v1.json -o ./some-folder/generated --axios --single-http-client --name TestApi.ts --type-prefix Test",
  },
  "devDependencies": {
    "knip": "^2.38.1"
  }
}
```

Output :
```
Unlisted dependencies (1)
http:  package.json
Unlisted binaries (1)
swagger-typescript-api  package.json
```

Expected output :
```
Unlisted binaries (1)
swagger-typescript-api  package.json
```

I may have some time next week to look into it

**Comment by webpro** [comment]
This is slightly confusing, as `npx` also has a `--package` (or `-p`) argument. Technically, one could argue that you should use the separator:

```
npx swagger-typescript-api -- -p http://localhost:3030/swagger.v1.json
```

This is also in the `npx` docs:

> The double-hyphen character is recommended to explicitly tell npm to stop parsing command line options and switches.


Still, url's are invalid dependencies (except for e.g. Deno), so that's something Knip can take into account here too.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.38.2. See [Release 2.38.2](https://github.com/webpro/knip/releases/tag/2.38.2) for release notes._

**Comment by beaussan** [comment]
Thanks a lot @webpro ! You are awesome ❤️

**Comment by webpro** [comment]
Thanks Nicolas, keep 'em coming :)
