### ISSUE TITLE
Eslint extends in a monorepo context is reporting false positive on Unresolved imports

### ISSUE THREAD

**Issue by beaussan** [webpro/knip#319]
Currently, knip eslint plugin report false positive for Unresolved imports in a monorepo context, using two eslintrc files with a extends.

I was not able to make a failing test but I have isolated in a reproduction here : https://github.com/beaussan/repro-eslint-knip-monorepo

I will continue to try making a failing test in the meantime

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.38.5. See [Release 2.38.5](https://github.com/webpro/knip/releases/tag/2.38.5) for release notes._

**Comment by webpro** [comment]
Thanks for the clear report, Nicolas! I've done some refactorings and overall things are handled a bit better now.
