### ISSUE TITLE
Monorepo config (without package manager workspaces)

### ISSUE THREAD

**Issue by webpro** [webpro/knip#326]
Thanks webpro. To continue the discussion, I tried to run `knip` from the root of my monorepo, but I am running into some problems.

- I have a monorepo package that is an npm library. It exports helper functions from the "./src/index.ts" file, exactly like you would expect.
- Besides being exported from the "index.ts" file, these functions are otherwise unused. But obviously this is intentional because it is an npm library that other people are expected to consume.
- When running `knip` from the subpackage directory, it seems to work fine with no errors. 
- When running `knip` from the monorepo directory, it complains that all of the exports are unused.

I figured that maybe I need to explicitly tell knip about the entry point, so I tried this config, based on what you said in your previous comment:

```json
{
  "$schema": "https://unpkg.com/knip@2/schema.json",
  "workspaces": {
    "packages/foo": {
      "entry": ["./packages/foo/src/index.ts"]
    }
  }
}
```

But that didn't work. Furthermore, I changed "./packages/foo/src/index.ts" to "BOGUS_VALUE", and knip didn't even throw any errors. Is that intended? Shouldn't knip be throwing runtime errors if I put in bogus values for the purposes of failing-fast on typos? Regardless, I'm not quite sure how to make this work, any guidance would be appreciated.

For context, [this is the repo I am trying it on](https://github.com/IsaacScript/isaacscript).

_Originally posted by @Zamiell in https://github.com/webpro/knip/issues/315#issuecomment-1789407107_

**Comment by webpro** [comment]
@Zamiell, I've looked into the repo and fiddled a bit. You could try this if you like:

- Remove all `knip.json` config files across the repo
- Use this `knip.json` for starters in the root:

```json
{
  "$schema": "https://unpkg.com/knip@2/schema.json",
  "ignoreWorkspaces": ["packages/isaacscript-lua"],
  "workspaces": {
    "packages/docs": {},
    "packages/eslint-config-isaacscript": {},
    "packages/eslint-plugin-isaacscript": {
      "entry": ["src/index.ts", "tools/createRule.ts", "tools/generate.ts"]
    },
    "packages/isaac-typescript-definitions": {},
    "packages/isaac-lua-polyfill": {},
    "packages/isaacscript-cli": {
      "entry": [
        "src/main.ts",
        "src/commands/monitor/modDirectorySyncer/modDirectorySyncer.ts",
        "src/commands/monitor/saveDatWriter/saveDatWriter.ts"
      ],
      "ignore": ["file-templates/**"]
    },
    "packages/isaacscript-common": {
      "ignore": ["src/classes/features/other/extraConsoleCommands/commands.ts"]
    },
    "packages/isaacscript-common-ts": {}
  }
}
```

- Upgrade to v2.38.6 which contains a fix for the crazy remark function output
- Run using `knip --exclude classMembers` for some "bearable" output.

You'll need to tweak the config further, but this is the idea. The downside of not using the package manager workspace is that really each and every workspace should be added to this config, otherwise Knip consider it part of the root workspace (`"."`) and then it goes haywire.

Let me know whether this is sufficient to get you back on track, otherwise I can open a PR.

**Comment by webpro** [comment]
> But that didn't work. Furthermore, I changed "./packages/foo/src/index.ts" to "BOGUS_VALUE", and knip didn't even throw any errors. Is that intended? Shouldn't knip be throwing runtime errors if I put in bogus values for the purposes of failing-fast on typos?

The `entry` config options are globs (w/ wildcard patterns), so Knip (or actually globby, the dependency used for this) tries to find matching files, which could just be zero. But yeah, finding zero matching maybe should result in a warning or something (maybe an addition to the `Configuration issues` that already exists).

**Comment by Zamiell** [comment]
> finding zero matching maybe should result in a warning or something

Absolutely! This would be a great addition, thank you.

> Let me know whether this is sufficient to get you back on track, otherwise I can open a PR.

Thank you so much for taking a look! I'm going through and cleaning things up bit by bit, and your config was enough to get me started!

I think I've found a bug in the current version of Knip though (v2.38.6).
Steps to reproduce:

```
git clone git@github.com:IsaacScript/isaacscript.git
cd isaacscript
git checkout 2336a5bbfd1317bdef187b78b00c3e09078441f4
yarn install
npx knip
```

It will generate a lot of noise, but right now I'm focused on the very end, the final lines of the output:

```
Unused exported class members (5)
customTargetModDirectoryName         Config  packages/isaacscript-cli/src/classes/Config.ts
enableIsaacScriptWatcherAutoRestart  Config  packages/isaacscript-cli/src/classes/Config.ts
isaacScriptCommonDev                 Config  packages/isaacscript-cli/src/classes/Config.ts
modsDirectory                        Config  packages/isaacscript-cli/src/classes/Config.ts
saveSlot                             Config  packages/isaacscript-cli/src/classes/Config.ts
```

I think this is a bug, because these fields do appear to be being used. For example, let's consider the first one, "customTargetModDirectoryName". If we search for that string in VSCode, we see that it is being used in the `getModTargetDirectoryName` function in the `utils.ts` file. And if we look where that function is being used, we can very quickly work our way back to the "main.ts" file, which is explicitly listed in the "entry" field in the "knip.json" file.

**Comment by webpro** [comment]
Good to hear! Please open one issue per problem after configuring Knip with the root `knip.json`.
