### ISSUE TITLE
`@astrojs/check` is reported as unused dependency

### ISSUE THREAD

**Issue by risu729** [webpro/knip#329]
[`@astrojs/check`](https://www.npmjs.com/package/@astrojs/check?activeTab=readme), the library for [`astro check`](https://docs.astro.build/en/reference/cli-reference/#astro-check) command, is reported as unused dependency.

I would be happy to create a PR for this.
However, I would like to ask whether it is acceptable to add it without any conditions. Some users might add it and not use it, and they will not be able to realize that if it is ignored in the default of the Vitest plugin.

**Comment by webpro** [comment]
A pull request sounds be great!

Sounds like we need to make sure that only if `astro check` is in a script in `package.json` the `@astro/check` package is required. Otherwise it's unused and should be reported as an unused dependency. Something like this?

**Comment by risu729** [comment]
Thanks for your advice! I made a PR now.
