### ISSUE TITLE
Show a warning when a path in the "knip.json" file does not match any results

### ISSUE THREAD

**Issue by Zamiell** [webpro/knip#331]
For example, if the entry point was `foo.ts`, and the user typoed it to be `fooo.ts`, then Knip should immediately show a warning. Failing fast is important, as it potentially save the end-user a bunch of troubleshooting time.

**Comment by webpro** [comment]
The entry file options are patterns/globs, might contain wildcards, and try to find matching items on the file system. They're not meant to throw exceptions, just an array of matching files on disc.

What Knip could do however, is print a warning if there are exactly zero matches.

**Comment by Zamiell** [comment]
> What Knip could do however, is print a warning if there are exactly zero matches.

Sure!

**Comment by webpro** [comment]
Closing this, as there are too many factors at play to reliably implement this.

Thinking about a `knip init` or something to help with this, though.
