### ISSUE TITLE
Knip says dependencies are unused when they are actually used

### ISSUE THREAD

**Issue by Zamiell** [webpro/knip#345]
This is on knip version 2.40.1.

Steps to reproduce:

```
git clone git@github.com:IsaacScript/isaacscript.git
cd isaacscript
git checkout aa5b9e68ca3ec147d0b87ec83da8bd8a536dcf61
yarn
npx knip
```

The first lines of the output are:

```
Unused dependencies (53)
@algolia/client-search                package.json
@arktype/fs                           package.json
```

Many dependencies are reported as unused, but let's just start with the second one, "@arktype/fs".
If we grep the repository for this, we can see that it is being used in the monorepo package called "isaacscript-common-node" in a file called "arkType.ts". All of the functions in "arkType.ts" are being exported from the entry point, "index.ts". And there is an entry for "isaacscript-common-node" in the workspaces object inside the knip.json file.

Thus, I conclude that Knip seems be to confused about how monorepo dependencies work.

**Comment by webpro** [comment]
This is expected behavior: `@arktype/fs` is used and listed in `packages/isaacscript-common-node` so it's unused in the root `package.json`.

**Comment by Zamiell** [comment]
Well, it is actually used in the root package.json, because I am using the Google-style of monorepos where all dependencies are installed at the root. (This is what Google does internally in their monorepos.) I've become increasing convinced that this is one of the best ways to organize monorepos, and [I've written more about this over at the Turborepo forums](https://github.com/vercel/turbo/issues/2060#issuecomment-1416135197).

In other words, I am not using the "workspaces" feature of the package manager whatsoever, so even though "@arktype/fs" is listed in "packages/isaacscript-common-node/package.json", there is no corresponding "node_modules" folder at all. This is perhaps something knip could in principle detect automatically. But if not, then I need some way to tell Knip that I am NOT using workspaces and that I am using a Google-style monorepo, so that these spurious error messages can be supressed. Is there a way to do that?

**Comment by Zamiell** [comment]
Thinking on this more, Knip can know I am not using workspaces because there isn't any workspaces defined in the root package.json file, right?

**Comment by webpro** [comment]
Alternatively, you can remove `@arktype/fs` from `packages/isaacscript-common-node/package.json`. If you decide to list packages in both locations, but use it in only one, then that's on you. Let's leave it that :)

**Comment by Zamiell** [comment]
> Alternatively, you can remove @arktype/fs from packages/isaacscript-common-node/package.json. If you decide to list packages in both locations, but use it in only one, then that's on you. Let's leave it at that :)

webpro, that isn't possible. To be clear, `isaacscript-common-node` is an npm library that is published to npm. The dependency must be in the "packages/isaacscript-common-node/package.json" file, or else when end-users `npm install` the library, the corresponding arktype dependency will not be downloaded by the package manager, and then there will be a runtime error. And I can't remove it from the root, because in Google style monorepos, all dependencies must live at the root, for previously discussed reasons (see my blog). Does that make sense?

**Comment by Zamiell** [comment]
Bump - I feel like Knip should be able to handle this style of monorepo. Is the problem that you don't think that this style of monorepo is idiomatic enough in the TypeScript ecosystem to bother supporting in Knip?

My blog over at the Turborepo forums has 14 upvotes, and furthermore, this is how Google structures its monorepos internally, so hopefully that goes towards showing that it should be a candidate for support.
 
Having at least some optional setting that would suppress these spurious warnings or otherwise work around the problem would be greatly appreciated.

**Comment by webpro** [comment]
> Many dependencies are reported as unused, but let's just start with [..]

> Thus, I conclude that Knip seems be to confused about how monorepo dependencies work.

> spurious error messages

> webpro, that isn't possible

I just don't think your approach aligns very well with what Knip tries to do and the way you come across makes that I currently don't want to spend my energy here.

You can use `--exclude dependencies` to get rid of your "false positives".
