### ISSUE TITLE
Should support `.yaml` as a valid extension.

### ISSUE THREAD

**Issue by gajus** [webpro/knip#348]
https://github.com/webpro/knip/blob/d79728b1d21f98c6a1da932717115b9426ad1524/src/plugins/graphql-codegen/index.ts#L18

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.41.3. See [Release 2.41.3](https://github.com/webpro/knip/releases/tag/2.41.3) for release notes._

**Comment by webpro** [comment]
Thanks! Looked at their source code and added even more config file patterns: https://github.com/webpro/knip/tree/main/src/plugins/graphql-codegen

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.0.0-canary.4. See [Release 3.0.0-canary.4](https://github.com/webpro/knip/releases/tag/3.0.0-canary.4) for release notes._
