### ISSUE TITLE
The CJS build of Vite's Node API is deprecated

### ISSUE THREAD

**Issue by EvgenyOrekhov** [webpro/knip#350]
Started getting this error every time I run knip:

> The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-dep

I use:

- knip 2.41.3
- Vitest 0.34.6
- Node.js 18.18.2

**Comment by webpro** [comment]
Is it just a warning, or an error? How can I reproduce it?

**Comment by EvgenyOrekhov** [comment]
Steps to reproduce:

```sh
mkdir knip-vitest
cd knip-vitest
npm i -D vitest knip
```

Then create file `vitest.config.ts`

```
/// <reference types="vitest" />
import { defineConfig } from 'vitest/config';
export default defineConfig({});
```

Then run `npx knip > result.txt`, and you should see the warning.

<img width="1161" alt="image" src="https://github.com/webpro/knip/assets/8045060/38f10e64-9ce2-4825-9861-f3f037f16a31">

Note: you have to run `npx knip > result.txt`, and not just `npx knip` to see the warning, because `npx knip` clears the current output line.

**Comment by webpro** [comment]
Thanks, gotcha.

The first thing that caught my eye is that you probably want to set `"type": "module"` in `package.json`, to nudge Node.js and other module resolvers in the right direction.

However, that won't be sufficient today, I think there's an issue in jiti. Knip uses jiti under the hood to load such config files. Hacked around a bit and didn't get it to work (not even when using the `.mts` extension), maybe fixed when they make the switch to ESM being the native import/loading mechanism in [jiti v2](https://github.com/unjs/jiti/issues/174).

To get rid of the warning today, you could switch to use the `.mjs` extension.

> Note: you have to run `npx knip > result.txt`, and not just `npx knip` to see the warning, because `npx knip` clears the current output line.

Knip should not clear or overwrite that output (e.g. it does not do that on my macOS with Bash). Can I ask which shell you are using?

You can use `--no-progress` or `-n` so Knip won't rewrite lines or clear `stdout`.

**Comment by EvgenyOrekhov** [comment]
> Knip should not clear or overwrite that output (e.g. it does not do that on my macOS with Bash). Can I ask which shell you are using?

I use zsh on my macOS. I can see the warning gets shown for a split second. With `--no-progress` it stays on the screen.
BTW I believe the warning goes to `stderr`, not `stdout`.

**Comment by webpro** [comment]
@yekver Those are two different things. The real issue here is about CJS vs ESM (with `"type": "module"`).

The other thing is only about how Knip logs things to `stdout` (and `stderr`), and there seems to be a difference between Bash and Zsh. That's why we discuss the `--no-progress` flag.

**Comment by JoshuaKGoldberg** [comment]
FWIW I see the CJS notice in https://github.com/JoshuaKGoldberg/create-typescript-app/pull/1082.

**Comment by webpro** [comment]
Yeah, it's coming from jiti, waiting for them to go fully ESM :)

**Comment by webpro** [comment]
See https://github.com/webpro/knip/issues/565
