### ISSUE TITLE
named exports with default import

### ISSUE THREAD

**Issue by JeisonJHA** [webpro/knip#353]
This is a simplified version of the problem I'm currently facing.
The original project experiencing this issue is written in TypeScript. To make it easier to identify the problem, I've created a minimal configuration to reproduce it.

``` js
//exporter.js
const cb = async (data) => {
    console.log(data)
}

module.exports = { cb } 
```

``` js
//index.js
const exporter = require('./exporter')
exporter.cb()
```
``` sh
Unused exports (1)
cb  src/exporter.js
 ELIFECYCLE  Command failed with exit code 1.
```

![image](https://github.com/webpro/knip/assets/15232721/0135581b-9cce-4118-9b78-cc9fc6fc663d)

**Comment by webpro** [comment]
What's the original code? TypeScript does not use CJS syntax. I'm asking, because different syntax follows different code paths in Knip.

**Comment by JeisonJHA** [comment]
hi, here is an example:

``` js
//index.ts
import { exporter } from './exporter';

exporter.cb('test')
```

``` js
//exporter/exporter.ts
const cb = async (data: string) => {
    console.log(data)
}

export { cb }
```

``` js
//exporter/index.ts
import * as exporter from './exporter'

export {
    exporter
}
```

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.43.0. See [Release 2.43.0](https://github.com/webpro/knip/releases/tag/2.43.0) for release notes._

**Comment by webpro** [comment]
Thanks @JeisonJHA, guess this combo isn't super common, but should be good now :)

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.0.0-canary.4. See [Release 3.0.0-canary.4](https://github.com/webpro/knip/releases/tag/3.0.0-canary.4) for release notes._

**Comment by JeisonJHA** [comment]
Thanks, @webpro! I was testing it here, and it worked perfectly with an arrow function. However, with the function itself, it doesn't work. Would you like me to open a new issue for this?

**Comment by webpro** [comment]
Perhaps you could just show an minimal example here?

**Comment by JeisonJHA** [comment]
sure!
here it goes:
```js
//index.ts
import { exporter } from './exporter';
exporter.cb('test')
```

```js
//exporter/exporter.ts
async function cb(data: string) {
    console.log(data)
}

export { cb }
```

```js
//exporter/index.ts
import * as exporter from './exporter'
export {
    exporter
}
```

**Comment by webpro** [comment]
Dang, this one wasn't easy, but also inspired/forced to do a nice refactoring that'll be useful in the future (to auto-fix issues and remove unused exports).
