### ISSUE TITLE
.css.ts files are not recognised anymore

### ISSUE THREAD

**Issue by Dremora** [webpro/knip#354]
Since version 2.38.5 (and present in the current latest stable), Knip doesn't seem to follow `.css.ts` files, and reports such files as being unused.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.41.4. See [Release 2.41.4](https://github.com/webpro/knip/releases/tag/2.41.4) for release notes._

**Comment by webpro** [comment]
Thanks for the report, @Dremora! Not sure how this got through, but added coverage and fixtures to prevent regressions.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.0.0-canary.4. See [Release 3.0.0-canary.4](https://github.com/webpro/knip/releases/tag/3.0.0-canary.4) for release notes._
