### ISSUE TITLE
Reflect.metadata is not a function

### ISSUE THREAD

**Issue by splincode** [webpro/knip#355]
Clone: https://github.com/taiga-family/taiga-ui

```
$ npx knip
Reason: Reflect.metadata is not a function
projects/demo/webpack.config.ts
```

**Comment by webpro** [comment]
This is a downstream issue. Issues/PRs to track:

- https://github.com/unjs/jiti/issues/145
- https://github.com/unjs/jiti/pull/165
- https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/pull/70

**Comment by webpro** [comment]
See https://github.com/webpro/knip/issues/565
