### ISSUE TITLE
[feature] check dependency version consistency

### ISSUE THREAD

**Issue by cbbfcd** [webpro/knip#356]
It's a great tool, and if it's possible, I'm wondering if it's possible to add a feature that lists the different versions of the same dependency for sub-projects in a monorepo project, which is very common, but also a big problem that often leads to us packaging in multiple different versions of the same repository!

may be just like this:
```js
knip --dependencies


// output
// ...
// version check message
// lodash@4.17.21 in package foo
// lodash@4.15.20 in pacakge zoo
// ...
```

**Comment by webpro** [comment]
That's outside the scope of Knip. But there are tools that do this:

- [syncpack](https://jamiemason.github.io/syncpack/)
- [manypkg](https://github.com/Thinkmill/manypkg)

**Comment by cbbfcd** [comment]
thx reply ~
