### ISSUE TITLE
Infinite recursion with file and directory sharing name (?)

### ISSUE THREAD

**Issue by Jym77** [webpro/knip#359]
OK, so I run in an infinite recursion problem (or at least too many recursion) while running knip. Not sure excatly what is the problem and how to investigate it, and wasn't able to make a MNWE 😖 

* [Github action run that fails](https://github.com/Siteimprove/alfa/actions/runs/6946062877/job/18896755002?pr=1508) with a "RangeError: Maximum call stack size exceeded" error.
* [PR where it run](https://github.com/Siteimprove/alfa/pull/1508).
* [The culprit commit](https://github.com/Siteimprove/alfa/pull/1508/commits/390a15b6551e8374a345cd46669b796c9b314aa9) (after bisecting).

I do suspect that there might be a problem with both `src/selector.ts` and `src/selector/index.ts` existing, which means that when `src/selector/compound.ts` tries to `import { Absolute } from "./selector"`, it may mess up which file to use 🤔 
The other possible culprit is that the types are effectively mutually recursive. That is essentially an algebraic list-like type, but split over several files and with some shenanigans. Maybe that is throwing knip out…

Anyway, any idea on how I could investigate further and figure out whether the problem is in my code or in knip?

**Comment by Jym77** [comment]
> I do suspect that there might be a problem with both `src/selector.ts` and `src/selector/index.ts` existing, which means that when `src/selector/compound.ts` tries to `import { Absolute } from "./selector"`, it may mess up which file to use 🤔

I'm further convinced that this is the reason. I've removed that double naming and knip succeed:
* [Github action where knip works fine](https://github.com/Siteimprove/alfa/actions/runs/6957290780/job/18929895229?pr=1508)
* [The commit that makes it work](https://github.com/Siteimprove/alfa/pull/1508/commits/929a3086e746715a465f55b29ac593750eca2f70).

**Comment by webpro** [comment]
Any chance you could setup a minimal case so I can reproduce it?

I've added two templates to the docs: http://localhost:4321/guides/troubleshooting/#minimal-reproduction

**Comment by Jym77** [comment]
> I've added two templates to the docs: http://localhost:4321/guides/troubleshooting/#minimal-reproduction

URL is pointing to `localhost` 🙈

**Comment by Jym77** [comment]
That one feels too brittle for a MNWE 😖 
I tried extracting the directory who breaks, it broke. But then making a small change and undoing it un-broke it 🤔 
I'll just close this issue and keep a mental note in case I witness it again…
