### ISSUE TITLE
Latest TypeScript + Knip is reporting a dependency as unused

### ISSUE THREAD

**Issue by gajus** [webpro/knip#362]
I am not sure what's the best way to repro these issues since it seems to be affected by many other files in our project.

But here is a walkthrough showing the undesired behavior https://www.loom.com/share/8883a3d97f904e8dbdf96542aca072e9

Subject package https://npmjs.com/package/http-terminator

I can provide more debugging info as requested.

**Comment by webpro** [comment]
What I would look for first:

- Is there a `package.json` in the `./server` folder? Probably not, just in case.
- Analyze the `--debug` output and check the glob options and matching files.

**Comment by webpro** [comment]
Now I see `typescript@5.3.0` breaks some tests of Knip, I'll look into it.

**Comment by webpro** [comment]
Confirmed `typecript@5.3.2` breaks Knip - add compat in knip [v2.42.0](https://github.com/webpro/knip/releases/tag/2.42.0).

Related: https://github.com/microsoft/TypeScript/pull/55818
