### ISSUE TITLE
lazy import and select module is not supported

### ISSUE THREAD

**Issue by hyoban** [webpro/knip#375]
https://stackblitz.com/edit/knip-case-repro-uwhnkm?file=index.ts

```ts
async function main() {
  const lazy = await import('./lazy').then((module) => ({
    default: module.lazyLoad,
  }));
  lazy.default();
}

main();
```

**Comment by webpro** [comment]
This should fix it, but I'm not sure yet what I will do from Knip side yet. Make sure this is in `tsconfig.json`:

```json
{
  "compilerOptions": {
    "types": ["node"]
  }
}
```

You may need to `npm install -D @types/node`

**Comment by hyoban** [comment]
Thanks, it works

**Comment by webpro** [comment]
Thanks for the repro in StackBlitz, that was super helpful!
