### ISSUE TITLE
Regression in v3.3.5 - The system cannot find the path specified.

### ISSUE THREAD

**Issue by Zamiell** [webpro/knip#377]
Steps to reproduce:

```
git clone git@github.com:IsaacScript/isaacscript.git
cd isaacscript
git checkout de7eb6af04b57afc3236e4132e593956ca52fe45
yarn install
npx knip --exclude dependencies
```

After doing this, you should notice that the output is:

```
The system cannot find the path specified.
The system cannot find the path specified.
```

- Next, update the "package.json" file and change `"knip": "^3.3.5",` to `"knip": "3.3.4",`
- Then, run: `yarn install`
- Then, run `npx knip --exclude dependencies`

Notice that the error messages do not appear. Thus, this is a regression in v3.3.5.

**Comment by webpro** [comment]
No I don't see that error, can't reproduce. The messages do not appear.

**Comment by Zamiell** [comment]
I'm using Windows 10. Maybe this is an OS-specific regression?
I tested in both Windows Command Prompt and Git Bash, and the error appears in both of them.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.4.0. See [Release 3.4.0](https://github.com/webpro/knip/releases/tag/3.4.0) for release notes._

**Comment by webpro** [comment]
Looking at the commits that went into v3.3.5 I think I found the issue and it should be fixed now. Thanks for the report and bearing with me :)

**Comment by Zamiell** [comment]
No problem, appreciate the quick fix!
