### ISSUE TITLE
Add a way to suppress errors from a subset of files

### ISSUE THREAD

**Issue by gajus** [webpro/knip#380]
So obviously there is [`ignore`](https://knip.dev/reference/configuration/#ignore).

But the problem is that _ignore_ excludes the file from all reporting their dependencies.

For instance, we don't want to report any errors from generated files, so we do this:

```json
"ignore": [
  "**/__generated__/**/*"
],
```

but some of these generated files have their own dependencies that are only used by them, so now those dependencies are reported as unused.

I suggest that the current `ignore` should be renamed to `exclude` and a new `ignore` (or `ignoreErrors`) should be added.

**Comment by webpro** [comment]
I've made some changes and implemented this in v4 (released in `canary`) so it works more as you would expect: https://knip.dev/v4/reference/configuration#ignore

**Comment by gajus** [comment]
Amazing! Thank you

**Comment by gajus** [comment]
```ts
# app/components/ui/tabs.tsx
app/components/ui/tabs.tsx
5:import * as TabsPrimitive from '@radix-ui/react-tabs';
```

* `app/components/ui/tabs.tsx` is added to `ignore` in v4.
* `app/components/ui/tabs.tsx` is not imported in the rest of the application.

This will result in an error:

```
Unused dependencies (5)
@radix-ui/react-tabs          package.json
```

**Comment by webpro** [comment]
From this information I gather if `tabs.tsx` is not imported then it makes sense Knip thinks `@radix-ui/react-tabs` is unused?

The unused dependency is an issue in `package.json` (not `tabs.tsx`).

You can use `ignoreDependencies: ['@radix-ui/react-tabs']` to ignore the unused dependency.

**Comment by gajus** [comment]
That makes sense... I suppose I was going to say that because `app/components/ui/tabs.tsx` is ignored, I would mark its dependencies as used. But fair enough, I can see why this might not be desirable as well.

**Comment by webpro** [comment]
Yeah, I understand that too, could be looked at from both angles. It's an interesting expectation/idea, would mean another RFC. Maybe later on :)
