### ISSUE TITLE
Does a configuration exist within knip, akin to resolve.extensions in webpack, that could potentially be utilized?

### ISSUE THREAD

**Issue by CodeofSu** [webpro/knip#386]
When I use knip in vue project, it's imperative to inscribe the comprehensive directory, analogous to 'xx/xx/xx.vue', to ensure the file's detectability. 

Does a configuration exist within knip, akin to [resolve.extensions](https://webpack.js.org/configuration/resolve/#resolveextensions) in webpack, that could potentially be utilized?

**Comment by webpro** [comment]
Not 100% sure what you mean, but did you see https://knip.dev/features/compilers/? This explains how you can include `.vue` files in the analysis.

**Comment by CodeofSu** [comment]
Sorry. the example below is working as expected
```js
import ComponentA from './ComponentA.vue'
```
when remove '.vue' in code, ComponentA will report as Unused files
```js
import ComponentA from './ComponentA'
```
I consider knip can add feature like [resolve.extensions](https://webpack.js.org/configuration/resolve/#resolveextensions) to detect file in order,otherwish many project need much work to use knip.

**Comment by webpro** [comment]
In theory I think this would be possible, but I don't plan to support this. It introduces complexity and it's not good for performance.

I recommend to be explicit and use extensions. This is better for performance and module resolution. CommonJS did not, but ESM also requires extensions.

The framework Vue itself also shows the `.vue` extenions in their docs and examples, right? So let's follow best practices.
