### ISSUE TITLE
Support tsconfig aliases outside of package

### ISSUE THREAD

**Issue by Sheraff** [webpro/knip#388]
Reproduction: https://stackblitz.com/github/Sheraff/root
- remove the `"shared/**/*"` entry from the `"ignore"` list in `knip.json`
- `pnpm deps`

--- 

So I have a little bit of an uncommon setup, but (I think) it's fun because it makes imports across packages of a monorepo a little easier to work with.

Here's the directory
```
root
├── client
│   ├── main.tsx
│   ├── src
│   │   └── coucou
│   │       └── foo.ts
│   ├── package.json
│   └── tsconfig.json
├── shared
│   ├── bar.ts
│   ├── toto
│   │   └── baz.ts
│   ├── package.json
│   └── tsconfig.json
├── knip.json
├── package.json
└── tsconfig.json
```

For this example, say files in `/shared` are pretty much all simple exports
```ts
// shared/bar.ts
export function bar() {
  console.log('bar')
}
```

And to use them from `/client`, I've setup its `compilerOptions.paths` to reach outside of `/client` (see full tsconfig below) and it works like this:
```ts
// client/main.tsx
import { bar } from "@shared/bar"
bar()
```

And the issue is that those imports are not counted as used:
```shell
Unused files (5)
shared/env/publicConfig.ts
shared/env/schema.ts
shared/foo/bar.ts
shared/hello/world.ts
shared/sql.ts
```

So because I saw other issues in here, I tried a couple things:
- using `#` instead of `@` => same result
- I tried setting up another alias `@coucou` that doesn't reach outside of `/client` (see config below) => this works as expected

The repo works fine for the other tools that are in it:
- typescript
- esbuild
- vite
- turbo

```jsonc
// client/tsconfig.json
{
	"extends": "../tsconfig.json",
	"compilerOptions": {
		"jsx": "react-jsx",
		"lib": ["dom", "dom.iterable", "esnext"],
		"rootDir": "..",
		"baseUrl": ".",
		"paths": {
			"~/*": ["./src/*"],
			"@shared/*": ["../shared/*"],
			"@coucou/*": ["./src/coucou/*"]
		}
	},
	"include": [
		"src/**/*",
		"types/*.d.ts",
		"../types/*.d.ts",
		"main.tsx",
		"../shared/*",
		"../shared/**/*"
	],
	"exclude": ["node_modules"],
	"references": [{ "path": "../shared" }]
}
```

The repo is available here: https://github.com/Sheraff/root. It's very small (I'm making myself a "starter" so there isn't much code in it, it's basically 100% setup and config).

---

> Just in case I'm completely outside of the norm with this: the goal is basically to have a `/shared` package that exports a bunch of utility functions
> - without a barrel file at the root
> - without having to declare many `exports` in the package.json
> - with a nice import syntax
> 
> I wouldn't be surprised if there was a better way to do this, and if so I'd love to hear it!

**Comment by webpro** [comment]
Yeah that confuses Knip. Workspaces are supposed to be more isolated in this sense. So my first question would be, why aren't they?

I would think it's more idiomatic to either have a single `package.json` and then use `compilerOptions.paths` OR use workspaces without `paths` to cross-link them.

In your situation, I wonder what happens if you publish e.g. `client` - does it contain the necessary files at the right location from `shared`?

**Comment by Sheraff** [comment]
> Yeah that confuses Knip. Workspaces are supposed to be more isolated in this sense. So my first question would be, why aren't they?

This is the million dollar question here: what I wanted was to be able to 
- do "deep imports" from `/shared`, like for example in `/client` do something like `import { foo } from 'shared/bar/foo'`
- not have a barrel file that exports everything at the root of `/shared`
- not have to declare an `exports` in `/shared/package.json` every time I add a new function in `/shared`

And I didn't find any other way that this to do it. But I'd love to know of a good way to do this!

> I would think it's more idiomatic to either have a single `package.json` and then use `compilerOptions.paths` OR use workspaces without `paths` to cross-link them.

This is what I had done initially (1 `package.json` + `compilerOptions.paths`) but for turborepo to work it needs to have 1 package.json per "workspace"...

> In your situation, I wonder what happens if you publish e.g. `client` - does it contain the necessary files at the right location from `shared`?

Your intuition was correct, a `pnpm publish --dry-run` inside `/client` only lists files from `/client` (and then the package.json to get the rest) so as it is, this cannot be published individually. In practice it doesn't matter for this specific use-case as this is a monorepo aimed at making a client-side SPA so everything gets bundled correctly at build-time and 1 package doesn't make sense without the others... But I get your point.

**Comment by webpro** [comment]
I think you can use wildcards in export maps in `package.json`?

**Comment by Sheraff** [comment]
> I think you can use wildcards in export maps in `package.json`?

Indeed, that seems to work well, I think I can find something to work with there. Though I did find something that knip might want to support: pnpm allows aliasing of packages with a syntax like `"foo": "workspace:../bar"`. This could be a way to support `@shared` instead of `shared` in a way that isn't based on inferences (with `"@shared": "workspace:../shared"`)

**Comment by webpro** [comment]
The `workspace:` protocol is for package managers to find packages, and npm may not support this well/yet (Knip uses `@npmcli/map-workspaces` under the hood), so you do have a point here.

Not going to expand in this now though. Also since Knip has a generic `paths` feature to help mitigate issues like this: https://knip.dev/reference/configuration/#paths

Thanks for the input!
