### ISSUE TITLE
Cannot find package 'typescript'

### ISSUE THREAD

**Issue by splincode** [webpro/knip#389]
```
$ git clone https://github.com/taiga-family/taiga-ui.git
$ cd taiga-ui
$ npm ci 
```

```
$ npx -y knip
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from /Users/m.ivanov4/.npm/_npx/8d873e0e769cf1b4/node_modules/knip/dist/PrincipalFactory.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:887:9)
    at moduleResolve (node:internal/modules/esm/resolve:936:20)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.17.1
```

**Comment by webpro** [comment]
Thanks for reporting this. Knip requires peer dependencies `typescript` and `@types/node` and I'm not sure why `npx` fails to find or install those. 

Not sue how to reproduce. When I try this and `knip` is not globally available (i.e. `knip` or `which knip` err and nothing in `npm ls -g` has `knip` listed etc.), "it works on my machine". Maybe it's an old/specific version of npm?

You could try `pnpm dlx knip` or `bunx knip` too as a workaround.

**Comment by splincode** [comment]
I tested on my fresh environment and it doesn't work also

```
$ node -v
v20.10.0
$ npm -v
10.2.3
```

**Comment by jakebailey** [comment]
FWIW I can't reproduce this with all latest:

```console
$ COREPACK_ENABLE_STRICT=0 npx npm@latest exec knip@latest
Need to install the following packages:
  npm@10.2.5
Ok to proceed? (y) y
Unused dependencies (10)
...
```

**Comment by splincode** [comment]
<img width="1384" alt="image" src="https://github.com/webpro/knip/assets/12021443/647c23cd-1a37-4d6b-b6a4-ddbe24208b22">

**Comment by JoshuaKGoldberg** [comment]
I can reproduce this on ESLint right now _if_ `knip` is installed as a dev dependency:

```shell
git clone https://github.com/eslint/eslint
cd eslint
npm i -D knip --legacy-peer-deps
npx knip
```

```plaintext
joshgoldberg ~/repos/eslint $ npx knip
node:internal/modules/esm/resolve:844
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from /Users/josh/repos/eslint/node_modules/knip/dist/PrincipalFactory.js
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1121:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.10.0
```

**Comment by jakebailey** [comment]
Doesn't `--legacy-peer-deps` mean no peer deps get auto installed, and therefore that break is expected?

I think the global install is depending on whatever people happen to have gotten into their global caches, which is unfortunate and I didn't realize that `npx` would not be properly installing peer deps.

(Then again, it's a little odd to use `knip` globally, becuase I would expect that my workspace typescript be used, not some random version set by `knip`).

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.4.0. See [Release 5.4.0](https://github.com/webpro/knip/releases/tag/5.4.0) for release notes._

**Comment by webpro** [comment]
Btw this works too:

```
npx -y -p typescript -p @types/node knip
```

**Comment by splincode** [comment]
<img width="480" alt="image" src="https://github.com/webpro/knip/assets/12021443/1504663c-5d4a-4ccf-bd0b-b4d75fe3c627">

**Comment by webpro** [comment]
From [the npx docs](https://docs.npmjs.com/cli/v10/commands/npx):

> The `-p` argument is a shorthand for `--parseable` in npm, but shorthand for `--package` in npx. This is maintained, but only for the `npx` executable.

Maybe I'm reading it wrong, here's the version without shorthands:

```
npx --yes --package typescript --package @types/node knip
```

**Comment by juergenisch** [comment]
@splincode @webpro I ran into the same issue, in my case it helped to use a different typescript version than my version that was locally installed.

`npx -p typescript@latest -p knip knip`

**Comment by silverwind** [comment]
Ran into the same issue with latest version, `@types/node` and `typescript` are present, the above `npx` commands do work but I don't think they are proper solutions.

**Comment by webpro** [comment]
What would be a proper solution?

**Comment by silverwind** [comment]
One where `npx knip` works standalone, of course :)

**Comment by tordans** [comment]
First time knip user: I had this issue on all 3 projects that I tested knip on. `bunx knip` was the workaround that worked for me.
