### ISSUE TITLE
Support for import path aliases

### ISSUE THREAD

**Issue by juanmagalhaes** [webpro/knip#39]
This project seems to currently support typescript path aliases aliases. However, there are many other possible ways to create path aliases. For instance:

- jsconfig
- jest configuration (for tests only)
- module-alias package
- Babel config

And I'm sure there are a lot more possibilities out there.

I would be interesting if this project had a more generic way to specific aliases through config and CLI parameters instead of trying to figure out through your project config (Even though it's nice if it can figure out magically it sounds a lot easier if we could just tell it what the aliases look like)

I love the project idea though!

**Comment by webpro** [comment]
Absolutely. This has actually been in some old version, but it will be back as a new feature after v1 lands.

**Comment by webpro** [comment]
The feature to add `paths` has been added in [v1.6.0](https://github.com/webpro/knip/releases/tag/1.6.0). Also see the docs at https://github.com/webpro/knip#paths.

**Comment by mcmxcdev** [comment]
I am not entirely sure but I think knip only checks for `tsconfig.json` but not other variations of that filename right?

With https://nx.dev/ which we use, it's common to have a `tsconfig.base.json` (notice the name) at the root of the project.

When running knip without any config, I see our custom lib names as "Unlisted or unresolved dependencies".
When basically copying and pasting the paths from `compilerOptions.paths` to `knip.json` paths, these unresolved deps are gone. So I think it would make sense to support `tsconfig.base.json` out of the box.

**Comment by mcmxcdev** [comment]
Additionally, we have imports like `~/components/plans-details/TierCircle` which show up as unresolved.

The tsconfig.paths config for that is:

```
"~/*": ["./*"]
```

Just putting my 2 cents here since its related to import path aliases improvements :smile:

**Comment by webpro** [comment]
> I am not entirely sure but I think knip only checks for `tsconfig.json` but not other variations of that filename right?
> 
> With https://nx.dev/ which we use, it's common to have a `tsconfig.base.json` (notice the name) at the root of the project.
>
> When running knip without any config, I see our custom lib names as "Unlisted or unresolved dependencies". When basically copying and pasting the paths from `compilerOptions.paths` to `knip.json` paths, these unresolved deps are gone. So I think it would make sense to support `tsconfig.base.json` out of the box.

The default is indeed `tsconfig.json` (in root and/or in any workspace package). This can be overridden using `-t` or `--tsConfig`. When there is an `extends` in the TS config, that should work fine, too. You should not need to manually copy over the `paths` when using TS config.

**Comment by webpro** [comment]
Going to close this one as I think the original issue is resolved.
