### ISSUE TITLE
“Duplicate package name” error when using package at workspace root with pnpm

### ISSUE THREAD

**Issue by geigerzaehler** [webpro/knip#390]
In a legacy project I’m using have a package at the repository/workspace root. When I run `knip` I get the error “Duplicate package name: \<root package name\>”.

**Reproduction**

```bash
mkdir knip-root-workspace
cd knip-root-workspace
pnpm init
cat >pnpm-workspace.yaml <<<"packages:
- .
- packages/*"
pnpm add -w knip
pnpm exec knip
```

knip version 3.7.0

I’ll try to provide a PR that fixes this

**Comment by webpro** [comment]
Do you think the error message is not valid?

Knip requires package names to be unique, otherwise it could run into trouble when finding files or assigning issues to workspaces.

**Comment by geigerzaehler** [comment]
> Do you think the error message is not valid?

Yes, the error message is not valid. It’s caused by the package at the root being processed twice. In the reproduction, there is only one package.json at the root with package name “knip-root-workspace”. And still `knip` shows an error.

**Comment by webpro** [comment]
I see, the issue was not in dup package names, but dup workspace dirs. Thanks for the PR!
