### ISSUE TITLE
Add support for 11ty

### ISSUE THREAD

**Issue by what1s1ove** [webpro/knip#394]
Hey guys! I've just added your package to some of my small projects. Thank you so much for your work!!

Here is my `knip.config.js` as a result:

```js
/** @typedef {import('knip/dist').KnipConfig} KnipConfig */

/** @type {KnipConfig} */
let config = {
	entry: [
		`source/scripts/index.js`,
		`eleventy.config.cjs`, // 11ty – config has a lot of dependencies
		`.linthtmlrc.cjs`, // linthtml
	],
	ignore: [
		`source/data/**/*.cjs` // 11ty
	],
	ignoreDependencies: [
		`linthtml-config-htmlacademy` // linthtml
	],
}

export default config

```

I would like to suggest adding an Eleventy plugin. [Eleventy](https://www.11ty.dev/) is a very cool static site generator.

**Comment by what1s1ove** [comment]
I am not sure if it's necessary to create an issue for my other suggestions, because I'm not sure if you'll be happy with many issues from me 😁

I'll write them here, and later, if you think it's necessary, I'll create separate ones.

1. Add support for [linhtml](https://github.com/linthtml/linthtml) as well
2. Before using your package, I used a `Makefile` as a file to store all my application scripts (not the `scripts` section in `package.json`). There are many reasons for this (comment support, variables, working with all platforms (Deno, Bun, etc.), and so on). I migrated the scripts to `package.json` along with your package since I have fairly small projects. However, as a future plan, you might want to consider expanding support for script files.
3. I understand you [here](https://github.com/webpro/knip/issues/182#issuecomment-1664316828), but I still think it would be cool to have `knip.config.js` as a possible config file name, as most other configuration files have this prefix or plan to have it (usually with a migration to ESM).

**Comment by webpro** [comment]
> I am not sure if it's necessary to create an issue for my other suggestions, because I'm not sure if you'll be happy with many issues from me 😁

I'm interested in any type of feedback or input. Signals matter :)

> I'll write them here, and later, if you think it's necessary, I'll create separate ones.

I think I speak not only for myself as a maintainer if I say that separate tickets for separate issues are almost always a good idea :)

**Comment by what1s1ove** [comment]
> > I am not sure if it's necessary to create an issue for my other suggestions, because I'm not sure if you'll be happy with many issues from me 😁
> 
> I'm interested in any type of feedback or input. Signals matter :)
> 
> > I'll write them here, and later, if you think it's necessary, I'll create separate ones.
> 
> I think I speak not only for myself as a maintainer if I say that separate tickets for separate issues are almost always a good idea :)

Cool! Thank you! I've moved them to separate issues/comments.
- htmllint – https://github.com/webpro/knip/issues/395
- more script files – https://github.com/webpro/knip/issues
- `knip.config.js` – https://github.com/webpro/knip/issues/182#issuecomment-1859132471

**Comment by webpro** [comment]
Thank you! Really appreciate the input.

Any chance you would be up for a PR and contribute to Knip? Sounds like [creating a Knip plugin](https://knip.dev/guides/writing-a-plugin) is similar to the [Remix plugin](https://github.com/webpro/knip/blob/v4/packages/knip/src/plugins/remix/index.ts). No worries if not!

**Comment by what1s1ove** [comment]
> Thank you! Really appreciate the input.
> 
> Any chance you would be up for a PR and contribute to Knip? Sounds like [creating a Knip plugin](https://knip.dev/guides/writing-a-plugin) is similar to the [Remix plugin](https://github.com/webpro/knip/blob/v4/packages/knip/src/plugins/remix/index.ts). No worries if not!

Of course, I'll try to do it in the middle of the week 🙏

**Comment by what1s1ove** [comment]
Hey @webpro !

Could you take a look?

https://github.com/webpro/knip/pull/404

**Comment by what1s1ove** [comment]
Hey @webpro 
Since PR https://github.com/webpro/knip/pull/404 is merged, I think it can be closed.

Btw, when can I try this? I see that it is already available on website - https://knip.dev/reference/plugins/eleventy/, but I still cannot try it in npm package 🥲

**Comment by what1s1ove** [comment]
Thank you @webpro !
https://github.com/webpro/knip/pull/404
