### ISSUE TITLE
Add support for linthtml

### ISSUE THREAD

**Issue by what1s1ove** [webpro/knip#395]
Hey guys!
I think it would be great to add support for [linthtml](https://github.com/linthtml/linthtml). I can't say that the package is extremely popular, but it's definitely the best among all currently available options for similar tasks.

```js
/** @typedef {import('knip/dist').KnipConfig} KnipConfig */

/** @type {KnipConfig} */
let config = {
	entry: [
		`source/scripts/index.js`,
		`.linthtmlrc.cjs`, // linthtml
	],
	ignoreDependencies: [
		`linthtml-config-htmlacademy` // linthtml
	],
}

export default config
```

**Comment by webpro** [comment]
A plugin for this is certainly a welcome addition :)
