### ISSUE TITLE
Add support for more script files

### ISSUE THREAD

**Issue by what1s1ove** [webpro/knip#396]
Hey guys!

Before using your package, I used a `Makefile` as a file to store all my application scripts (not the `scripts` section in `package.json`). There are many reasons for this (comment support, variables, working with all platforms (Deno, Bun, etc.), and so on). I migrated the scripts to `package.json` along with your package since I have fairly small projects. However, as a future plan, you might want to consider expanding support for script files.

**Comment by webpro** [comment]
Knip has support for bash/script files, plugins like husky, lefthook and lint-staged use this.

Depending on the generic usefulness we could think of a new plugin? I have no idea if parsing a `Makefile` is feasible (for [bash-parser](https://www.npmjs.com/package/@ericcornelissen/bash-parser))?

If you're interested, you can search for "bash parser" and "tree sitter" in this repo for some drama around the topic :)

**Comment by webpro** [comment]
Going to close this one, feel free to request plugins in #483

**Comment by silverwind** [comment]
For most intends and purposes, you can parse a makefile like a bash file, e.g. commands will appear like in a bash script `npx eslint`, etc.
