### ISSUE TITLE
Unexpected `Unused item in ignoreDependencies` with wildcard workspaces

### ISSUE THREAD

**Issue by romainmenke** [webpro/knip#397]
see the error log in : https://github.com/csstools/postcss-plugins/actions/runs/7242391687/job/19727755824?pr=1220

```
Unused item in ignoreDependencies (workspace: plugins/postcss-color-functional-notation): style-dictionary-design-tokens-example
Unused item in ignoreDependencies (workspace: plugins/postcss-attribute-case-insensitive): open-props
```

The relevant bit of config : https://github.com/csstools/postcss-plugins/blob/0c4162a31eb9368c5cbf13de5ab39edafe00b02e/knip.json#L20-L40

```json
		"plugins/*": {
			"entry": [
				".tape.{cjs,mjs}",
				"generate/*.mjs",
				"src/browser-global.js",
				"src/browser.js",
				"src/index.js",
				"src/index.ts",
				"test/_import.mjs",
				"test/_require.cjs",
				"test/test.mjs"
			],
			"project": [
				"**/*.{ts,js,mjs}",
				"test/**/*.{cjs,mjs,js}"
			],
			"ignoreDependencies": [
				"open-props",
				"style-dictionary-design-tokens-example"
			]
		},
```

What I think is happening :

- some packages have these dependencies
- other packages do not
- we ignore these dependencies because they are not JavaScript content, but rather CSS, design tokens, ... that use npm as a package manager.

Up to `3.7.0` it seems that for wildcards (e.g. `plugins/*`) an `ignoreDependencies` entry was considered used if any package had it as a dependency.

After `3.7.0` this seems to have changed so that every package needs to have the dependency.

**Comment by webpro** [comment]
I fixed (and broke?) a few things in v3.8.1, are you using that version?

**Comment by romainmenke** [comment]
Yes, this is on exactly `v3.8.1` :)

**Comment by romainmenke** [comment]
I found that I can workaround this issue by adding specific entries for packages that require `ignoreDependencies`:

```json
		"plugins/postcss-global-data": {
			"entry": [
				".tape.{cjs,mjs}",
				"src/index.ts",
				"test/_import.mjs",
				"test/_require.cjs"
			],
			"project": [
				"**/*.ts",
				"test/**/*.{cjs,mjs,js}"
			],
			"ignoreDependencies": [
				"open-props"
			]
		},
		"plugins/*": {
			"entry": [
				".tape.{cjs,mjs}",
				"generate/**/*.mjs",
				"scripts/**/*.mjs",
				"src/browser-global.js",
				"src/browser.js",
				"src/index.js",
				"src/index.ts",
				"test/_import.mjs",
				"test/_require.cjs",
				"test/test.mjs"
			],
```

If that is how knip should be used then I don't mind changing to that.

I liked the wildcards because it allowed me to have less config, but I am aware that having wildcards that cover more than 50 packages and ignore states that only apply to some is not ideal. That opens the door to exactly the kinds of issues `knip` is intended to prevent.

**Comment by webpro** [comment]
I totally get the annoyance here, but the idea of the configuration hints is that when things are actually removed/fixed, the configuration should also be updated. So it's a bit of an investment initially, hopefully resulting in easier maintenance (especially in the long run, when other people forget, hand over over, etc, etc).

Guess the fix was a breaking change for you, sorry about that.

**Comment by romainmenke** [comment]
This wasn't even the slightest bit annoying :)

Thank you for verifying that everything is working as intended 🙇
