### ISSUE TITLE
better compiler support (svelte, vue, etc)

### ISSUE THREAD

**Issue by thenbe** [webpro/knip#399]
Is my assumption correct that all the code snippets listed [here](https://knip.dev/features/compilers/) are provided by knip as "recipes" in that users are expected to manually copy/paste the snippet into their own `knip.ts`?

I ask because the compiler [recipe](https://github.com/webpro/knip/blob/ae91dac79e4d0d05ac3d10aefd4b49ecab61ed6d/packages/docs/src/content/docs/features/compilers.md?plain=1#L118-L139) for svelte works great; knip can accurately analyze a sveltekit project given the right config. But is there a way that we can infer (or at least provide) this automatically and avoid requiring users to manually add that boilerplate into their own config? That way users are no longer required to create a config file, realize they need extra logic for svelte files, copy the boilerplate into their config, maintain it over time, etc.

Ideally, I'd like to see knip get to the point where running `npx knip` in a typical sveltekit (or similar) project just works. While I realize that there may be reasons that make it difficult or even impossible to reach that state (extra required dependencies, versioning, etc), I can't help but wonder if there's a bit more we can do here.

**Comment by webpro** [comment]
Absolutely, and I appreciate you're sharing this insight and I totally agree .

Here's some related thoughts:

- For me it's not an option to include parsers of frameworks that require compilation of non-standard files out there to fully automate it (bundle size/install bloat). 
- The thing I'm concerned about when building this into Knip is mostly about peer dependencies: Knip could use a different version or even a different package to parse the source files. I don't like the DX, but this is why I've moved the burden to users when introducing this feature.
- May not be a huge deal when most of the time we just need to grab import statements, though.
- The dependencies (compilers) are probably already in `node_modules`, but which package should we use to compile? I don't like the idea of automagically importing stuff and `try` things.
- A real parser is definitely recommended above regexes. However, when regexes are good enough they would solve most of the issues above.
- I think the challenge can be tackled extension-per-extension.
- Maybe something like detecting e.g. `.vue` (or any extension) and then installing the associated regex-based compiler is an acceptable default. The user can then override it with an actual compiler if the results are not good enough.
- I guess Svelte only has one compiler that everyone uses? I'm not a user myself, so not sure what could go wrong here (compilers may have plugins or extra stuff?).
