### ISSUE TITLE
schema mismatch (missing svelte key)

### ISSUE THREAD

**Issue by thenbe** [webpro/knip#400]
svelte is included in the json [schema](https://github.com/webpro/knip/blob/ae91dac79e4d0d05ac3d10aefd4b49ecab61ed6d/packages/knip/schema.json?plain=1#L389-L392), but not in the zod [schema](https://github.com/webpro/knip/blob/ae91dac79e4d0d05ac3d10aefd4b49ecab61ed6d/packages/knip/src/ConfigurationValidator.ts?plain=1#L115-L116). Although it's not clear to me which one is correct; is the svelte plugin supposed to be editable? Even after adding svelte to the zod schema, adding patterns to `svelte.entry` in my config had no effect (but adding the same pattern in the plugin source code worked fine).

**Comment by webpro** [comment]
Oops.. the Svelte plugin is not editable indeed 😅

Example in another plugin: https://github.com/webpro/knip/blob/v4/packages/knip/src/plugins/next/index.ts#L35-L38

Any chance you would be up for a PR?

Then it will also make more sense to have the `entry` files under the `svelte` config again :)

**Comment by thenbe** [comment]
> Then it will also make more sense to have the entry files under the svelte config again :)

The reason I felt it's better in `entry` was because I could then avoid having to manually re-declare all the entry patterns provided by knip's svelte plugin. Because (if I understand correctly) once you set your own pattern array (in `entry`, `project`, or `config`) then the original patterns are no longer used.

It would be useful if we can do something like this:

```typescript
const config: KnipConfig = {
   svelte: {
     // allow entry to take either a string[] or a function that returns a string[]
     entry: (predefined) => [
      'src/posts/*.md' // include my custom pattern
       ...predefined,  // along with any patterns provided by knip
     ]
   }
}
```

Keeping my custom pattern in the root `entry` for now gives me a fake sense that this sort of pattern merging is already possible lol

**Comment by webpro** [comment]
That makes sense; eventually the entry files end up in the same TypeScript program.

Your suggestion is also interesting, to allow a function. Not a priority for me right now to be honest, but I'll keep it in mind.

Thanks a lot for the PR!
