### ISSUE TITLE
Improve documentation for the tests section on the "Writing A Plugin" page

### ISSUE THREAD

**Issue by what1s1ove** [webpro/knip#405]
Based on the location of the `test` folder in the source code of the project, the path should be `test/plugins/cool-linter.test.ts` instead of `tests/plugins/cool-linter.test.ts`.

<img width="761" alt="image" src="https://github.com/webpro/knip/assets/42296182/033a295a-7236-4961-895e-e0b65f47504f">

**Comment by webpro** [comment]
Thanks for reporting this!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.12.0. See [Release 3.12.0](https://github.com/webpro/knip/releases/tag/3.12.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v4.0.0. See [Release 4.0.0](https://github.com/webpro/knip/releases/tag/4.0.0) for release notes._
