### ISSUE TITLE
Markdown reporter

### ISSUE THREAD

**Issue by drodil** [webpro/knip#409]
Could it be possible to get markdown reporter as part of the knip? It would be pretty much same kind as the default reporter but it could do some table formatting + proper headers for example in markdown

**Comment by webpro** [comment]
Absolutely. You can use a local, custom reporter. Perhaps copy from an existing one. And I'd be happy to review a PR to include and ship it with Knip.

**Comment by drodil** [comment]
Awesome, we might have use for it in https://github.com/backstage/backstage/pull/21963. I am off for holidays and can probably have a look at this when I am back if nobody else does before I am back. Merry Christmas 🎄
