### ISSUE TITLE
Add `find` to `IGNORED_GLOBAL_BINARIES`

### ISSUE THREAD

**Issue by RebeccaStevens** [webpro/knip#413]
[find on npm](https://www.npmjs.com/package/find) doesn't have a binary.

`fine` is a commonly available binary on unix systems (is that the right wording?) so it should be added to `IGNORED_GLOBAL_BINARIES`.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.9.0. See [Release 3.9.0](https://github.com/webpro/knip/releases/tag/3.9.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v4.0.0. See [Release 4.0.0](https://github.com/webpro/knip/releases/tag/4.0.0) for release notes._
