### ISSUE TITLE
@typescript-eslint/parser as unlisted

### ISSUE THREAD

**Issue by tkrotoff** [webpro/knip#422]
```JS
// File .eslintrc.js

/** @type {import('eslint').Linter.Config} */
const config = {
  root: true,
  parser: "@typescript-eslint/parser",
  ...
};

module.exports = config;
```

package.json:
```JSON
{
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.8.0"
  }
}
```

Knip 3.10.0 output:

```
Unlisted dependencies (1)
@typescript-eslint/parser  .eslintrc.js
```

**Comment by webpro** [comment]
If you don't have `@typescript-eslint/parser` listed in `package.json` this is expected behavior? You can look up the installation instructions here: https://typescript-eslint.io/getting-started#step-1-installation

**Comment by tkrotoff** [comment]
It works when adding @typescript-eslint/parser, sorry for the bad report
