### ISSUE TITLE
Playwright `projects:` entry points not detected

### ISSUE THREAD

**Issue by phiresky** [webpro/knip#424]
With the following playwright config snippet:

```ts
import { defineConfig, devices } from "@playwright/test";
import * as Configuration from "./configuration";

export default defineConfig({
	testDir: "./tests",
        ....
	/* Configure projects for major browsers */
	projects: [
		{
			name: "global-setup",
			testMatch: /global\.setup\.ts/,
			teardown: "teardown",
		},
		{
			name: "teardown",
			testMatch: /global\.teardown\.ts/,
		},
		{
			name: "chromium",
			use: { ...devices["Desktop Chrome"] },
			dependencies: ["global-setup"],
		},
	],
});
```

And the following directory structure:

```
e2e-tests
├── playwright.config.ts
├── tests
│   ├── global.setup.ts
│   ├── global.teardown.ts
│   ├── register.spec.ts
│   └── tsconfig.json
└── utils.ts
```

`knip --debug` detects the following:

```
[e2e-tests] Playwright config file paths (1)
[ [32m'.../e2e-tests/playwright.config.ts'[39m ]
[e2e-tests] Playwright dependencies (1)
[ [32m'entry:**/*.@(spec|test).?(c|m)[jt]s?(x)'[39m ]
```

So it misses the entry point of `/e2e-tests/tests/global.setup.ts` and `global.teardown.ts`. 

I'm not sure why, since the source code of the plugin seems to indicate that it's looking at the `projects` key in the config

**Comment by webpro** [comment]
The issue here is that Playwright accepts a regex for `testMatch`, which Knip does not support at all. Since it's not trivial to convert regex to glob I'm going to ask you to do that manually for now :)

**Comment by webpro** [comment]
Closing this as "wontfix" for now.

**Comment by ClementValot** [comment]
@webpro What's the reasoning behind not supporting regex? Is this a performance thing? 
I could see `knip.json` entry accepting both string and regex, with a `if (entry instanceof RegExp)` somewhere in the mix

**Comment by webpro** [comment]
What matters here is the underlying glob + matcher libs (e.g. fast-glob or tinyglobby), that's what needs to support it. But I'm also of the opinion that such libs should keep it simple without support for syntax nobody uses (so I'm happy to see #1447 happening).
