### ISSUE TITLE
Unlisted binaries: set

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [webpro/knip#429]
I have this error: "Unlisted binaries: set package.json".
Basically i have a npm script where i first set a env variable like this: `set FORCE_COLOR=1` , because otherwise it wouldn't work on Windows.
But Knip interprets "set" as a binary.

**Comment by webpro** [comment]
This goes through a bash/shell script parser, I guess we can fake/add `set` as a binary.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.13.0. See [Release 3.13.0](https://github.com/webpro/knip/releases/tag/3.13.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v4.0.0. See [Release 4.0.0](https://github.com/webpro/knip/releases/tag/4.0.0) for release notes._
