### ISSUE TITLE
Bump esbuild to 0.16.17

### ISSUE THREAD

**Issue by madx** [webpro/knip#43]
Hello :wave:

`esbuild` released a [`0.16.17` version](https://github.com/evanw/esbuild/releases/tag/v0.16.17) and the `1.2.0` release of Knip has a fixed-version dependency on `0.16.16`.

In our repository we also use esbuild and we are not able to update to knip `1.2.0` because we have esbuild `0.16.17`, updating our Yarn lockfile yields the following error:

```
error /home/madx/company_project/node_modules/knip/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/madx/company_project/node_modules/knip/node_modules/esbuild
Output:
/home/madx/company_project/node_modules/knip/node_modules/esbuild/install.js:130
    throw new Error(`Expected ${JSON.stringify("0.16.16")} but got ${JSON.stringify(stdout)}`);
          ^

Error: Expected "0.16.16" but got "0.16.17"
    at validateBinaryVersion (/home/madx/company_project/node_modules/knip/node_modules/esbuild/install.js:130:11)
```

Would it be possible to update to `0.16.17`? (or have a more relaxed policy on patch versions?)

Thanks

**Comment by webpro** [comment]
It's ironic that just now I'm considering tildes and carets, a minor bump of a `devDependency` breaks `npm run lint` (errors from `eslint-plugin-import` changing the import order).

While I'm 100% in favor of a relaxed policy, I'm holding off for now. Going to bump the rest shortly.

**Comment by madx** [comment]
Thanks a lot, definitely agree on the "semver-but-we-still-break-things-in-patch-versions" policy some packages seem to use ;)
