### ISSUE TITLE
Performance of single package reporting

### ISSUE THREAD

**Issue by drodil** [webpro/knip#430]
This relates to https://github.com/backstage/backstage/pull/21963. I took some performance analysis of knip and here you can see the hotspots that are taking time. 

Command used: `node --prof ./node_modules/knip/bin/knip.js --directory packages/app --no-exit-code --no-progress --include dependencies,unlisted --reporter markdown`

Processed output: [processed.txt](https://github.com/webpro/knip/files/13840036/processed.txt)

Maybe there's something to improve in performance based on this?

**Comment by webpro** [comment]
Thanks for posting this. Is this about v4? Otherwise I prefer not to spend my time on it. Please try v4 canary and see what diff that makes.

**Comment by drodil** [comment]
Ah, it's v3. I can check the v4 as well!

**Comment by drodil** [comment]
V4 report here: [processed2.txt](https://github.com/webpro/knip/files/13840186/processed2.txt) (markdown reporter was not usable in v4 yet)

V4 time: 7.66s user 1.54s system 99% cpu 9.214 total
V3 time: 7.86s user 1.69s system 123% cpu 7.724 total

Not so much difference in execution time between the versions though there are some improvements for V4 visible. Randomly the time is longer for both but that's normal, it's around 7-8 seconds for this one package usually with both versions.

Seems like most of the time both v3 and v4 is going to read the files in `SourceFileManager::getSourceFile` so not sure if there's much to do about it.

**Comment by webpro** [comment]
Yes, no surprises here. Performance is generally much better when linting a monorepo as a whole (as opposed to per workspace separately). Also see https://knip.dev/blog/slim-down-to-speed-up for some additional background.

**Comment by drodil** [comment]
Alright thanks, any chance to get the markdown reporter also included in the canary? I think backstage could start using the canary version then because at the moment only the dependency checks are enabled from knip.

**Comment by webpro** [comment]
Sure, I'll cherry-pick those commits into canary & publish today!

**Comment by webpro** [comment]
Published: https://github.com/webpro/knip/releases/tag/4.0.0-canary.8
