### ISSUE TITLE
Report a function that is used in an unused export (with ignoreExportsUsedInFile flag)

### ISSUE THREAD

**Issue by onskulit** [webpro/knip#431]
Hello!

I realized that it is useful for my project to enable the `ignoreExportsUsedInFile` flag because export keyword is not an issue, if code is actually used. However, the following problem appeared: sometimes a function is ignored with `ignoreExportsUsedInFile` because it is used in the code, but this code is not actually used either.

**Problem**: removing dead code takes several iterations

Code example:
```
export const helper = () => {}

export const unusedExport = () => {
    helper();
}
```

Knip will not mark `helper` as unused, although it is only used in dead code.

And in addition to this. For some reason, sometimes knip marks exports as unused, and after deleting the file turns out to be empty. It seems it would be more correct to mark the entire file as unused. Unfortunately, I can’t give a more detailed example, since it was some time ago and I can’t reproduce it.

**Comment by webpro** [comment]
While this would be a powerful feature, there are a few relevant topics here:

- enabling `ignoreExportsUsedInFile` but also "ignore it only in not-dead code" adds complexity
- doing multiple passes, which is currently hard/expensive/not in scope for Knip
- isolated file-based linting, which is not in scope for Knip

Combined, I currently just don't see this happen anytime soon.

> And in addition to this. For some reason, sometimes knip marks exports as unused, and after deleting the file turns out to be empty. It seems it would be more correct to mark the entire file as unused. Unfortunately, I can’t give a more detailed example, since it was some time ago and I can’t reproduce it.

I think I understand, I guess it comes down to the same topic as doing multiple passes. Knip fixes things after the actual analysis, and it would need to determine there are (1) no used exports left and (2) there are no other side-effects left, and the whole file can be deleted.

**Comment by webpro** [comment]
The answer is in "multiple passes" and combine with an isolated file linter such as ESLint :)
