### ISSUE TITLE
Report duplicates in configuration as `Configuration issues`

### ISSUE THREAD

**Issue by auvred** [webpro/knip#434]
I noticed that knip reports unused items in `ignoreDependencies` for example, but doesn't report if `ignoreDependencies` contains duplicated entries, for example:

```json
{
  "ignoreDependencies": [
    "package-a",
    "package-a"
  ]
}
```

I think it'd be nice if knip would report such issues

**Comment by webpro** [comment]
Any option could be checked for duplicates. Is there any tool that actually does this? I'm kinda worried to overdo this kind of checks. Maybe there's even a way to do this statically with JSON Schema and/or TypeScript?

**Comment by auvred** [comment]
> with JSON Schema

No, it doesn't support such things 

> TypeScript

If we somehow enforce this at the type level, users will not be able to dynamically pass `string[]` values

> I'm kinda worried to overdo this kind of checks

This makes sense. I totally understand you, thanks for the reply!

This feature is pretty nit-picky, so if you think it shouldn't be presented in the Knip, let's close the issue

**Comment by webpro** [comment]
Closing this as "wontfix" for now.
