### ISSUE TITLE
Lerna: used libraries marked as unused 

### ISSUE THREAD

**Issue by nemisqe** [webpro/knip#437]
Hi! I have some troubles with Knip setup for Lerna project. I have such project structure:

```
- web
- mobile
- core
- storybook
```

When I run Knip, I see that a lot of libraries appears as unused, but they're used. For example, I see that Knip shows `@amplitude/react-native` as unused (this library installed in `mobile` dir), but it's used In `core` dir. And the same thing happens almost for all libraries.

Is there any way to resolve it? 
I couldn't find any similar issues in git or discord, so I made this ticket. If you need some more information - please ping me. 

Thanks in advance!

`Knip config:`

<img width="832" alt="Screenshot 2024-01-08 at 11 26 55" src="https://github.com/webpro/knip/assets/41796565/911c417f-32b4-4c69-96cf-3516d0334abe">

`lerna.json`

<img width="832" alt="Screenshot 2024-01-08 at 11 27 18" src="https://github.com/webpro/knip/assets/41796565/16a56b17-04ea-4669-a6de-37bf8a69d2dc">

**Comment by webpro** [comment]
> For example, I see that Knip shows `@amplitude/react-native` as unused (this library installed in mobile dir), but it's used In core dir. 

This statement leads me to think Knip behaves as expected.

> If you need some more information - please ping me.

Yes, please see https://knip.dev/guides/troubleshooting#minimal-reproduction

**Comment by nemisqe** [comment]
Thank you for your answer!
Unfortunately, I don't have an opportunity to create like codesandbox 

>This statement leads me to think Knip behaves as expected.

As far as I can see, I should define knip config for **every** workspace in Lerna project, am I right? Or I can somehow to use only one config at the top of project?

**Comment by webpro** [comment]
Knip works with one configuration at the root, and uses the `workspaces` in `package.json` at the root. See https://knip.dev/features/monorepos-and-workspaces

**Comment by webpro** [comment]
> Unfortunately, I don't have an opportunity to create like codesandbox because of NDA:(

You can use different names, etc. It should be minimal and generic.
