### ISSUE TITLE
FR: more informative error messages

### ISSUE THREAD

**Issue by Akaprog** [webpro/knip#443]
**Situation**
```
npx knip
Analyzing workspace ....
Error loading app/cypress.config.ts
Reason: Invalid or unexpected token
```

with debug it showed exactly the right file (in my case, it was broken installation of bluebird as cypress dependency, with one file replaced with a png image)

**Proposal**
I wish if knip returned cause part (or full loader error) for such cases, something like this

```
LoaderError: 
[cause]: /app/node_modules/bluebird/js/release/finally.js:1
  �PNG
```

**Comment by webpro** [comment]
Is this still an issue? Feel free to re-open if necessary :)
