### ISSUE TITLE
Resolving Knip error with automatic Imports using unplugin-vue-components

### ISSUE THREAD

**Issue by joris-gallot** [webpro/knip#445]
Hello!

I'd like to add [unplugin-vue-components](https://github.com/unplugin/unplugin-vue-components) to a Vue.js project, which allow  automatic imports of components found in the `components` directory. However, when removing the imports for these components, Knip raises an error as it cannot recognize that they are imported automatically (`Unused exports`).
Do you think there might be a way to help Knip understand that these components are automatically imported?
If anyone has an idea, I'd be happy to take a look and work on it! Thanks!

My Knip configuration:
```ts
export default {
  rules: {
    classMembers: 'off',
    unlisted: 'off',
  },
  ignoreBinaries: ['date', 'ln', 'pwd', 'madge'], // package.json
  ignoreDependencies: [
    'lodash-es',
    'stylelint',
    '@tiptap/extension-floating-menu',
    '@tiptap/html',
    '@splidejs/splide',
    '@splidejs/vue-splide',
  ],
  ignore: ['**/*.d.ts', 'histoire.config.ts', '**/*.story.vue'],
  entry: [
    'src/main.ts',
    'vite.config.ts',
    'upload-sourcemaps.js',
    'src/histoire-setup.ts',
    'postcss.hexrgba.js',
    'scripts/*',
    '**/*.spec.{js,ts}',
  ],

  project: '**/*.{ts,vue}',
  compilers: {
    vue: (text) => {
      const compiler = /<script\b[^>]*>([\s\S]*?)<\/script>/gm;
      const scripts = [];
      let match;
      while ((match = compiler.exec(text))) scripts.push(match[1]);
      return scripts.join(';');
    },
  },
};

```

**Comment by webpro** [comment]
Probably the easiest way is to add the auto-imported components to the `entry` paths.

**Comment by joris-gallot** [comment]
Does that mean if a component is no longer used, I won't get a Knip error?
I've tested it, and I don't get any errors, do you think there might be a way to trigger an error if a component is not used (thus not imported)?

**Comment by webpro** [comment]
> Does that mean if a component is no longer used, I won't get a Knip error?

No, entry files are glob matches, even zero matches is not an error. And they don't need to be `import`-ed by another module.

> I've tested it, and I don't get any errors, do you think there might be a way to trigger an error if a component is not used (thus not imported)?

Since the components are auto-imported, there's no way for Knip to understand this. Knip basically works from entry files and then following `import` statements.

Custom resolvers don't work great with Knip I'm afraid. I don't currently see an easy way to add a custom resolver. But feel free to explore this, I'm open to something clean and maintainable.

Or... don't use magic and explicitly import components.

**Comment by joris-gallot** [comment]
Thanks for the details and quick responses! 

I think we can close this for now; I'm not ready to explore more on this

**Comment by webpro** [comment]
Alright, cool!

I appreciate the feedback, at the very least it serves as a reminder that custom resolvers could be a very useful feature (perhaps a bit similar to how custom compilers fit in pretty well).
