### ISSUE TITLE
How can I use it without any configuration file?

### ISSUE THREAD

**Issue by marco-carvalho** [webpro/knip#446]
I would like to just call `npx knip App.tsx`. Is this possible?

**Comment by webpro** [comment]
No, you'd need a config file with that entry path

**Comment by marco-carvalho** [comment]
@webpro do you see value in a feature like this? Or maybe something like `npx knip --entry App.tsx`.

**Comment by webpro** [comment]
Not sure.. Once this option would become available as an argument, I'm sure the others will be expected too and at this point I wonder how useful it is too duplicate all that.

**Comment by marco-carvalho** [comment]
Just to tell you about my use-case: I thought it would be a good idea to edit multiple repos of mine to include a Github Actions to check if `knip` throws anything, and I was kinda praying to just only add via Github web interface a line of something like `npx knip App.tsx` or `npx knip --entry App.tsx` into my Github Actions `.yml`, and not manually enter in every repo and create a config file.

**Comment by webpro** [comment]
Maybe hack something in like so:

```
echo '{"entry":"App.tsx"}' > knip.json && knip
```

**Comment by marco-carvalho** [comment]
thanks for the help @webpro

**Comment by webpro** [comment]
Alright, let's close this then.
