### ISSUE TITLE
Dependency pinning vs ranges

### ISSUE THREAD

**Issue by kachkaev** [webpro/knip#45]
👋 @webpro!

WDYT of using dependency ranges (e.g. `^`) instead of pinned versions? I just opened https://github.com/blockprotocol/blockprotocol/pull/895 to test https://github.com/webpro/knip/issues/31 and noticed an extra instance of `eslint` in my `yarn.lock`. It’d be great if it could be deduplicated.

**Comment by webpro** [comment]
Yeah, also see #43. Just when I wanted to introduce tildes and/or carets I had a bad experience with a breaking change in a minor or patch update. Will look into it again, as I'm totally in favor of Knip being a good citizen in anyone's `node_modules`.

**Comment by webpro** [comment]
I've introduced semver ranges for `dependencies` in v1.6.1, let's see how this goes...

**Comment by kachkaev** [comment]
No more duplicate ESLint instance in https://github.com/blockprotocol/blockprotocol/pull/895, thanks! 🎉
