### ISSUE TITLE
False positive for Unused exported class members with mapped type interface

### ISSUE THREAD

**Issue by danvk** [webpro/knip#450]
Knip version: 3.13.2

I have a `class` that implements an `interface`. Knip reports that all the required methods from that `interface` are unused, but this definitely isn't true: deleting them causes a TypeScript type error and a runtime exception.

Minimal repro here: https://github.com/danvk/knip-unused-member-repro
Original occurance here: https://github.com/danvk/gravlax/actions/runs/7509061003/job/20445621772

```
> npx tsx src/index.ts
3
> pnpm knip
Unused exported class members (2)
literal  Interpreter  src/class.ts:15:3
binary   Interpreter  src/class.ts:4:3
```

**Update** It seems to have to do with the mapped type in the `interface`, making this change makes the knip error go away:

```
export type ExpressionVisitor<R> = {
-  Kind in Expr["kind"]]: (expr: Extract<Expr, { kind: Kind }>) => R;
+  binary(expr: Binary): R;
+  literal(expr: Literal): R;
};
```

Maybe this is the same as #414, I'm not sure.

```ts
// interface.ts
export interface Binary {
  kind: "binary";
  left: Expr;
  operator: '+' | '*';
  right: Expr;
}

export interface Literal {
  kind: "literal";
  value: number;
}

export type Expr = Binary | Literal;

export type ExpressionVisitor<R> = {
  [Kind in Expr["kind"]]: (expr: Extract<Expr, { kind: Kind }>) => R;
};

export function visitExpr<R>(expr: Expr, visitor: ExpressionVisitor<R>): R {
  return visitor[expr.kind](expr as never);
}
```

```ts
// class.ts
import { Binary, Expr, ExpressionVisitor, Literal, visitExpr } from "./interface";

export class Interpreter implements ExpressionVisitor<number> {
  binary(expr: Binary): number {
    const left = this.evaluate(expr.left);
    const right = this.evaluate(expr.right);
    if (expr.operator === '+') {
      return left + right;
    } else if (expr.operator === '*') {
      return left * right;
    }
    throw new Error('unsupported operator');
  }

  literal(expr: Literal): number {
    return expr.value;
  }

  evaluate(expr: Expr): number {
    return visitExpr(expr, this);
  }
}
```

```ts
// index.ts
import {Expr, visitExpr} from './interface';
import {Interpreter} from './class';

const expr: Expr = {
  kind: 'binary',
  operator: '+',
  left: {
    kind: 'literal',
    value: 1,
  },
  right: {
    kind: 'literal',
    value: 2
  },
};

console.log(visitExpr(expr, new Interpreter()));
```

**Comment by webpro** [comment]
Thanks for the extensive bug report, Dan.

When you do "Find All References" for `binary` or `literal` in VS Code there are no results (other than a ref to itself). Knip uses the same `findReferences` method from the Language Server.

That's also what makes this issue different from #414 (that one exposes a difference in the `findReferences` results between Knip and e.g. in VS Code).

So it's more of an issue with TypeScript itself, not sure whether they'd consider this a bug or not.

As an aside, maybe it has something to with the fact that `class Interpreter implements` a `type` (not an `interface`), although I understand you want to pass in the generic `number` and map over `Expr` to declare the methods.

**Comment by danvk** [comment]
Thanks for the info @webpro! I filed an issue against TypeScript, we'll see what they say.

Regardless of whether they consider the current behavior correct, I'd say this is a bug with Knip. It may just be an extremely difficult one to fix :)

**Comment by webpro** [comment]
Going to close this one here. This will likely be either fixed by TypeScript, or not at all.
