### ISSUE TITLE
Eleventy plugin: ignore JavaScript "data" files

### ISSUE THREAD

**Issue by uncenter** [webpro/knip#453]
The Eleventy plugin exists, but doesn't resolve anything from the configuration. I'm hoping we can extract the `dirs.data` property returned from the configuration file function and count files in that directory as entry files, but unfortunately Eleventy configuration files export functions that take in a very specific class with many methods. Is there a way to lie to JavaScript about what methods exist on a class and just pass a dummy class?

**Comment by webpro** [comment]
The Eleventy plugin deserves some love indeed. Do you know/have some example repo(s) with such configuration? Perhaps even pointers to Eleventy code that passes that (class) argument(s)?

**Comment by uncenter** [comment]
Sure! I'd love to help however I can. Here's [the configuration file of my website](https://github.com/uncenter/uncenter.dev/blob/main/eleventy.config.js). Most of it is not relevant for Knip and simply uses the class methods I mentioned to configure Eleventy:

https://github.com/uncenter/uncenter.dev/blob/164678271da7eeddb1065f60247a97ae393bd3b9/eleventy.config.js#L27-L119

But then at the very bottom, the function returns an object:

https://github.com/uncenter/uncenter.dev/blob/main/eleventy.config.js#L121-L131

As you can see, the `dir.data` property of the returned object points to [a directory containing JS/JSON files](https://github.com/uncenter/uncenter.dev/tree/main/src/_data) that Eleventy uses. *Note:* that object won't necessarily have those properties, so we'll have to hard code a default configuration to fall back on, I think.

Again, the issue here is really that I'm not sure how we can load and run the config function without access to the actual class. The simplest/stupidest way would be to manually create a dummy class with all the right properties but nothing inside of them? I'm familiar with Eleventy's code base, so I can help with that... let me know what you think!

**Comment by uncenter** [comment]
For reference, here is the class that Eleventy passes to the config function: https://github.com/11ty/eleventy/blob/main/src/UserConfig.js.

**Comment by webpro** [comment]
Thanks a lot! Very helpful.

Executing a function a function with dummy objects is something some other plugins are already doing, just to name a few:

- https://github.com/webpro/knip/blob/main/packages/knip/src/plugins/babel/index.ts#L41
- https://github.com/webpro/knip/blob/main/packages/knip/src/plugins/gatsby/index.ts#L45
- https://github.com/webpro/knip/blob/main/packages/knip/src/plugins/webpack/index.ts#L67

But I guess that class looks a bit frightening as configurations may use any prop or method. Could mostly be just no-ops I guess? Also the first take does not need to be perfect. But ideally not throw either.

Would you like to stab at it yourself?

**Comment by uncenter** [comment]
Yes! I'll give that a go.

**Comment by webpro** [comment]
Awesome! I'll leave you to it, but I'm here to help in case you need anything.

**Comment by uncenter** [comment]
Can an entry pattern just be a whole directory? Or should I recursively read the files in each directory to figure that out...

**Comment by webpro** [comment]
An entry pattern matches files, not directories, e.g. `toEntryPattern('dir/**/*.ts')`. Some plugins such as for Playwright have a `config.testDir` that's prepended to each of such an entry pattern. But not sure what is exactly the use case here?

**Comment by uncenter** [comment]
Right yeah they are globs, forgot about that. 🤦
