### ISSUE TITLE
Rush JS monorepo support

### ISSUE THREAD

**Issue by Faithfinder** [webpro/knip#457]
At our workplace we're using a monorepo management tool called Rush.
https://rushjs.io/pages/intro/welcome/

It's semi-popular at >600k weekly downloads on npm, specializes on industiral scale monorepo management, and is used at Microsoft, HBO and TikTok.
It uses pnpm workspaces underneath, so I believe I can make `knip` work for our repo with some effort anyway using manual workspace definition, however it could be nice if the experience was improved.

There are 2 main differences from the vanilla pnpm workspaces:
* No root package.json
* Package manager files (lockfile, pnpm-workspaces.yaml, npmrc, etc) isn't at the root of the repo (pnpm-workspaces is a generated temp file not commited to git).

A setting to give custom path to the workspaces file could be a solution?

**Comment by webpro** [comment]
I was in a Rush project too, trying to integrate Knip, so I understand the situation. I also understand the value of not having a `node_modules` folder at the root. Still, for various reasons, we ended up migrating to pnpm + Turborepo, as it's less "magic". Obviously I'm not asking you to do the same, but this RFC is currently not in scope as there's a lot more to it than a custom path to the workspaces file.

Would still be great to have some kind of workaround for Rush users if that makes sense and/or if you could share it if/when you would have any.

**Comment by Faithfinder** [comment]
> Would still be great to have some kind of workaround for Rush users if that makes sense and/or if you could share it if/when you would have any.

I will one day, Knip looks great and I want it, but dunno when I'll get the time to do setup. But it will probably just be a manual enumeration of projects in `knip.json#workspaces`. Not perfect, but my startup aint Microsoft, we don't have 600 packages that need settings, should be manageable

**Comment by webpro** [comment]
Maybe the `"."` could be configured as usual, while symlinking the relevant things (`package.json, `node_modules` and `pnpm-workspace.yaml`) to the root. Perhaps naive, but that's basically what Rush does as well to trick pnpm?

**Comment by Faithfinder** [comment]
> Maybe the `"."` could be configured as usual

Oh, I _must_ configure `.`? I thought I could just leave it out.

Another thing that could help in the meantime, is if `knip` searched for `.gitignore` recursively. Right now if I run `knip` without config in an app it's already helpful, but it's highlighting `dist` folder because `.gitignore` is 2 folders up in the hierarchy.

**Comment by webpro** [comment]
> Oh, I must configure .? I thought I could just leave it out.

No, you don't have to, I was just making the connection with the symlinked `package.json` etc.

> Another thing that could help in the meantime, is if knip searched for .gitignore recursively. Right now if I run knip without config in an app it's already helpful, but it's highlighting dist folder because .gitignore is 2 folders up in the hierarchy.

Knip should run from the root, it won't look upwards of it the `cwd` for `.gitignore` files. Even using `--directory` has the same restriction. You can lint separate workspaces using `--workspace` which does take those files into account (https://knip.dev/features/monorepos-and-workspaces#lint-a-single-workspace).

**Comment by webpro** [comment]
```
echo '{"name":"bliep"}` > package.json && pnpx knip --workspace apps/admin && rm package.json
```

**Comment by Faithfinder** [comment]
Runs, but considers all dependencies as unlisted and config files (.eslintrc etc) as unused, lol

**Comment by webpro** [comment]
I guess that's were the symlinking comes in. Or `knip --production --strict` for isolation.

**Comment by Faithfinder** [comment]
I feel like the result is better if I just run it in a project folder. Sure, it picks up gitignored files, but it detects all dependencies etc correctly then.

I've also tried simply running it in `common/temp` where all pnpm files that are normally in the root are stored, but `knip` hung up (been showing this for hours now). Tried running it in `rush`'s own repo to see if that's something wrong with ours, but there it fails  while reading `.pnpmfile.cjs`
![image](https://github.com/webpro/knip/assets/25051063/a0ec6886-b341-4646-a325-fa98ed063962)
![image](https://github.com/webpro/knip/assets/25051063/4c15a3b8-b6ba-4ed6-b7f3-054fa76cbb5a)

**Comment by webpro** [comment]
That error looks like either `name` is not present in a `package.json` file or syntax like this is used:

```json
{
  "devDependencies": {
    "//": [
      "a comment"
    ]
  }
}
```

As we're deviating from the original topic, I'm going to close this issue (reason: https://github.com/webpro/knip/issues/457#issuecomment-1896984925).

**Comment by Pipo93** [comment]
@Faithfinder can you point to an example project? I'm running into the issue that all workspace dependencies are currently marked as unused.
