### ISSUE TITLE
False positive on `Unused files` for react component with type declaration file

### ISSUE THREAD

**Issue by emschenn** [webpro/knip#458]
When  trying out  Knip on our repo, we encountered a false positive issue where it incorrectly reports unused files when a component have type declaration files.

This problem is reproducible in Knip versions 2, 3, and 4.

- - -

Here is a minimal repro example: https://codesandbox.io/p/sandbox/knip-unused-file-repro-45348l  
* There are two components, `Counter` and `Counter2`, both implemented as class components in JavaScript. 
* The only distinction is that `Counter` has a type declaration file for TypeScript support, while `Counter2` does not. 
* Both 2 components are used in the app; however, Knip erroneously reports the following as unused files:
```
Unused files (2)
src/Counter/Counter.js
src/Counter/index.js
```

We are uncertain if there is a resolution for this issue. Any guidance or assistance is appreciated! 🙏🏼

**Comment by webpro** [comment]
At first sight, that looks a bit like an odd combination of things:

- Let's only consider Knip v4
- Knip requires at least `typescript@5.0.4` (and `@types/node`) (also see https://knip.dev/overview/getting-started#installation)
- The `Counter2/Counter.js` file contains JSX so it would make sense if it has that extension?

When I give only `index.tsx` to resolve the rest it indeed returns the other files:

```
App.tsx
Counter/index.d.ts
Counter2/Counter.js
Counter2/index.js
Hello.tsx
index.tsx
```

When using TypeScript files (i.e. `src/Counter/Counter.tsx` and `src/Counter/index.ts`) all seems fine.

**Comment by webpro** [comment]
As I think Knip behaves as expected, I'm going to close this issue.
