### ISSUE TITLE
ignore pattern for dirs

### ISSUE THREAD

**Issue by fmacherey** [webpro/knip#463]
I updated from `3.12.0` to `4.0.4`. Before it was possible to have directories in `ignore` pattern just as string without wildcard / glob.
```
const config: KnipConfig = {
  ignore: [
    ".next"
  ] 
}
```
These checks are now not passing, and have to be changes to `".next/**"`. I suppose this is a regression, as I could find a clear information in the release notes, that this intend to be a breaking change. 

Thanks for you help :)

**Comment by webpro** [comment]
The related releases notes are here: https://knip.dev/blog/knip-v4#ignore-files

Perhaps you didn't find release notes here: https://github.com/webpro/knip/releases/tag/4.0.0 - I have just added a link there, thanks for reminding me :)

So yeah it's a breaking change indeed and the docs are here: https://knip.dev/reference/configuration#ignore

**Comment by fmacherey** [comment]
Ah thanks for the quick reply and and adjusting the notes :)
