### ISSUE TITLE
Plugin for WebdriverIO ("wdio" / wdio.conf.js)?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro/knip#464]
Coming over from https://github.com/eslint/eslint/pull/18005#discussion_r1458067768: it'd be great to have a built-in plugin for [WebdriverIO](https://webdriver.io). It's a test framework that has a `wdio.conf.js` file & is used by ESLint.

I'd be happy to contribute this. I don't personally use wdio but it'd be a good motivator for me to contribute to Knip. 😄

**Comment by webpro** [comment]
Feel free to work on this! I think it should be quite similar to the Ava, Jest and Mocha plugins.

Looks like the main objectives are the same: getting the entry files right and translate things like `framework: "mocha"` to `@wdio/mocha-framework`.

**Comment by webpro** [comment]
Closing in favor of https://github.com/webpro/knip/issues/483
