### ISSUE TITLE
Add ` "allowTrailingCommas": true` to the schema

### ISSUE THREAD

**Issue by RebeccaStevens** [webpro/knip#468]
This will prevent these sort of issues in vscode:

![image](https://github.com/webpro/knip/assets/7224206/d7c29bf9-977f-4a69-9362-6e5d897456b1)

related: https://github.com/microsoft/vscode/issues/102061

**Comment by webpro** [comment]
Did you see https://knip.dev/reference/configuration#json-schema? You can use the JSONC schema for this :)
