### ISSUE TITLE
Running knip triggers the webpack configuration

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#47]
**Knip version**: 1.7.0

### Bug

Running knip in non-production mode triggers my webpack configuration. Since my config has automatic build mode handling, it fails.

My configuration (`./webpack.config.js`):

```
const dev = require('./webpack.dev.js') // configuration for development build
const prod = require('./webpack.prod.js') // configuration for production build

function getConfig(mode) {
    switch (mode) {
        case 'development':
            return dev(process.env)
        case 'production':
            return prod(process.env)
        default:
            throw new Error(`Trying to use an unknown mode ${mode}`) // unknown command
    }
}

const processModes = {
    start: 'development',
    prod: 'production'
}

module.exports = () => {
    const mode = processModes[process.env.npm_lifecycle_event]
    process.env.NODE_ENV = mode
    return getConfig(mode)
}

```

### How to reproduce
Create a new project, copy this configuration and set a `package.json` script with `"knip": "knip"`.

### Workaround
The only way to handle this would be either to default to `development` or to set `"webpack": false` in `knip.json`. 

I don't think this is the intended way as it flawlessly lints my other files. Is it possible to lint it without triggering my config or should I handle it myself?

**Comment by ElPrudi** [comment]
Since Knip is a development tool, it may be best to default to `development`.

I don't know if I would close it since the problem hasn't really been solved, so I'll leave it open in case you want to go into webpack linting more broadly in the future.  So close it as you see fit. Anyway, it makes sense to note it in the docs in case someone else returns a function instead of an object.
I got the idea from the SurviveJs Webpack book, so I'm sure I won't be the only one returning a function.


Thank your for your answer :)

**Comment by webpro** [comment]
Sorry if I wasn't clear. Knip supports both the config as an object and a function. You are using it as a function, that's why I asked if it would be possible for you to change your function to something like this. Not tested, but you get the idea:

```js
module.exports = (env, argv) => {
    const mode =  env.production ? 'production' : 'development';
    process.env.NODE_ENV = mode;
    return getConfig(argv.mode);
```

Also see https://webpack.js.org/configuration/configuration-types/#exporting-a-function

**Comment by ElPrudi** [comment]
Yes, changing the function according to your recommendation did indeed work. Thanks you!

**Comment by webpro** [comment]
Great, thanks for reporting back.
