### ISSUE TITLE
Files specified in `ts-node` with the option are considered unused files

### ISSUE THREAD

**Issue by fossamagna** [webpro/knip#470]
## 

When an option is given to the `ts-node` called in the `scripts` field, the file specified in the argument will not be included in the entry file.

`package.json`
```
{
  "name": "knip-ts-node-options-example",
  "version": "1.0.0",
  "private": true,
  "description": "The repository to reproduce knip issue on ts-node with options",
  "scripts": {
    "hello": "ts-node -T scripts/hello.ts",
    "knip": "knip"
  },
  "keywords": [
    "knip",
    "ts-node"
  ],
  "author": "fossamagna",
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^20.11.5",
    "knip": "^4.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3"
  }
}
```

When `knip` is executed, `scripts/hello.ts` is judged as unused files as follows.
```
npm run knip 

> knip-ts-node-options-example@1.0.0 knip
> knip

Unused files (1)
scripts/hello.ts
```

If no option is specified for `ts-node`, the file is not considered unused files.　
option so that files specified in `ts-node` are not judged as unused files.

reproduction repository: https://github.com/fossamagna/knip-issue-470

**Comment by webpro** [comment]
Thanks for the report, @fossamagna, should be better now :)
