### ISSUE TITLE
External plugins

### ISSUE THREAD

**Issue by UnderKoen** [webpro/knip#473]
Hey I have been using this tool within our project and have been loving it. We use some tools internally which don't have a plugin within this tool. I would like to use a plugin without using `patch-package`.

In the config something like:
```json
{
	"plugins": ["@internal/plugin"]
}
```

**Comment by webpro** [comment]
For now, only a quick link: https://mastodon.social/@voxpelli/111799328719469735

**Comment by webpro** [comment]
A few questions:

- What is expected from the plugin API? What is used from the code added by `patch-package`? Anything (pseudo/redacted) you could share?
- What tools are not internal and could be added as public plugins to Knip?

**Comment by UnderKoen** [comment]
1. It just updates `plugins/index` for added the plugin.
2. One of the tools is [`@under_koen/bsm`](https://github.com/underkoen/bsm) but it is only really used by our teams so it seems better to maintain with the package than in knip.

**Comment by webpro** [comment]
> 1. It just updates `plugins/index` for added the plugin.

I'm interested in what your plugin is exporting, e.g. only `CONFIG_FILE_PATTERNS` and/or `findDependencies` etc. I'm trying to start investigating what APIs should be exposed for external plugins, etc.

> 2. One of the tools is [`@under_koen/bsm`](https://github.com/underkoen/bsm) but it is only really used by our teams so it seems better to maintain with the package than in knip.

Alright, that makes sense.

**Comment by UnderKoen** [comment]
```ts
export default {
  NAME,
  ENABLERS,
  isEnabled,
  findDependencies,
  CONFIG_FILE_PATTERNS
};
```

**Comment by webpro** [comment]
Closing this due to currently not interested in widening the API surface area.

**Comment by james-nash** [comment]
Just came here to ask for the same thing. I'm using a tool called [Cobalt UI](https://cobalt-ui.pages.dev/) in our monorepo and wanted to write a little plug-in to automatically add its config file as an entry point. I'll try to contribute one when I have a bit of spare time.

However, it would have been helpful to be able to quickly make this locally as my own plugin and use it (for now, I need to work around it via Knip's config, but it's a bit tedious). Being able to do write external plugins might also make it easier for folks like me to test and refine them _before_ contributing back into `knip`.

I totally appreciate that you're not keen to increase the API surface right now. However, I hope supporting external plugins can be re-considered at some point in the future.
