### ISSUE TITLE
False positive unused dependency

### ISSUE THREAD

**Issue by Faithfinder** [webpro/knip#476]
[Repro](https://codesandbox.io/p/devbox/knip-buffer-repro-cmp8fp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrsasof30006356n1g7nu728%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrsasof30002356nsi7dek6r%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrsasof30004356n6vokpb8f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrsasof30005356ngf11sj0n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrsasof30002356nsi7dek6r%2522%253A%257B%2522id%2522%253A%2522clrsasof30002356nsi7dek6r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtcuzg6002e356mckft4e2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtcuzg6002e356mckft4e2v%2522%257D%252C%2522clrsasof30005356ngf11sj0n%2522%253A%257B%2522id%2522%253A%2522clrsasof30005356ngf11sj0n%2522%252C%2522activeTabId%2522%253A%2522clrthmvjj00j7356mekw3hfd3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clrthmvjj00j7356mekw3hfd3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clrsasof30004356n6vokpb8f%2522%253A%257B%2522id%2522%253A%2522clrsasof30004356n6vokpb8f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrsasof30003356n681x71dt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clrtczm7t00tl356mvtwv9daz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrtczm1y0008eege9lqmcrfv%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrsasof30003356n681x71dt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Probably because `buffer` is built into Node, however node types aren't installed, this is a browser package ponyfill

**Comment by webpro** [comment]
Indeed, Knip is using `module.isBuiltin`. You can use `ignoreDependencies` for exceptions like this.

**Comment by Faithfinder** [comment]
Sure, but I wonder if detecting presence of `@types/node` could be a helpful heuristic here?

**Comment by webpro** [comment]
That might work, but sounds like unnecessary complexity, error-prone, for an uncommon situation.

**Comment by Faithfinder** [comment]
"Uncommon" is a relative term. [Quick search](https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29package%5C.json%24%2F+%22%5C%22buffer%5C%22%3A+%5C%22%22&type=code) over github for `buffer` in `package.json` files shows 45 thousand hits, and that's not the only package that would get a false positive like this, and we can't see private repos, obviously.

I guess rather than looking at `@types/node`, if there's explicitly an import of a package that's listed in `package.json`, it either shouldn't be flagged at all, or go into some kind of "Ambiguous" category? Ignoring is possible, of course.

**Comment by webpro** [comment]
With "uncommon" I meant Node.js built-in modules that are also available as a module in the npm registry under the same name (but this claim is not backed by any numbers).

It's ambiguous indeed, not sure what's the best way to go about this yet. The generic solution to do the same for all built-ins also listed is debatable, since I think Knip should report modules like `"path"`:

```
❯ last-publish path
The last publish date of path is 9/13/2015
```

An array of built-ins that are also commonly used packages could work, but looks like even buffer is "fixing itself":

```
❯ last-publish buffer
The last publish date of buffer is 11/23/2020
```

**Comment by webpro** [comment]
Going to close this one. Knip could fix it, but tbh I like the fact that it raises it as an issue, makes you think (e.g. in Node.js you may not want the package but the built-in), and if necessary can be configured as an exception (in `ignoreDependencies`). Over time, this problem will fade anyway.
