### ISSUE TITLE
Knip detects a script parameter as a package dependency

### ISSUE THREAD

**Issue by Faithfinder** [webpro/knip#477]
All it the title.
[Repro](https://codesandbox.io/p/devbox/dep-detection-repro-3p6c7n?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrsasof30006356n1g7nu728%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrsasof30002356nsi7dek6r%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrsasof30004356n6vokpb8f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrsasof30005356ngf11sj0n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrsasof30002356nsi7dek6r%2522%253A%257B%2522id%2522%253A%2522clrsasof30002356nsi7dek6r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtcuzg6002e356mckft4e2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtcuzg6002e356mckft4e2v%2522%257D%252C%2522clrsasof30005356ngf11sj0n%2522%253A%257B%2522id%2522%253A%2522clrsasof30005356ngf11sj0n%2522%252C%2522activeTabId%2522%253A%2522clrtsnr9301ad356mqsj0vojo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clrtsnr9301ad356mqsj0vojo%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clrsasof30004356n6vokpb8f%2522%253A%257B%2522id%2522%253A%2522clrsasof30004356n6vokpb8f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrsasof30003356n681x71dt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clrtczm7t00tl356mvtwv9daz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrtczm1y0008eege9lqmcrfv%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrsasof30003356n681x71dt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by voxpelli** [comment]
`deploy` is claimed to be missing? This is correct I believe, it's an unspecified dependency. If it's something provided externally on your system then you need to tell knip that you have made sure it's available where it's needed, because knip can't know?

**Comment by Faithfinder** [comment]
> `deploy` is claimed to be missing? This is correct I believe, it's an unspecified dependency. If it's something provided externally on your system then you need to tell knip that you have made sure it's available where it's needed, because knip can't know?

I implore you to actually run `knip` on the repro ;)
![Screenshot_20240126-074843](https://github.com/webpro/knip/assets/25051063/fa0ec765-dcb5-452b-9617-deaf4c77b08f)

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v4.2.2. See [Release 4.2.2](https://github.com/webpro/knip/releases/tag/4.2.2) for release notes._

**Comment by webpro** [comment]
Bit of an edge case situation, but should be fixed!

**Comment by Faithfinder** [comment]
Eh, looking at the fix code, I'm not sure this does it. I've used `deploy` as name in the minimal repro, but that's not a real binary (I had to put it in `ignoredBinaries` so that repro focueses on correct thing). In reality it's an in-house binary that's called `welbi-deploy`, and `-r` stands for `repository` (ECR). I'm fairly certain there's a billion binaries out there that have their own meaning for `-r`. I think the list you want to maintain should be inclusive (`node`, `ts-node`, `jest` etc), rather than exclusions.

If your experience says that `-r` stand for `require` fairly universally, fair enough, but I'd add this special case to the docs. If it was there I would update scripts to use full parameter name, rather than add repo name to `ignoreDependencies`

**Comment by webpro** [comment]
The reason I mentioned it's an edge case, is because it's not that common to use a binary in `package.json#scripts` that didn't come with a dependency also listed in the same file.

Knip makes a difference between these scripts and, for instance, binaries in GitHub Actions files, which is totally different context.

I'm definitely not stating that `--require` is a universal thing. I think it's just fairly common within the npm ecosystem, within `package.json#scripts`, and only as far as I've seen myself. So within this context I once decided to use this as a default and I still think Knip is on the right side here. Always happy to adjust, though.

The obvious downside and, indeed, a very ugly part of Knip here is that if..

1) a binary is used that's not part of a listed dependency, AND
2) it's using `-r`, `--require` and/or `--loader` argument, AND
3) with a value that's not a local entry file or a dependency

..then it's reported as an unlisted dependency.

So either Knip makes a whitelist or a blacklist for this, and I'm still on the fence with it.  It's hard to justify hard-coding `welbi-deploy` in Knip's codebase, that's for sure.

**Comment by Faithfinder** [comment]
The binary in my case is a listed dependency. It's internal to the monorepo, but it's in `package.json` (well, the package name is `@welbi/deploy-scripts`, `welbi-deploy` is the binary name). In a rush repo you don't get random things floating around, everything is listed :)

I for sure am not asking for a hardcode of `welbi-deploy`, or just `deploy` for that matter, I guess I should have made my example say `aBinary` :)

And I guess I do agree that people don't often write their own binaries, though they sorta should, it's nice :)

Still, IMO allowlist is a better pattern, because I've only seen `require` in `node` and wrappers around node, like `ts-node`.

Regardless, I think doc updates are in order. Regardless of allow or block list, this is "magical" behaviour and should be documented. Here's a PR: https://github.com/webpro/knip/pull/484
