### ISSUE TITLE
Automatically pick up knip.mjs and knip.cjs

### ISSUE THREAD

**Issue by fregante** [webpro/knip#478]
https://knip.dev/overview/configuration#location

Could you add these two extensions to the list of files knip automatically looks for? So I don't have to add `--config knip.mjs`

### Reasoning

My app doesn't use type=module, but my webpack config does (.mjs), which means that knip also has to be loaded as a module.

https://github.com/pixiebrix/pixiebrix-extension/blob/951da774d2ecb296f381b3b6cda128be790fac3f/knip.mjs#L1

**Comment by webpro** [comment]
Sorry, I'd rather make that list smaller than bigger. Hopefully the ecosystem can agree on some conventions and we'll move on from CJS to ESM too.

I could even imagine supporting only JSON, since compilers might become a solved problem.

Let's see where this goes. I'm not against the idea per se, but not at this time.

**Comment by fregante** [comment]
> Hopefully the ecosystem can agree on some conventions and we'll move on from CJS to ESM too.

What convention? Those two extensions are here to stay and will never not be used. There are a lot of people who are unable/unwilling to switch to ESM, or are in these partial states because of other tools that don't support ESM.

> since compilers might become a solved problem.

A solved problem in knip or in development? Because webpack is not going anywhere anytime soon either.

**Comment by fregante** [comment]
How will knip read the entry points from webpack's config without importing webpack's config? Would I have to repeat them and hope they will not get out of sync?

**Comment by webpro** [comment]
OK I think I see we're the confusion stems from. Let's break it down:

- The initial request is about the Knip configuration file (e.g. `knip.json` or `knip.ts`).
- The Webpack configuration file (e.g. `webpack.config.ts`) is handled by Knip's Webpack plugin, which should automatically result in those `config.entry` files being added as entry files to Knip.

Sorry, I didn't dive into the links you've sent and explain immediately. You shouldn't need to do any of this: https://github.com/pixiebrix/pixiebrix-extension/blob/951da774d2ecb296f381b3b6cda128be790fac3f/knip.mjs#L3-L14

Knowing this, if anything isn't working as expected, please file an issue :)

**Comment by fregante** [comment]
The file is executed, I see the console.logs within it, but its entries don't appear in Knip's debug output. Does knip support config factories?

https://webpack.js.org/configuration/configuration-types/#exporting-a-function
