### ISSUE TITLE
'playwright-ct' is missing in `KnipConfig` type

### ISSUE THREAD

**Issue by romansp** [webpro/knip#487]
Pretty much self-explanatory. Plugin was added here https://github.com/webpro/knip/pull/262 but `playwright-ct` entry is missing. https://github.com/webpro/knip/blob/f2173a490689636a4ddcc93765f8244f572989bd/packages/knip/src/ConfigurationValidator.ts#L107-L109

Just TypeScript error. Plugin still works as expected though.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v4.3.0. See [Release 4.3.0](https://github.com/webpro/knip/releases/tag/4.3.0) for release notes._
