### ISSUE TITLE
False positive for "Unlisted binaries" with pnpm

### ISSUE THREAD

**Issue by danvk** [webpro/knip#491]
I got a false positive for "Unlisted binaries" when one "script" in `package.json` was run from another one via `pnpm <script>` rather than `pnpm run <script>`.

My setup looks something like this:

```json
{
  "scripts": {
    "repl": "pnpm run:ts src/index.ts",
    "run:ts": "node --loader ts-node/esm --no-warnings",
    "benchmark": "pnpm --silent repl bench/fib33.lox",
  }
}
```

I get the following error from knip:

    Unlisted binaries (1)
    bench/fib33.lox  package.json

Applying this diff fixes the error:

```
-    "benchmark": "pnpm --silent repl bench/fib33.lox",
+    "benchmark": "pnpm --silent run repl bench/fib33.lox",
```

It's odd that knip thinks that `bench/fib33.lox` is a binary. pnpm doesn't require scripts to be run via `pnpm run`, so this pattern should be supported by knip.

Here's the commit where I "fixed" the false positive by adding "run":
https://github.com/danvk/gravlax/pull/37/commits/ae27cb97038eb8b9ac7265c05319379817738285

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v4.3.1. See [Release 4.3.1](https://github.com/webpro/knip/releases/tag/4.3.1) for release notes._

**Comment by webpro** [comment]
> It's odd that knip thinks that `bench/fib33.lox` is a binary. pnpm doesn't require scripts to be run via `pnpm run`, so this pattern should be supported by knip.

I understand the reasoning, but I'd like to add that Knip does not include/use pnpm itself so eventually it's all just simulation and heuristics. The issue in this case was that `--silent` is a boolean flag and that was not part of the show yet.

**Comment by danvk** [comment]
Thanks for the quick fix @webpro! 💯
