### ISSUE TITLE
Add support for unused (never set) properties in interfaces / inline types

### ISSUE THREAD

**Issue by phiresky** [webpro/knip#499]
I'm not sure what exactly the scope would be, but here's some example code:

```tsx
export function ReactComponent(props: {
  x: number;
  foo?: string;
  bar?: string;
}) {
  return <div>
    {props.x}
    {props.foo ? <SomeFooComponent />: null}
    {props.bar ? <SomeBarComponent />: null}
    </div>;
}
```

Now this code looks fine, but imagine at all the call sites of this function, the `foo` and `bar` parameters are never actually set. Then this component has guaranteed dead code which might mean that the whole SomeFooComponent / SomeBarComponent can also be completely removed from the code base.

Typescript can already identify these with the `find all references` action targeting each of the properties, so it should be possible to build.

**Comment by webpro** [comment]
I've moved away from `findReferences` (except for class members), but any sort of `prop.access` could potentially be added, same for type and interface member usage.

Could you please give some usage examples? If it's JSX it might be different story.

**Comment by webpro** [comment]
Closing this, not in scope for Knip currently
