### ISSUE TITLE
Reason: Cannot find module '@/app/lib/env'

### ISSUE THREAD

**Issue by deadcoder0904** [webpro/knip#515]
I have a `drizzle.config.ts` file on top-level that imports `@/app/lib/env` like this.

#### drizzle.config.ts

```ts
// import * as dotenv from "dotenv"
import type { Config } from "drizzle-kit"
import { isDevelopment, isLinux } from "std-env"

import { env } from "@/app/lib/env"

// dotenv.config({ path: ".env.development" })
const DATABASE_EXTENSION = isDevelopment ? "dev" : "prod"
const DATABASE_PATH = `${env.DATABASE_NAME}.${DATABASE_EXTENSION}.sqlite`
const FINAL_DATABASE_PATH = isLinux ? `/app/${DATABASE_PATH}` : DATABASE_PATH

export default {
	schema: "./src/app/db/schema.ts",
	out: "./src/app/db/migrations",
	driver: "better-sqlite",
	dbCredentials: {
		url: FINAL_DATABASE_PATH,
	},
	verbose: true,
} satisfies Config
```

And my tsconfig paths also include it.

#### tsconfig.json

```json
{
	"compilerOptions": {
		"target": "ESNext",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "ESNext",
		"moduleResolution": "Bundler",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"incremental": true,
		"plugins": [
			{
				"name": "next"
			}
		],
		"paths": {
			"@/*": ["./src/*"]
		}
	},
	"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "src/seed/insert.ts"],
	"exclude": ["node_modules"]
}
```

But when I ran `knip`, I got this error:

```bash
> knip

Analyzing workspace ....
Error loading E:/Code/mysite.com/drizzle.config.ts
Reason: Cannot find module '@/app/lib/env'
Require stack:
- E:\Code\mysite.com\drizzle.config.ts
 ELIFECYCLE  Command failed with exit code 2.
```

I'm using this version of `knip`:

> 		"knip": "^5.0.1",

What's the issue?

**Comment by webpro** [comment]
I'm afraid jiti (dependency to load such files) does not use the TS config, or does not support such path aliases. Not much Knip can do here unfortunately, other than recommending to work around it and not use aliases in such config files.

**Comment by deadcoder0904** [comment]
should i open an issue on jiti or its not possible to support it at all?

**Comment by deadcoder0904** [comment]
found the issue: https://github.com/unjs/jiti/issues/166

**Comment by deadcoder0904** [comment]
lmk if i should keep it open to avoid duplicates?

**Comment by webpro** [comment]
I think we should add it to https://knip.dev/reference/known-issues so let's keep this one open until either one's done :)

**Comment by deadcoder0904** [comment]
it looks like they support it, no?

see https://github.com/unjs/jiti/issues/209

**Comment by webpro** [comment]
Right, feel free to give it a shot

**Comment by webpro** [comment]
Knip v5.1 introduces a new potential workaround: `bunx --bun knip`

**Comment by webpro** [comment]
Closing this by https://knip.dev/reference/known-issues#path-aliases-in-config-files and https://github.com/webpro/knip/issues/565

**Comment by chadxz** [comment]
@webpro I don't think upgrading Jiti to v2 addressed this. I'm still encountering this error when loading the drizzle config file and that config contains an import using a typescript path alias. I imagine you know this based on the current "known-issues" but I'm wondering if you'd want to reopen this issue to track the problem? blocked me for a few hours as a first-time user of knip :( I think for now I'm going to try removing the drizzle plugin.

**Comment by webpro** [comment]
@chadxz Sorry to hear this. You're right, jiti v2 doesn't address this and neither does `knip.json#paths`, since jiti isn't using that. The only thing that actually works is to use Bun: https://knip.dev/reference/cli#knip-bun. Feel free to open an issue, maybe there's a way to pass on the path aliases to jiti everywhere properly.

**Comment by chadxz** [comment]
Thanks, I just decided to throw in the towel on this line of investigation and go a different way. Best wishes
