### ISSUE TITLE
Workspace inheritance

### ISSUE THREAD

**Issue by patricklafrance** [webpro/knip#516]
In some cases, it would be useful if a workspace could inherit from a parent workspace.

For example, if I have:

```
{
    workspaces: { 
         "packages/*": {
              eslint: true
         },
         "packages/toto": {
               ignore: ["foo.ts"]
         }
    }
}
```

I would expect `packages/toto` to inherit the `eslint: true` configuration from `packages/*`.

I understand thought that this kind of behavior can lead to unwanted inheritance, but it is something that I was expecting to work so I am throwing the idea out there in case it resonates.

Thanks,

Patrick

**Comment by webpro** [comment]
This could indeed lead to unexpected/undesired results. That's why I'm going to close this issue.

This should work as expected, though:

```js
{
     eslint: true
     workspaces: { 
         "packages/toto": {
               ignore: ["foo.ts"]
         }
    }
}
```
