### ISSUE TITLE
How to filter issues for a given sub-directory?

### ISSUE THREAD

**Issue by angrybacon** [webpro/knip#518]
I've been trying to use the existing options to filter out issues for a large codebase that is split amongst codeowners and their respective directories. For context, this is a Next.js project.

What I tried:

- `npx knip | grep 'path/to/domain'`  
  Doesn't seem to be useable as it looks like the output is split and some of the issues will be skipped. I initially thought `--no-progress` would prevent this but it didn't help
- `npx knip --workspace 'path/to/domain'`  
  As expected, this leads to false positives &mdash; for my use case &mdash; due to symbols within the specified domain being used outside of the domain

What is the recommended way for users to filter issues that are only relevant for a given directory within the codebase?

**Comment by webpro** [comment]
```
npx knip | grep 'path/to/domain'
```

When piping like this the `-n` flag is not needed anymore. Also, would not recommend to filter report this way as not everything necessarily contains that path.

```
knip --workspace 'path/to/workspace'
```

This _should_ work properly, it includes dependent and parent workspaces.

Some other options include:

- See the various reporters, e.g. use the JSON reporter and take it from there
- Use custom preprocessor and/or reporter (also see implementation of existing ones for inspiration)

https://knip.dev/features/reporters

**Comment by angrybacon** [comment]
> When piping like this the -n flag is not needed anymore

Good to know thanks 🙏 

> Also, would not recommend to filter report this way as not everything necessarily contains that path.

In my case filtering by path is good enough since each code owner would then be responsible for their respective path(s). For posterity, the workaround would be to first output to a file but that's very practical. I suppose one can try `stdbuf -o0` too perhaps

> This should work properly, it includes dependent and parent workspaces.

With a bit more time, I'll try to make a reproduction setup and see what I missed then. I'll also look into custom reporters thanks for the pointers 👍
