### ISSUE TITLE
Knip can not find webpack-plugins while recursively linting webpack configurations

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#52]
**Knip version**: 1.8.0

Knip does not check whether the returned webpack configuration has been merged with another configuration via `webpack-merge` or a function type configuration.

For example, Knip says that `webpack-merge`, `esbuild` and `esbuild-loader` are not used, even though they are defined and merged with another configuration from

`webpack.common.js`
```
const esbuild = require('esbuild')

module.exports = (env) => {
    module: {
        rules: [
           {
                    test: /(\.js)x|\.js$/,
                    loader: 'esbuild-loader',
                    include: srcPath,
                    exclude: /node_modules/,
                    options: {
                        target: 'es2015',
                        tsConfigRaw: require('./tsconfig.json'),
                        implementation: esbuild
                    }
                },
        ]
   }               
}
```
`webpack.dev.js`
```
const { merge } = require('webpack-merge')
const common = require('./webpack.common.js')

module.exports = (env) => merge(common(env), {
    mode: 'development'
}
```
`webpack.config.js`
```
const dev = require('./webpack.dev.js')

module.exports = (env, argv) => {
     return env.production ? dev(process.env) : throw new Error('Unsupported mode)
}
```
Results after running `knip`:
```
Unused dev dependencies (3)
esbuild                               package.json
esbuild-loader                        package.json
webpack-merge                         package.json
```

**Comment by webpro** [comment]
Knip should handle this properly. Note that Knip swallows some errors when not using `--debug` or `--no-progress`. This might be unexpected. It's hard to draw a line which errors should be suppressed or not, there's definitely room for improvement here.

Could you please try with `--debug` and see what errors you get?

**Comment by ElPrudi** [comment]
Ok, going through the debug messages I found that yes, it does recursively look, but it can't find everything I have. From my webpack-dependencies it can only find most of the loaders, but none of the plugins.
```
[knip] Included entry files (10)
[
 ...
  '<root>/webpack.config.js' // it finds the entry config
]
[knip] Included files resolved from entry files (57)
[
   ...
  '<root>/webpack.common.js',
  '<root>/webpack.config.js',
  '<root>/webpack.dev.js',
  '<root>/webpack.prod.js'  // it finds the modes
]
```
So yes, it handles it, but it can't find everything.

**Comment by ElPrudi** [comment]
From these webpack plugins used in this path:
```
babel-loader
ts-loader
esbuild-loader
esbuild
MiniCssExtractPlugin.loader
css-loader
less-loader
base64-inline-loader
Dotenv()
ForkTsCheckerWebpackPlugin
MiniCssExtractPlugin
CaseSensitivePathsWebpackPlugin
CleanWebpackPlugin
ExtraWatchWebpackPlugin
CssMinimizerPlugin
JsonMinimizerPlugin
HtmlMinimizerPlugin
EslintPlugin
PowerBICustomVisualsWebpackPlugin
CircularDependencyPlugin
```
it can only find
```
[knip] Dependencies used by Webpack configuration (8)
[
  '<root>\\node_modules\\mini-css-extract-plugin\\dist\\loader.js',
  'babel-loader',
  'base64-inline-loader',
  'css-loader',
  'less-loader',
  'ts-loader',
  'webpack-cli',
  'webpack-dev-server'
]
```

**Comment by webpro** [comment]
Any chance you could share the configuration file(s) here? This would tremendously to improve Knip :)

**Comment by ElPrudi** [comment]
Here is my full configuration. Hopefully I have set up the visibility correctly.
https://pastebin.com/Ym7vMkJm
There are 4 files, I put the full file name above each. Just mock some files if you get errors.

**Comment by webpro** [comment]
The dependencies listed with "Dependencies used by Webpack configuration (8)" are found by the custom resolver for strings like `loader: 'ts-loader'` which are very specific and custom to Webpack. This happens in the Knip webpack plugin.

The rest of the dependencies (imported like `require('mini-css-extract-plugin')`) are generic JS/TS and should be caught using "regular" dependency resolving. This happens later in the process.

So it's like a two-pass process. The debug message should be more clear about this, though.

Are there false positives (unused or unlisted dependencies) related to Webpack in the end report?

**Comment by ElPrudi** [comment]
This is actually the last dependency resolver process in the debug message.
List of found unused dev dependencies:
```
Unused dev dependencies (29)
@babel/runtime                        package.json
@babel/runtime-corejs3                package.json
@commitlint/cli                       package.json
@commitlint/config-conventional       package.json
@microsoft/tsdoc                      package.json
@microsoft/tsdoc-config               package.json
@typescript-eslint/typescript-estree  package.json
case-sensitive-paths-webpack-plugin   package.json
circular-dependency-plugin            package.json
clean-webpack-plugin                  package.json
css-minimizer-webpack-plugin          package.json
dotenv                                package.json
dotenv-webpack                        package.json
editorconfig                          package.json
esbuild                               package.json
esbuild-loader                        package.json
eslint-config-standard                package.json
eslint-import-resolver-webpack        package.json
eslint-plugin-babel                   package.json
eslint-webpack-plugin                 package.json
extra-watch-webpack-plugin            package.json
fork-ts-checker-webpack-plugin        package.json
html-minimizer-webpack-plugin         package.json
json-minimizer-webpack-plugin         package.json
mini-css-extract-plugin               package.json
powerbi-visuals-webpack-plugin        package.json
terser-webpack-plugin                 package.json
webpack-bundle-analyzer               package.json
webpack-merge                         package.json
```

**Comment by webpro** [comment]
[v1.10.0](https://github.com/webpro/knip/releases/tag/1.10.0) should improve things. Although I wonder why it does not seem to resolve regular `require()` in your project. In my testing (and as [part of the tests](https://github.com/webpro/knip/tree/main/test/fixtures/plugins/webpack)) this works fine. Any chance you could try again with v1.10.0 and see the report output?

**Comment by webpro** [comment]
By the way, there was a typo `env.prodution` in the shared files, this affects results as it would find only development config in both passes.

**Comment by ElPrudi** [comment]
Thanks for pointing it out. :)

Yes, now finds all webpack plugins. Thank you!

**Comment by webpro** [comment]
Thanks for your help and confirmation @ElPrudi, this is exactly the idea of Knip development: getting less and less false positives (by improving the plugins).

**Comment by ElPrudi** [comment]
Ok, I have to reopen it, because I wrongly assumed it has been fixed due to my wrong `knip.json` config.
`knip.json`
```json
{
	"$schema": "https://unpkg.com/knip@1/schema.json",
	"webpack": {
		"config": ["webpack.config*.js"]
	},
	"workspaces": {
		".": {
			"entry": "src/visual.ts",
			"project": "src/**/*.ts"
		},
		"packages/*": {
			"entry": "index.{js,ts}",
			"project": "**/*.ts"
		}
	}
}
```
For some reason I can't find the regular dependency resolution process in the debug message. Maybe there is a difference for knip because the main project is running in the frontend browser view while webpack is running in the backend view, therefore it can't get the `require()`?
Anyways, here is my debug output up until the unused dependencies:
https://pastebin.com/h4mPWnt5

**Comment by webpro** [comment]
The dependencies of regular source code is not listed separately in debug output.

Afraid I can't help if I don't have access to something I can run and debug.

Not sure if it's helpful at all, but this webpack fixture directory is part of the test suite and seems to work fine: https://github.com/webpro/knip/tree/main/test/fixtures/plugins/webpack

**Comment by ElPrudi** [comment]
What if you try using an typescript entry file that uses the module `export` `import` syntax?

Because that's the only difference between my case and your test. My theory is that knip checks the module type for the entry file and uses it throughout the whole project, inculding the webpack files, and therefore doesn't read the `require` statements, because those two syntaxes are for different module types.

This could also be the reason why you were initially confused that knip did not read the require statements in my project.

**Comment by webpro** [comment]
Yeah that makes sense, but Knip (partnering up with ts-morph tbh) are pretty flexible in this regard. Just tried a few things and that seems not to be the case, but can't be sure without the actual thing.

**Comment by ElPrudi** [comment]
Perhaps making the `--debug` options more detailed, or issuing warnings and errors, and making the search more rigorous would benefit the search to force a better work environment in which its used just like eslint does with its warnings and errors.

**Comment by ElPrudi** [comment]
Unfortunately, no. I think Knip has problems with the monorepo structure as a whole. Knip only fetches the packages from the root `package.json`, ignoring the dependencies of the subpackages `package.json`s. Since I plan to deploy each subpackage to npm, I guess I need to restructure my package locations for knip or not run knip as a monorepo.

I can now say that it is not a problem with the webpack parser, but rather with the monorepo parser.

**Comment by ElPrudi** [comment]
Ok, after testing around in another project, the problem still exists. I don't know if my configuration is just bad or something else, but I don't actually care about webpack anymore since I'm currently switching to esbuild, so let's pretend this problem doesn't exist.

I'll leave this issue open if anyone else has a problem with the webpack parser.

**Comment by webpro** [comment]
> Unfortunately, no. I think Knip has problems with the monorepo structure as a whole. Knip only fetches the packages from the root `package.json`, ignoring the dependencies of the subpackages `package.json`s. Since I plan to deploy each subpackage to npm, I guess I need to restructure my package locations for knip or not run knip as a monorepo.

Knip v2 uses `package.json#workspaces` and analyzes all of them by default, plus extra directories with `package.json` if added to `workspaces` in `knip.json`. This is now also at https://github.com/webpro/knip#workspaces-monorepos.

> I can now say that it is not a problem with the webpack parser, but rather with the monorepo parser.

Without a reproducible case it's hard to decipher potential issues. The original issue seems not relevant anymore, so I'm going to close this issue. If you (or anyone) else has issue, feel free to open a new issue.
