### ISSUE TITLE
webpack require.context support

### ISSUE THREAD

**Issue by 999946** [webpro/knip#520]
https://webpack.js.org/guides/dependency-management/#requirecontext

The webpack 'require.context' is widely used in front-end engineering, and it's expected that Knip can also analyze this behavior.

**Comment by webpro** [comment]
What's the issue you're facing with Knip? What output do you see?

**Comment by 999946** [comment]
@webpro I have the following code in my project.
```
const requireContext = require.context('./js', true, /^.+\.js$/);

requireContext('./test-a.js').default()
requireContext('./test-b.js').default()
```
knip result
```
Unused files (2)
src/test/js/test-a.js
src/test/js/test-b.js
```
these two files should not appear in the list of unused files.

**Comment by webpro** [comment]
Knip does currently not support anything else than native `import()`, `require()` or `require.resolve()` calls. What you're expecting here is pretty custom and specific to Webpack.

It could be an interesting feature, but we're not there yet.
