### ISSUE TITLE
Jest plugin not picking up test environment requirement.

### ISSUE THREAD

**Issue by atrofimov-sc** [webpro/knip#523]
On knip 5.0.1

package.json:

```
  "devDependencies": {
    "jest-environment-jsdom": "^29.7.0",
    "jest": "^29.7.0",
    "@testing-library/react": "^14.2.1"
  }
```

jest.config.ts

```
import type { Config } from 'jest';

const config: Config = {
  preset: '<rootDir>/../../config',
  testEnvironment: 'jest-environment-jsdom',
};

export default config;
```

Knip config:

```
const config: KnipConfig = {
  rules: {
    files: 'off', // Not useful.
    exports: 'off', // Libs are all public. Don't want to add @public to every export.
    types: 'off', // Same as exports.
    enumMembers: 'off', // Same as exports.
    binaries: 'off', // Complains about all binaries as unused. Tisk.
    unresolved: 'off', // Already checked by typescript. Complains about config files. Tisk.
  },
  ignoreExportsUsedInFile: true,
  ignore: ['dist/**', 'types/**'],
  workspaces: {
    '.': {
      // Do not lint root (yet).
      ignore: ['*', 'js/config/*'],
    },
    'js/libs/*': {
      entry: 'src/{index,cli}.{js,ts,tsx}',
    },
  },
};

export default config;
```

But when I run knip, I get:

```
Unused devDependencies (3)
jest-environment-jsdom  js/libs/some/package.json  
```

## What I expect to happen

Is for it to see that I've got `jest` in the deps, and use the plugin, use the default rule to find `jest.config.ts` and evaluate it by looking at `testEnvironment`, see that there's a require for `jest-environment-jsdom`.

## What happens

knip complains that the dependency is unused.

## What I tried

Tried messing w/ the `jest` config in kniprc. No help.
Tried running with `-d` but saw nothing about `jest` in the debug output at all.

**Comment by webpro** [comment]
- Using `'jest'` instead of `'jest-environment-jsdom'` could help for now.
- Maybe you want to [fix it](https://github.com/webpro/knip/blob/862be7baf40dbf50b8825c7b1124a997e19deea8/packages/knip/src/plugins/jest/index.ts#L52)? 
- If you see nothing Jest related in `--debug` then the plugin might not be enabled at all. It's enabled when the `jest` dependency is listed in `package.json`

**Comment by atrofimov-sc** [comment]
I can confirm that using `jsdom` instead of `jest-environment-jsdom` does work.

**Comment by webpro** [comment]
Thanks! Let's leave it at this then.
