### ISSUE TITLE
Support for ESLint Flat config

### ISSUE THREAD

**Issue by sazzer** [webpro/knip#524]
ESLint is introducing a [new "flat" configuration format](https://eslint.org/docs/latest/use/configure/configuration-files-new). This is feature complete but you still need to opt in to it.

I've just updated my project to use this, and Knip is now listing 1 unused file and 17 unused dependencies where it wasn't before because it doesn't understand that these are actually used by Eslint now:
```
-> % npx knip
Unused files (1)
eslint.config.mjs
Unused devDependencies (17)
@typescript-eslint/eslint-plugin   package.json
@typescript-eslint/parser          package.json
eslint                             package.json
eslint-config-prettier             package.json
eslint-formatter-mo                package.json
eslint-plugin-jest                 package.json
eslint-plugin-jest-extended        package.json
eslint-plugin-jest-formatting      package.json
eslint-plugin-no-secrets           package.json
eslint-plugin-perfectionist        package.json
eslint-plugin-pii                  package.json
eslint-plugin-prettier             package.json
eslint-plugin-security             package.json
eslint-plugin-unicorn              package.json
eslint-plugin-write-good-comments  package.json
globals                            package.json
prettier                           package.json
```

I can fix this by manually adding my `eslint.config.mjs` file to the `entry` array in my Knip config, but it would be good if I didn't need to do this:
```
import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: ['src/index.ts', 'eslint.config.mjs']
};

export default config;
```

Cheers

**Comment by webpro** [comment]
Flat configs are supported in Knip, but the `.mjs` extension is missing:

- https://github.com/webpro/knip/blob/main/packages/knip/src/plugins/eslint/index.ts#L25
- https://github.com/webpro/knip/blob/main/packages/knip/src/plugins/eslint/index.ts#L36

You're up for a fix and a PR? :)

**Comment by sazzer** [comment]
> Flat configs are supported in Knip, but the `.mjs` extension is missing:
> 
>     * https://github.com/webpro/knip/blob/main/packages/knip/src/plugins/eslint/index.ts#L25
> 
>     * https://github.com/webpro/knip/blob/main/packages/knip/src/plugins/eslint/index.ts#L36
> 
> 
> You're up for a fix and a PR? :)

https://github.com/webpro/knip/pull/525 :)
