### ISSUE TITLE
Why Knip emits error on GitHub action workflow, but not locally?

### ISSUE THREAD

**Issue by tal-rofe** [webpro/knip#526]
I have the following project: https://github.com/tal-rofe/url-shortener

I have this pull request fails because of Knip:
https://github.com/tal-rofe/url-shortener/actions/runs/8032520872/job/21942009096

**Error**:
```
4s
Run pnpm knip
  pnpm knip
  shell: /usr/bin/bash -e {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin

> url-shortener@1.0.0 knip /home/runner/work/url-shortener/url-shortener
> knip -c ./knip.json -t ./tsconfig.json

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
Unused devDependencies (1)
@commitlint/cli  package.json
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

The workflow for this job is here: https://github.com/tal-rofe/url-shortener/blob/main/.github/workflows/integrate.yaml#L56

when I run the same command locally:

```bash
git clone https://github.com/tal-rofe/url-shortener.git
pnpm i
pnpm knip
```

I get no errors.

Why?

**Comment by webpro** [comment]
> Why Knip emits error on GitHub action workflow, but not locally on same environment?

I don't know. It's not the same environment. So you'd need to figure out the differences.

Might have something to do with Git settings or "hidden" directories, I'd say here's the starting point: https://github.com/tal-rofe/url-shortener/blob/8b85d9774444466497afec184c26cb04acbdbb34/.husky/commit-msg#L4

**Comment by webpro** [comment]
Maybe Husky installs Git hooks in one env but not the other.

**Comment by tal-rofe** [comment]
> Maybe Husky installs Git hooks in one env but not the other.

That's true, from `package.json` file:
```
"prepare": "is-ci || run-p husky:install git:config",
```

So I could do, in `knip.json` file,
```
"ignoreDependencies": ["commitizen", "@commlitlint/cli"],
```

But then I'd get this warning:
```
> knip -c ./knip.json -t ./tsconfig.json

Analyzing workspace apps/web...
Configuration issues (1)
Unused item in ignoreDependencies: @commitlint/cli
✂️  Excellent, Knip found no issues.
```

It is better, but any better solution?

**Comment by webpro** [comment]
That's up to you. You could create a different Knip config for CI.

Local:

```
knip
```

In CI:

```
knip -c knip-with-ignored-@commlitlint/cli.json
```

**Comment by tal-rofe** [comment]
@webpro 

Thank you
