### ISSUE TITLE
Changing default "entry" when using workspaces

### ISSUE THREAD

**Issue by tomdee** [webpro/knip#528]
I have a project with a slightly different entry format from the default
```
{
  "entry": [
    "{index,main,cli}.{js,cjs,mjs,jsx,ts,cts,mts,tsx}",
    "src/{index,main,cli}.{js,cjs,mjs,jsx,ts,cts,mts,tsx}"
  ],
  "project": ["**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}"]
}
```

But what I have is `index-[SERVICE-NAME].ts`

I have a monorepo with a number of workspaces. I can't figure out how to change the default entries
I've looked at https://knip.dev/features/monorepos-and-workspaces

I don't think I can just put a `*` entry - because the entries won't be merged with other workspace specific entries that I need merged.
I don't think I can just add it to the `.` entry - since it doesn't propagate
And I can't just add a top-level `entry` object has that doesn't get shared with workspace.

Am I missing something here? Is this a bug? Or is it a feature request? 😄 I'm not sure.

**Comment by webpro** [comment]
Indeed, when it comes to the `entry` option it won't be merged across workspaces. ([Other top level options](https://knip.dev/features/monorepos-and-workspaces#additional-options) and [plugins](https://knip.dev/reference/configuration#plugins) can be configured and will be propagated to workspaces.)

Wildcards in workspace names are supported:

```json
{
  "workspaces": {
    "packages/*": {
      "entry": ["index-[SERVICE-NAME].ts"]
    }
  }
}
```

Not sure exactly what the desired end result should be in terms of configuration, but if that's not enough, you can [use TypeScript in a dynamic configuration](https://knip.dev/reference/dynamic-configuration) and assemble any configuration object.

**Comment by webpro** [comment]
Closing, I think the answer is appropriate.
