### ISSUE TITLE
Feature: Display summary at the end of the script

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#53]
**Knip version**: 1.8.0

For someone like me who is new to writing libraries and Apis, I easily get over 200 - 400 things found. It would be great to have a proper result message that shows the final results of the things found (like the listing that is done while processing the files).

On another project I got a error message at the end that said:

```
ELIFECYCLE exited with code <sum of found things>
```

**Comment by webpro** [comment]
Each issue type has it's own count. They're different types of issues, not sure if it makes sense to have them always printed. Maybe as an option. In any case, Knip exits with a code that's the number you'd like to see so you could do something like this:

```
knip || echo "Total issues found: $?"
```

**Comment by ElPrudi** [comment]
This sadly doesn't work as a npm script.

I was thinking of an out of the box message, like

```
Total issues found: 210
```
and maybe an extra flag like `--verbose` that would display a full summary, like
```
  Found 210 issues in 64 files
 ------------------------
   10 Unused files
    3 Unlisted or unresolved dependencies
  127 Unused exports
    4 Unused exported types
    3 Unused exported enum members
   63 Unused exported class members
```
Basically a summary just like eslint does.

**Comment by webpro** [comment]
Since it's possible and straightforward to [create custom reporters](https://github.com/webpro/knip/blob/main/docs/custom-reporters.md), I'm going to close this one now. Also, feel free to open a PR and I'm happy to look into it.
