### ISSUE TITLE
Auto-detect `tsd`

### ISSUE THREAD

**Issue by voxpelli** [webpro/knip#535]
Would be sweet if `knip`  auto-detected [`tsd`](https://www.npmjs.com/package/tsd) and automatically detected `.test-d.ts` files as used then :)

It didn't for me when I added `tsd` in a project that uses `knip@5.0.3`

**Comment by webpro** [comment]
Sounds like a feature request for a tsd plugin :)

**Comment by voxpelli** [comment]
Oh, I should maybe have added it to #483 instead of creating a new issue, my bad 🙈 

I'll try to make a PR for one once the plugin work you seems to be up to in the [`plugins`](https://github.com/webpro/knip/tree/plugins) branch is done 🙂

**Comment by webpro** [comment]
> Oh, I should maybe have added it to #483 instead of creating a new issue, my bad 🙈

Sorry, didn't mean to hint that YOU should do that.

> I'll try to make a PR for one once the plugin work you seems to be up to in the [`plugins`](https://github.com/webpro/knip/tree/plugins) branch is done 🙂

Good call, was busy with that indeed: #540

**Comment by webpro** [comment]
Feel free to open a PR obviously, just trying to clean up the list of open issues.

**Comment by voxpelli** [comment]
@webpro And I actually moved away from using `tsd` myself and maybe we will even do so in `type-fest` 🙈

**Comment by webpro** [comment]
Oof, good to know :)
