### ISSUE TITLE
Knip doesn't track tsconfig file with typescript plugin enabled.

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#54]
**Knip version**: 1.8.0

While digging through the output objects in `--debug`, I noticed that knip is not tracking the tsconfig file. I have the typescript plugin enabled, whether I specify the option in my custom `knip.json` or not, the root tsconfig does not get tracked.
Excerpt from the debug message:
```
[knip] Unresolved configuration
{
  cwd: '<root>',
  tsConfigFile: undefined,
  gitignore: true,
  isStrict: false,
  isProduction: false,
  isShowProgress: false,
  isIncludeEntryExports: false
}
[knip] Included workspaces
[
  {
    name: '.',
    dir: '<root>',
    config: {
      entry: [ 'src/visual.ts' ],
      project: [ 'src/**/*.ts' ],
      paths: {},
      ignore: [],
      typescript: { config: [ 'tsconfig.json' ], entry: null, project: null }
    },
    ancestors: []
  }
]
[knip] Enabled plugins (.)
[
  'Babel',
  'commitlint',
  'ESLint',
  'husky',
  'Prettier',
  'TypeScript',
  'Webpack'
]
```

**Comment by webpro** [comment]
What do you mean by "track" here?

- Knip uses the TypeScript config to resolve files/paths.
- What the Knip TypeScript **plugin** does: find external dependencies from `extends` and `compilerOptions.plugins` in `tsconfig.json`. So Knip can eventually settle whether there's dependencies in `package.json` missing.

**Comment by ElPrudi** [comment]
I mean that the tsconfig-file is undefined. Is this a false alarm? Then I'm sorry.

**Comment by webpro** [comment]
Don't be sorry, you're helping this project a lot! Thanks a bunch.

The `tsConfigFile: undefined` in the unresolved configuration is about the CLI arguments coming in, so apparently `-t` or `--tsConfig` (to use something different than the default `tsconfig.json`) was not provided from the command line.

I'm going to make that more clear :)

**Comment by ElPrudi** [comment]
Oh, ok. Thank you for your explanation :)
