### ISSUE TITLE
`@commitlint/cli` - Unused devDependencies only in CLI

### ISSUE THREAD

**Issue by RebeccaStevens** [webpro/knip#542]
When I run `knip` locally everything passes, but it CI it fails. I've got no idea why.

Here's my CI output:
https://github.com/RebeccaStevens/template-typescript-node-package/actions/runs/8243105381/job/22543137223

**Comment by webpro** [comment]
Closing this as I think it's not a bug in Knip, but rather a different environment with different (npm) scripts, files present, etc.

**Comment by RamAvni** [comment]
Any update on this one?
