### ISSUE TITLE
Knip reports sass-loader as unused dependency

### ISSUE THREAD

**Issue by drodil** [webpro/knip#543]
When using sass-loader in the React component to load `.scss` files, knip reports this as an unused dependency. For example:

```tsx
import 'style-loader!css-loader!sass-loader!./App.scss';
```

```json
"devDependencies": {
   "sass-loader": "^14.0.0"
}
```

**Comment by webpro** [comment]
Shouldn't those loaders be referenced in Webpack config (or what else understands this)?

And then I guess those should be listed in `package.json` as well.

**Comment by webpro** [comment]
Sounds like Knip behaves as expected then? Why is `sass-loader` listed?

**Comment by webpro** [comment]
Not sure if this is an issue with Knip. This feels similar to using peer dependencies. If you remove `sass-loader` from the list it shouldn't break?

From Knip perspective, the question might be whether `sass-loader` being referenced in an import specifier is enough, and I'm on the fence with that. Either way, it wouldn't be trivial to support and I think it won't happen soon. So at this point there isn't much I can do, sorry.

**Comment by drodil** [comment]
Ok, well it breaks if I remove the `sass-loader` dependency. Have to just add it to the `ignoredDependencies` list then

**Comment by fregante** [comment]
Yes here knip should detect `sass-loader` as a dependency because it's explicitly listed: https://webpack.js.org/concepts/loaders/#inline

This type of loader configuration is very old and has been mostly replaced by `rules` in `webpack.config.js`, but the docs still mention it as first-class 🤷‍♂️ 🤢
