### ISSUE TITLE
Error parsing .prettierrc.json Reason: Unexpected end of JSON input

### ISSUE THREAD

**Issue by marco-carvalho** [webpro/knip#545]
https://stackblitz.com/edit/vitejs-vite-7iuew8

```sh
❯ npx knip
Analyzing workspace ....
Error parsing /home/projects/vitejs-vite-7iuew8/.prettierrc.json
Reason: Unexpected end of JSON input
```

**Comment by webpro** [comment]
<img width="348" alt="Screenshot 2024-03-14 at 8 16 03 AM" src="https://github.com/webpro/knip/assets/456426/26af5129-e17c-49ac-a0ae-2a26db8afc4c">

**Comment by marco-carvalho** [comment]
@webpro sorry, I didn't updated the repo, but now I did.

**Comment by webpro** [comment]
Still not sure what you're ask is. The file is empty, that's invalid JSON. That's literally the error message.
