### ISSUE TITLE
Compilers should receive the file name that they are operating on

### ISSUE THREAD

**Issue by ryanwilsonperkin** [webpro/knip#547]
The current API for a compiler is a function that receives the text contents of the file as its only input, and produces a list of imports. It would be great if the compiler also received the path to the file that is being acted on as context.

For example, imagine the following CSS module files:

```
// src/foo/foo.module.css
@import '../bar/bar.module.css';
...

// src/bar/bar.module.css
@import 'global.module.css'
...

// src/styles/global.module.css
...
```

For an application using PostCSS, this set of CSS modules could be perfectly valid because `postcss-import` can take a set of paths as globals for where it should try to resolve modules from, so we could provide it `src/styles` as a place to search for absolute paths like `global.module.css`

The given example on https://knip.dev/features/compilers#css handles the case of `foo` correctly, but fails on `bar` because it does not have a concept of the global definition. In this case it would be desirable for users to be able to provide a compiler that actually invokes postcss and retrieves the resolved imports from its result, but this would require us to provide the path to the file for the `from` context.

**Comment by ryanwilsonperkin** [comment]
As another example, I'd like to be able to provide a compiler to compile a custom manifest file type, but the compilation will require it to to check the existence of relative paths listed within it. We can only calculate those relative paths by knowing the path of the file itself that has provided the text.

**Comment by webpro** [comment]
Isn't it the second argument?

**Comment by ryanwilsonperkin** [comment]
It doesn't appear to be if I define compilers inline in my config

eg.

```ts
import type {KnipConfig} from 'knip';
const config: KnipConfig = {
  compilers: {
    css: (text, filename) {}
  }
}
```

`text` is typed as a string, but `filename` gives `unknown`

**Comment by webpro** [comment]
And if you actually try it?

**Comment by webpro** [comment]
Absolutely! But for now you're good hopefully

**Comment by ryanwilsonperkin** [comment]
Sure does, thanks @webpro 
I've opened a PR which I _think_ will update the relevant places, but I'm not sure if there's any additional work needed to build or validate the zod schema change.
