### ISSUE TITLE
Knip sees some bash parameters as unresolved dependencies.

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#55]
**Knip version**: 1.9.0

I've set up a monorepo with husky and commitlint with a commit-message hook.
Here is the full tutorial: https://betterprogramming.pub/how-to-lint-commit-messages-with-husky-and-commitlint-b51d20a5e514

In this tutorial a `commit-msg` file has to be created with this command
```
npx --no --commitlint --edit ${1}
```
After running `knip` it says:
```
Unlisted or unresolved dependencies (1)
${1}
```

Here are more test cases:

```
npx --no --commitlint --edit ${1} ${2}
...
Unlisted or unresolved dependencies (1)
${1}
```

```
npx --no --commitlint --edit  ${35} 
...
Unlisted or unresolved dependencies (1)
${35}
```

```
npx --no --commitlint --edit $1 $2
...
Unlisted or unresolved dependencies (1)
$1
```
I guess this has something to do with the position in this command.

Edit: Here is what the `--debug` option says
```
[knip] Dependencies used by husky configuration (1)
[ '${1}' ]
```

**Comment by webpro** [comment]
This should be fixed in [v1.10.0](https://github.com/webpro/knip/releases/tag/1.10.0) (although `--commitlint` in the examples should have a space in between or the dashes removed).
