### ISSUE TITLE
Knip flags .graphql imports as unused when they have a co-located .d.ts file

### ISSUE THREAD

**Issue by ryanwilsonperkin** [webpro/knip#550]
We can configure `knip` to search for unused `.graphql` files by adding a "graphql" entry to the compilers option, but if the GraphQL files in the project have a co-located `.d.ts` file then they will be incorrectly reported as unused.

Example reproduction here: https://github.com/ryanwilsonperkin/knip-issue-non-js-dts

This example provides a small React application bundled by Vite, which uses a code generation tool to produce a `.d.ts` file next to every `.graphql` file, such as

```
src/ExampleQuery.graphql
src/ExampleQuery.graphql.d.ts
```

When just the `.graphql` file exists, Knip acts correctly and will only report unused files as unused, but when a corresponding `.d.ts` file is found, it seems that Knip only marks that `.d.ts` file as used, and will report that all GraphQL files are unused.

**Comment by ryanwilsonperkin** [comment]
I'm also happy to help contribute a fix to this, would just need to align with the authors on the most appropriate way to rearchitect some of the module resolution since it seems like the right approach here might be to resolve _multiple_ modules such as what happens with the `.js` detection for co-located `.d.ts` files

**Comment by webpro** [comment]
What a coincidence, I actually have a fix already. But taking the opportunity to refactor module resolution as a whole, to also be able to support React Native/Metro projects.

I can publish a version shortly for you to try it out though.

**Comment by ryanwilsonperkin** [comment]
That'd be excellent, thank you!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.1.3-canary.0. See [Release 5.1.3-canary.0](https://github.com/webpro/knip/releases/tag/5.1.3-canary.0) for release notes._

**Comment by webpro** [comment]
Would be great if you could try out this version before I'll release v5.1.3 (I'm not in a hurry btw)

**Comment by ryanwilsonperkin** [comment]
Just tested and can confirm this is working for finding the `.graphql` files now, thanks @webpro!

**Comment by webpro** [comment]
Thanks for the feedback! It's in v5.1.3
