### ISSUE TITLE
UNIX "touch" command is recognized as an unlisted binary

### ISSUE THREAD

**Issue by lucasrmendonca** [webpro/knip#552]
The [touch command](https://en.wikipedia.org/wiki/Touch_(command)) from UNIX/Linux is being recognized as an unlisted binary, probably because Knip can't be sure if it's an OS command or the [npm package "touch"](https://www.npmjs.com/package/touch).

However, since the npm package hasn't been updated in over 7 years, I'd like to suggest to add the "touch" command to the list of ignoredBinaries permanently, what do you think @webpro ?

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.1.2. See [Release 5.1.2](https://github.com/webpro/knip/releases/tag/5.1.2) for release notes._

**Comment by webpro** [comment]
Agreed!
