### ISSUE TITLE
error when using with turborepo + pnpm

### ISSUE THREAD

**Issue by louisgv** [webpro/knip#554]
I was able to run Knip in a flat repo. However, when running in a monorepo created with turborepo, I got the following:

```
/test/node_modules/.pnpm/typescript@5.4.2/node_modules/typescript/lib/typescript.js:122445
              if (otherFileText !== existingFile.text) {
                                                 ^

TypeError: Cannot read properties of undefined (reading 'text')
    at processTypeReferenceDirectiveWorker (/test/node_modules/.pnpm/typescript@5.4.2/node_modules/typescript/lib/typescript.js:122445:50)
    at processTypeReferenceDirective (/test/node_modules/.pnpm/typescript@5.4.2/node_modules/typescript/lib/typescript.js:122415:7)

Node.js v20.9.0
```

To reproduce:

1. `pnpm create turbo@latest`, pick `pnpm`
2. Add knip + knip script
3. `pnpm knip`

**Comment by louisgv** [comment]
Tried with older ts version, same issue:

```
turborepo-pnpm-knip/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:121138
              if (otherFileText !== existingFile.text) {
```

**Comment by jonkoops** [comment]
This issue is also reproducible on [our repo](https://github.com/keycloak/keycloak/tree/main/js).

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.1.4. See [Release 5.1.4](https://github.com/webpro/knip/releases/tag/5.1.4) for release notes._

**Comment by webpro** [comment]
Thanks folks! Should be good now

**Comment by jonkoops** [comment]
Thanks for the quick turnaround @webpro
