### ISSUE TITLE
Dynamic imports are reported as unused

### ISSUE THREAD

**Issue by coryhouse** [webpro/knip#556]
Knip reports the the module I'm dynamically importing as unused. 

Small repo that reproduces the issue: https://github.com/coryhouse/knip-react-router-issue. Run `npx knip` to see the issue. Note that `PageOne` and `PageTwo` are dynamically imported in App.tsx, but reported as unused. 

Output:
```
coryhouse@Cory-M1 ~/P/knip-react-router-issue (main) [SIGINT]> npx knip
Analyzing workspace ....
Unused exports (2)
Component  unknown  src/PageOne.tsx:1:14
Component  unknown  src/PageTwo.tsx:1:14
```

This repo uses React Router's [lazy](https://reactrouter.com/en/main/route/lazy).

**Comment by webpro** [comment]
> Note that `PageOne` and `PageTwo` are dynamically imported in App.tsx, but reported as unused.

Their `Component` exports rather than the files themselves are reported as unused. There's currently not much Knip can do about this, other than think the `default` export is what's being used.

You could look at JSDoc tags to mark those exports:

- https://knip.dev/reference/cli#--experimental-tags
- https://knip.dev/reference/jsdoc-tsdoc-tags

**Comment by coryhouse** [comment]
@webpro - Great point. You're right - React Router's approach here is non-standard. The exported component isn't explicitly referenced, so there's no way for Knip to "see" the consumption.

Marking the exports as `/** @public */` does the trick for now. Thanks!

**Comment by coryhouse** [comment]
I'm going to close this since I don't see anything Knip can do - the real root cause is React Router doing something tricky and non-standard. Thanks again!

**Comment by webpro** [comment]
Just for the record: https://knip.dev/guides/handling-issues#external-libs

Most similar situations should be handled properly cq don't need to be ignored. This particular case might be a bug with TypeScript or the RR types.

**Comment by crystalfp** [comment]
I have a bunch of UI components loaded dynamically with:
```
defineAsyncComponent(() => import(`../ui/${item.ui}.vue`));
```
Understand that Knip cannot mark as used the files under `../ui/` But is there a way to manually say "These file are used, trust me"? They are listed in the configuration file project entry.
Thanks!
