### ISSUE TITLE
Allow using inline code comments to override config

### ISSUE THREAD

**Issue by sbalay** [webpro/knip#557]
It would be nice if we could use code comments to tell `knip` to ignore a file, export, variable, etc, similar to [how eslint works](https://eslint.org/docs/latest/use/configure/rules#using-configuration-comments-1)

**Comment by webpro** [comment]
Knip tries not to introduce new/proprietary syntax: https://knip.dev/explanations/why-use-knip#unobtrusive

You still have some options, though:

- https://knip.dev/reference/cli#--experimental-tags
- https://knip.dev/reference/jsdoc-tsdoc-tags

**Comment by sbalay** [comment]
> Knip tries not to introduce new/proprietary syntax: https://knip.dev/explanations/why-use-knip#unobtrusive
> 
> You still have some options, though:
> 
> * https://knip.dev/reference/cli#--experimental-tags
> * https://knip.dev/reference/jsdoc-tsdoc-tags

Missed that part in the docs, thanks for the quick reply!
