### ISSUE TITLE
Huge slow down between 5.1.2 and 5.1.4

### ISSUE THREAD

**Issue by fregante** [webpro/knip#559]
- 5.1.2: 50 seconds https://github.com/pixiebrix/pixiebrix-extension/actions/runs/8344206799/job/22836126224
- 5.1.4: 11 minutes https://github.com/pixiebrix/pixiebrix-extension/actions/runs/8350254200/job/22856242159

I'm also seeing a change of resolution, which is missing a CJS file import and not reporting a missing cli in npm scripts too (knip)

https://github.com/pixiebrix/pixiebrix-extension/commit/12cb937a06efaed101ec79081c093450ecbf6cd1

**Comment by webpro** [comment]
My guess is that the performance improvements when `classMembers` is excluded (the default) is working out well, but negatively impacts this case which has `classMembers` included.

Can you confirm running without `classMembers` is faster?

**Comment by fregante** [comment]
Thank you ☺️
