### ISSUE TITLE
Unused binary in TypeScript projects.

### ISSUE THREAD

**Issue by ozum** [webpro/knip#561]
Hi,

My TypeScript project has "src/bin/create.ts", and my `package.json` has `bin` entry for compiled js:

```json
  "bin": {
    "create": "dist/bin/create.js"
  },
```

Knip reports "src/bin/create.ts" as an unused file.

P.S. As a workaround, I added the files to the ignore list. However, it would be very nice Knip detects it automatically.

Kind regards,

**Comment by webpro** [comment]
How would Knip be able to match those files?

You can add `src/bin/create.ts` as an entry file manually.

**Comment by ozum** [comment]
> How would Knip be able to match those files?

For a TypeScript project, mapping files from TypeScript from the source directory to the destination directory. For this case, `src/**` -> `dist/**`. However this could have many edge cases, I don't know whether it is possible to detect those directories from tsconfig.json reliably.

> You can add src/bin/create.ts as an entry file manually.

Thanks, I already did this.

**Comment by webpro** [comment]
At this point I think adding an `entry` is effective and straightforward.

I'd love to abstract this away from the user, but there are multiple tools potentially involved  (TypeScript or bundlers like Webpack, etc). So I'm going to close this one for now.
