### ISSUE TITLE
knip@5 unresolved imports for non-JS/TS files with aliases

### ISSUE THREAD

**Issue by what1s1ove** [webpro/knip#563]
Hello guys! Thanks for such a cool package!

After updating **knip** to version 5, I started getting an error about **Unresolved imports** for non-JS/TS files (for example `.css`), if they are imported via an alias (`compilerOptions.paths` option in the TS config). This wasn't the case in version 4.

A live example where you can see it - https://github.com/what1s1ove/whatislove.dev/pull/368/files#diff-4ff343093dd7d14f4172b6c8ee05f543dd7b805a877cc223a358750dd8e5884bR4

Perhaps I missed something with the updates? Could you please advise if I'm missing something?

UPD:
Sorry, just noticed that there is a **Regression** issue type 🥲 I will be more careful in the future.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.2.1. See [Release 5.2.1](https://github.com/webpro/knip/releases/tag/5.2.1) for release notes._

**Comment by webpro** [comment]
Oops, thanks! I was just fixing some bugs anyway 🚀
