### ISSUE TITLE
Clarifications regarding the `includeEntryExports` option along with `.js` files

### ISSUE THREAD

**Issue by what1s1ove** [webpro/knip#564]
Knip uses `.ts` or `.d.ts` files to determine whether files are being used throughout the project. In projects where there are no `.ts` files, only `.js` files, for example, those using JSDoc for typing, types can be obtained by creating `.d.ts` files from `.js` files where JSDoc is used (Creating .d.ts Files from .js files – https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html).

Since these `.d.ts` files are considered artifacts of the project, they are often added to `.gitignore`.

In order for knip to successfully determine whether files are being used in the project, in the `knip.config.js`, the `entry` must specify the path to `index.d.ts`. However, since knip by default ignores all files listed in `.gitignore`, it turns out that performing project checks with knip is not entirely accurate.

This can be worked around by adding the `--no-gitignore` flag when executing knip (and at the same time, now in the `knip.config.js`, all additional items that were in `.gitignore` need to be manually listed). After that, project checks with knip will run successfully. But this seems more like a hack than how it should be, in my opinion.

My suggestion is to allow knip to use files explicitly listed in `knip.config.js`, even if they are in `.gitignore`.

A live example where you can see it - https://github.com/what1s1ove/whatislove.dev/pull/368/files

**Comment by webpro** [comment]
Just recently a feature landed that accepts `.js` with `.d.ts` sibling files.

So my first question is: how are the results when not adding `.d.ts` files as entry files and also not ignoring them?

**Comment by what1s1ove** [comment]
> Just recently a feature landed that accepts `.js` with `.d.ts` sibling files.
> 
> So my first question is: how are the results when not adding `.d.ts` files as entry files and also not ignoring them?

Yes, I will receive an error message

```
Unused exports (1)
hello  unknown  packages/shared/build/index.d.ts:2:14
```

But I had to temporarily remove the folder where `d.ts` artifacts with `.gitignore` are stored: 

<img width="259" alt="image" src="https://github.com/webpro/knip/assets/42296182/9f6a3a3d-ac03-4e4e-bc84-c48c77e92a77">

`d.ts` are project artifacts. They shouldn't be in git

**Comment by webpro** [comment]
> `d.ts` are project artifacts. They shouldn't be in git

I tend to agree, but some repos still seem to have them checked in (also see #503).

Either way, you can add them to `ignore` config.

> But I had to temporarily remove the folder where `d.ts` artifacts with `.gitignore` are stored:

What happens if you don't do this?

**Comment by what1s1ove** [comment]
> > `d.ts` are project artifacts. They shouldn't be in git
> 
> I tend to agree, but some repos still seem to have them checked in (also see #503).
> 
> Either way, you can add them to `ignore` config.
> 
> > But I had to temporarily remove the folder where `d.ts` artifacts with `.gitignore` are stored:
> 
> What happens if you don't do this?

I will need to commit the entire build and commit it every time there are files in it. I think this is not what is needed 🥲

<img width="411" alt="image" src="https://github.com/webpro/knip/assets/42296182/dc5b90df-0fd2-48e5-b147-70fc59795389">

**Comment by webpro** [comment]
No, obviously that's not what you want, but I meant from the perspective of running knip.

I guess the feature request remains to always add `entry` items, even if they're (git-)ignored.

**Comment by what1s1ove** [comment]
> No, obviously that's not what you want, but I meant from the perspective of running knip.
> 
> I guess the feature request remains to always add `entry` items, even if they're (git-)ignored.

Yes, you're right. It will fix everything I guess

**Comment by webpro** [comment]
Still not sure if this is a good idea, in https://github.com/what1s1ove/whatislove.dev/pull/368/files#diff-276af98608d3690a0aaff2941183c722215f049710a6a3b83642b946e1e36a89 I'm seeing see `entry: ['build/index.d.ts']`, while build artifacts generally shouldn't be statically analyzed in the first place.

**Comment by what1s1ove** [comment]
> Still not sure if this is a good idea, in https://github.com/what1s1ove/whatislove.dev/pull/368/files#diff-276af98608d3690a0aaff2941183c722215f049710a6a3b83642b946e1e36a89 I'm seeing `entry: ['build/index.d.ts']`, while build artifacts generally shouldn't be statically analyzed in the first place.

this is how `d.ts` files are usually used when working with `.js` + typing (without `.ts`)

the build for `d.ts` files happens on the `postinstall` script, so they are always there essentially.

**Comment by webpro** [comment]
> In order for knip to successfully determine whether files are being used in the project, in the `knip.config.js`, the entry must specify the path to `index.d.ts`.

I feel like this is might be the culprit. This file is the "DTS entry", but not the actual source entry file of the lib/workspace. I think it starts at e.g. `src/index.js`. We should take it from there.

**Comment by what1s1ove** [comment]
> > In order for knip to successfully determine whether files are being used in the project, in the `knip.config.js`, the entry must specify the path to `index.d.ts`.
> 
> I feel like this is might be the culprit. This file is the "DTS entry", but not the actual source entry file of the lib/workspace. I think it starts at e.g. `src/index.js`. We should take it from there.

I completely agree with this. This would be the most ideal option. But as far as I understand, knip uses TypeScript (it doesn’t matter whether it’s `.ts` or `.d.ts`, but _not_ `.js`) in order to find out whether a dependency is used somewhere or not. Or am I wrong?

**Comment by webpro** [comment]
Knip indeed uses TypeScript's module resolution as basis, but has additional features on top of that. Knip supports JavaScript repos without any TypeScript as well.

Not sure if it helps, but you could use `--debug` to see what files are included in the analysis (or even `--trace` to see how exports are matched against imports).

**Comment by what1s1ove** [comment]
> Knip indeed uses TypeScript's module resolution as basis, but has additional features on top of that. Knip supports JavaScript repos without any TypeScript as well.
> 
> Not sure if it helps, but you could use `--debug` to see what files are included in the analysis (or even `--trace` to see how exports are matched against imports).

I see... 

Then there may be an issue with `includeEntryExports`.

If I set the `entry` everywhere as `src/index.js`, I'll get this output from Knip:

```
Unused exports (10)
ValuesOf              unknown  packages/shared/src/index.js:10:9 
thisIsUnusedFunction  unknown  packages/shared/src/index.js:12:14
ProcessExitCode       unknown  packages/shared/src/index.js:1:22 
KeyboardKey           unknown  packages/shared/src/index.js:1:9  
checkIsOneOf          unknown  packages/shared/src/index.js:2:9  
getFormattedDate      unknown  packages/shared/src/index.js:3:15 
getRandomNumber       unknown  packages/shared/src/index.js:4:19 
getShuffledItems      unknown  packages/shared/src/index.js:5:18 
initDebounce          unknown  packages/shared/src/index.js:6:19 
```

Although, in fact, all dependencies except `thisIsUnusedFunction` are used in other applications.

But if I use a hack through `build/index.d.ts` as an `entry` (as it is now in the pull request example), everything will continue to work.

So it seems the issue might lie within `includeEntryExports` itself, and it only works with paths that TypeScript understands (`.ts` or `.d.ts` files).

**Comment by webpro** [comment]
Feel free to create a minimal reproduction of the issue and I'm happy to look into it. Please either change the title of this one or create a new one if you do :)

**Comment by what1s1ove** [comment]
Hey @webpro ! 

Sorry for the delayed response!

I have prepared a repository with an example - https://github.com/what1s1ove/knip-playground

## Start
1. `git clone git@github.com:what1s1ove/knip-playground.git && cd knip-playground`
2. `npm i`
3. Run on of the two scripts (see details below) 

## Brief description of the repo:

### Folders:
- `apps/app-a` and `apps/app-b` - applications using dependencies from `package/shared`
- ` package/shared` - a package with reusable dependencies. `package/shared` exports two functions in the `index.js` file: `usedFunction` and `unusedFunction`. The `usedFunction` is used in `apps/apps-a` and `apps/app-b`, while the `unusedFunction` is not used anywhere. I want Knip to complain about `unusedFunction`.

### Knip configurations:
- `knip-dts.js` - has an `entry` for `package/shared` as `build/index.d.ts` and the `includeEntryExports` option enabled. Currently, Knip complains about the `unusedFunction`, which is what I want to achieve.
- `knip-js.js` - has an `entry` for `package/shared` as `src/index.js` and the `includeEntryExports` option enabled. Currently, Knip complains about both `usedFunction` and `unusedFunction`, which is incorrect.

### Scripts:
- "knip-js": "knip --config knip-js.js"
- "knip-dts": "knip --config knip-dts.js --no-gitignore"

**Comment by webpro** [comment]
Thanks a lot for the detailed repo, it inspired me to make a significant change in module resolution. I've used most of your rep(r)o as a fixture in https://github.com/webpro/knip/tree/main/packages/knip/fixtures/workspaces-dts

Feel free to try out v5.7.0 and see if it helps. To be clear: the case with `src/index.js` (not a DTS file) as an entry file should indeed result in `unusedFunction` being reported as unused.

**Comment by what1s1ove** [comment]
Hey @webpro ! 

Thank you so much! Now everything works as expected!

Thank you for not following my first suggestion and fixing it by changing the logic of the `--no-gitignore` flag 😁

**Comment by webpro** [comment]
Yeah, sorry for the confusion, but we'll get there 🚀 

Just saying, this is what fixed it (basically always try to resolve to a `.js/.ts` file first): 47ff3eb4f79c5f85c595847033e42012a70d7ee7
