### ISSUE TITLE
Results from async compilers are ignored

### ISSUE THREAD

**Issue by ryanwilsonperkin** [webpro/knip#566]
https://knip.dev/features/compilers states that `compilers` can be `async` functions, this was previously working on v5.1.2, something appears to have changed since then causing the compiler to be run but its results are not used and so the results that are returned do not result in the files being marked as used.

**Comment by ryanwilsonperkin** [comment]
Bisecting releases, the issue appears to have been introduced in version `5.1.3`

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.2.2. See [Release 5.2.2](https://github.com/webpro/knip/releases/tag/5.2.2) for release notes._

**Comment by webpro** [comment]
I think it's fixed now, let me know if it isn't. Next time, a but more details are probably useful :)

**Comment by ryanwilsonperkin** [comment]
Yep! Working as of `5.2.2`

A test I was using for this was:
```
{
  compilers: {
    css: async () => '',
  }
}
```
Which would result in the CSS files being marked as unused, while dropping the `async` allowed them to be used. In practice, our CSS compiler is fairly more complicated but narrowed it to the use of an async function.

**Comment by webpro** [comment]
Thanks! I'm mostly happy both the report and the fix were quick 🚀
