### ISSUE TITLE
Multiple package occurrences in a monorepo are only evaluated once and then fail

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#57]
**Knip version**: 1.10.0

In my monorepo every package has it's own prettier config file.

`<root>/package.json`

```json
{
    "devDependencies": {
        "prettier": "^2.8.3"
    }
}
```
`<root>/packages/eslint-config-<project>/package.json`

```json
{
    "dependencies": {
        "eslint-plugin-prettier": "^4.2.1",
        "prettier": "^2.8.3"
    }
}
```
`<root>/packages/build/package.json`

```json
{
    "devDependencies": {
        "prettier": "^2.8.3"
    }
}
```
`pnpm-workspace.yaml`
```yaml
packages:
    # main package
    - 'src/*'
    # all packages in direct subdirs of packages/
    - 'packages/*'
```
`<root>/knip.json`
```json
{
	"$schema": "https://unpkg.com/knip@1/schema.json",
	"entry": ["src/index.ts"],
	"project": ["src/**/*.ts"],
	"ignoreBinaries": ["nw"],
	"workspaces": {
		"packages/*": {
			"entry": "index.js",
			"project": "**/*.ts"
		}
	}
}
```
After running `npm run knip`:
```
Unused dependencies (1)
prettier                                packages/eslint-config-<project>/package.json
Unused dev dependencies (1)
prettier                                packages/build/package.json
```

It seems like knip resolves the dependencies in the root `package.json` for the whole monorepo. Then after the root evaluation it finds a sub package `package.json` but because it's been already evaluated it sees it as unused dependency. At least that is my theory.

**Comment by webpro** [comment]
Knip checks all dependencies in each package, but the default mode accepts that dependencies are listed in an ancestor package as well.

However, seeing your configuration, I realize that the root package must be under `workspaces` as `"."` like so:

```json
{
  "$schema": "https://unpkg.com/knip@1/schema.json",
  "workspaces": {
    ".": {
      "entry": ["src/index.ts"],
      "project": ["src/**/*.ts"]
    },
    "packages/*": {
      "entry": "index.js",
      "project": "**/*.ts"
    }
  }
}
```

This was not documented all, sorry! Going to update the readme shortly.

**Comment by ElPrudi** [comment]
Yes, this was the reason. But for whatever reason it still says in my build package that the `prettier` dependency is unused and I don't know why, because the `.prettierc` file is there.

**Comment by webpro** [comment]
> Yes, this was the reason. But for whatever reason it still says in my build package that the `prettier` dependency is unused and I don't know why, because the `.prettierc` file is there.

For Knip, the existence of a configuration file `.prettierc` does not mean the related dependency is actually used. The `prettier` dependency or binary itself should be referenced somewhere, usually from some npm script in the `package.json` of the same package, e.g.:

```
{
  "scripts": {
    "format": "prettier src --write",
  }
}
```

**Comment by ElPrudi** [comment]
> For Knip, the existence of a configuration file `.prettierc` does not mean the related dependency is actually used.

Which is weird because none of my packages have a prettier script inside their `package.json` but it's not treated as "unused dev dependency". I always thought the main reason for having prettier as dev dependency would be to just have a `.prettierrc` file.

**Comment by webpro** [comment]
Are you sure it's not referenced anywhere? Could be source code, a GitHub Action workflow yaml file, and so on.

**Comment by ElPrudi** [comment]
If I have a tool that would search it for me in my whole repo I could answer that, but I checked again and only in the root it's not treated as unused dev dependency, while knip detects it in all of my sub packages.
I now have it as peer dependency as I need it for my eslint config.

**Comment by ElPrudi** [comment]
But for now, I'll just close it because the error was on my end. Maybe I have a prettier ignore comment somewhere in my code I forgot.
