### ISSUE TITLE
TypeScript: support for triple-slash directives

### ISSUE THREAD

**Issue by fregante** [webpro/knip#571]
I think this doesn't work at the moment: https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

```ts
/// <reference types="..." />
/// <reference path="..." />
```

For example my global.d.ts file has:

```ts
// We only use this package for its types. URLPattern is Chrome 95+
/// <reference types="urlpattern-polyfill" />

// Improve standard type library https://www.totaltypescript.com/ts-reset
/// <reference types="@total-typescript/ts-reset" />
```

**Comment by webpro** [comment]
I think that should work. Did you try the latest version + the `--include-libs` flag?

Is the `global.d.ts` included when you use the `--debug` flag?

Please create a minimal reproduction.

**Comment by fregante** [comment]
> Did you try the latest version + the `--include-libs` flag?

Yes, no change



> Is the `global.d.ts` included when you use the `--debug` flag?

Yes it does appear in `Project paths`. Here's the last few lines of the repro debug output:


```sh
[]
[*] Created 1 programs for 1 workspaces
[*] Analyzing used resolved files [P1/1] (1)
[ '/-repro/global.d.ts' ]
Unused dependencies (1)
webextension-polyfill  package.json
Unused devDependencies (2)
@sindresorhus/tsconfig      package.json
@total-typescript/ts-reset  package.json
```

## Repro

```json5
// tsconfig
{
  "extends": "@sindresorhus/tsconfig"
}
```

```ts
// global.d.ts

/// <reference types="@total-typescript/ts-reset" />

declare const browser: import("webextension-polyfill").Browser;
```

```sh
npm init -y
npm install -D knip
npm install -D @total-typescript/ts-reset @sindresorhus/tsconfig 
npm install webextension-polyfill
npx knip --include-libs --debug
```

**Comment by fregante** [comment]
It seems that it doesn't detect type dependencies specified like that, including in JSDoc:

```js
/**
 * @param {import("webpack").Configuration[]} configs
 */
module.exports = (...configs) => merge(shared, ...configs);
```

from https://github.com/pixiebrix/pixiebrix-extension/blob/69318e6cc4e5d5931f346a30b171216c97c86533/webpack.sharedConfig.js/#L138

My full knip config is at https://github.com/pixiebrix/pixiebrix-extension/blob/69318e6cc4e5d5931f346a30b171216c97c86533/knip.mjs

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.5.0. See [Release 5.5.0](https://github.com/webpro/knip/releases/tag/5.5.0) for release notes._

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.5.0. See [Release 5.5.0](https://github.com/webpro/knip/releases/tag/5.5.0) for release notes._

**Comment by webpro** [comment]
Thanks @fregante! Support should be better now

**Comment by fregante** [comment]
Thanks for the quick fix! 


Regarding the JSDoc issue, it was unrelated, `webpack-env` sets the type for `require.context`, not `import('webpack')`

**Comment by webpro** [comment]
What has been discussed and fixed here is making sure references to dependencies in `import()` statements and file pragmas are taken into account. Most of that, including type imports in JSDoc comments, was functioning already, but some edge cases were not.
