### ISSUE TITLE
Infinite (?) recursion with circular tsconfig references.

### ISSUE THREAD

**Issue by Jym77** [webpro/knip#574]
MNWE: https://codesandbox.io/p/devbox/x5zwqw

The global structure is a workspace/monorepo one, with a single package in `packages/foo`. The code inside the package seems to be of no relevance (here, just declaring and exporting a type).

The top-level directory has a `tsconfig.json` with most regular options and `"references": [{ "path": "packages" }]`.
The `packages` directory has a `tsconfig.json` extending it, and `"references": [{ "path": "foo" }]`.
The `packages/foo` directory (aka workspace) has a `tsconfig.json` extending the previous.

This creates some circular references between the `extends` and `references` fields.

Running knip on this project takes forever (several minutes before I get bored and kill it). The last displayed message is "Analyzing workspace packages/foo..."
When running with several workspaces (my actual code), I see all the "Analyzing workspace packages/pkg1…", "Analyzing workspace packages/pkg2…", … messages. So the problem likely appears in some post-processing step after these and before the "Connecting the dots…" message.

It seems that removing one level of references (moving the basic TS config in `packages/tsconfig.json` instead of the `extends` field) makes it snappy again. (I haven't tested that very thoroughly).

From local tests, this was very fast in `5.1.3-canary-0` and broke down in `5.1.3`. Not sure which commit created the problem.

I'm only seeing the problem with the nested/circular `tsconfig` files, so I assume there is a graph exploration that doesn't anymore account for circular graphs and therefore goes into infinite recursion.

**Comment by webpro** [comment]
I don't seem to have access to that devbox ("Devbox not found")

**Comment by Jym77** [comment]
Sorry, ~I was on mute~ it was private. Should be good now.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.6.1. See [Release 5.6.1](https://github.com/webpro/knip/releases/tag/5.6.1) for release notes._

**Comment by webpro** [comment]
Thanks for the repro @Jym77! Should be good now
