### ISSUE TITLE
Custom npm commands running tools through npx are reported as unlisted binaries

### ISSUE THREAD

**Issue by felpel** [webpro/knip#577]
In one of our `package.json`, we have a command like such:
```json
"check-updates": "npx npm-check-updates",
```
As I execute `knip` with the default configuration, the report shows me something like such:
```sh
Unlisted binaries (x)
npm-check-updates  package.json
```

`npm-check-updates` is not installed in my `devDependencies` and shouldn't be because `npx` is being leveraged.

It looks like a false positive here and the issue is reproducible with any command that would leverage `npx` (we have 3 in our project).

**Comment by webpro** [comment]
Yes, it's a known issue/ambiguity: https://knip.dev/guides/handling-issues#npx

Does that help?

**Comment by voxpelli** [comment]
Also: `npx` is rarely/never needed in npm scripts as the `node_modules/.bin` is added to the PATH when running commands from npm scripts

**Comment by webpro** [comment]
Good point, but I think @felpel has the goal not to have `npm-check-updates` in the list of dependencies.

Though, it's usually recommended to version/fix it explicitly in `package.json`. Then, this would be enough indeed:

```json
{
  "scripts": {
    "check-updates": "npm-check-updates",
  }
}
```

**Comment by felpel** [comment]
> Yes, it's a known issue/ambiguity: https://knip.dev/guides/handling-issues#npx
> 
> Does that help?

Seems like this should be good enough for our use case :)
