### ISSUE TITLE
When specifying the `workspaces` setting in a custom `knip.json`, knip does not lint for unused class members, enum members and types.

### ISSUE THREAD

**Issue by ElPrudi** [webpro/knip#58]
**Knip version**: 1.10.0

Just like the title says, if I specify my workspace in my custom `knip.json` file
```json
{
	"$schema": "https://unpkg.com/knip@1/schema.json",
	"entry": ["src/index.ts"],
	"project": ["src/**/*.ts"],
	"ignoreBinaries": ["nw"],
	"workspaces": {
		"packages/*": {
			"entry": "index.js",
			"project": "**/*.ts"
		}
	}
}
```
It finds:
```
Unused files (4)
Unused dependencies (17)
Unused dev dependencies (35)
Unlisted or unresolved dependencies (1)
```
but if I omit this setting, it finds:
```
Unused files (42)
Unused dev dependencies (16)
Unused exports (99)
Unused exported types (27)
Unused exported enum members (53)
Unused exported class members (728)
```
I'm in the process of fixing my API, which is why it's strange that I have to change my configuration so often to find everything.

**Comment by webpro** [comment]
Perhaps this is caused by the same: https://github.com/webpro/knip/issues/57#issuecomment-1399577011

**Comment by webpro** [comment]
By the way, there is a `--debug` option which logs which files are included from each package.

**Comment by ElPrudi** [comment]
> Perhaps this is caused by the same: [#57 (comment)](https://github.com/webpro/knip/issues/57#issuecomment-1399577011)

Yes, this was the reason. Since my build package is basically almost empty and the other package was just an eslint package, it appeared to me that the it didn't lint at all.
I really have to use the `--debug` flag more often before posting an issue.
