### ISSUE TITLE
commonjs unused module.exports detected vs exports not detected

### ISSUE THREAD

**Issue by hugomallet** [webpro/knip#580]
Hi,

Unused commonjs exports are not detected when they are exported using the exports alias.

For example, this unused export would be detected : 
```js
module.exports.add = () => {};
``` 

while this one won't be : 
```js
exports.add = () => {};
``` 

Thanks

**Comment by webpro** [comment]
That's correct, also see https://knip.dev/guides/commonjs for recommendations.

This is another subtle caveat with the dynamic nature of CommonJS. Using `module.exports` is generally preferred over `exports` (also see e.g. https://www.hacksparrow.com/nodejs/exports-vs-module-exports.html).

Not sure if Knip should still try to support this, but at least we can update the docs.

**Comment by webpro** [comment]
Alright then :)
