### ISSUE TITLE
Support for @access tags

### ISSUE THREAD

**Issue by jfmengels** [webpro/knip#584]
I discovered the existence of the [JSDoc `@access` tag](https://jsdoc.app/tags-access), which can simulate other tags.

> The @access tag specifies the access level of a member. You can use the @access tag as a synonym for other tags:
>
> `@access private` is the same as `@private`.
> `@access protected` is the same as `@protected`.
> `@access public` is the same as `@public`.

I don't know how widespread this syntax is in practice.
Note that I don't need this, just thought this could be good to support for completeness' sake. Feel free to close this if you think it will be useful to no-one.

**Comment by webpro** [comment]
Thanks for the suggestion. Can't remember seeing this in the wild and haven't heard this being requested. Unless there's demand it's probably better not to introduce unnecessary features/complexity.
