### ISSUE TITLE
Knip don't found files used only in tests

### ISSUE THREAD

**Issue by pkolt** [webpro/knip#591]
Hi guys!

I use knip@5.9.4 and React in my project.

Why knip don't ignore tests files? Even if I add tests files in "ignore" section in my config file.

```json
{
  "$schema": "https://unpkg.com/knip@5/schema.json",
  "entry": ["src/index.{ts,tsx}"],
  "project": ["src/**/*.{ts,tsx}"],
  "ignore": [
    "src/api/src/**",
    "src/service-worker.ts",
    "src/**/*.test.{ts,tsx}" // <-----THIS DON'T WORK
  ]
}
```

Also, I tried added their in "project" section, but this don't helped me.

```json
{
  "$schema": "https://unpkg.com/knip@5/schema.json",
  "entry": ["src/index.{ts,tsx}"],
  "project": ["src/**/*.{ts,tsx}", "!src/**/*.test.{ts,tsx}"], // <-----THIS DON'T WORK
  "ignore": [
    "src/api/src/**",
    "src/service-worker.ts"
  ]
}
```

Is there any way to make knip ignore test files for components? After all, this is a very common case when a component is no longer used. But tests are written for it, so knip does not consider the component to be dead code.

```
MyComponent.tsx // <--- THIS COMPONENT IS NOT USED ANYWHERE ELSE
MyComponent.test.tsx
```

**Comment by webpro** [comment]
Please see the following sections in the docs:

- https://knip.dev/guides/performance#ignoring-files
- https://knip.dev/features/production-mode

**Comment by pkolt** [comment]
Thank @webpro to your answer!

But I not found answer to my question. I think knip doesn't allow exclude tests files in analyze.
And this is very strange ☹️

Why does construction `"!src/**/*.test.{ts,tsx}"` not exclude files from analysis, but simply make them ignored in the report?

```json
{
  "$schema": "https://unpkg.com/knip@5/schema.json",
  "entry": ["src/index.{ts,tsx}"],
  "project": [
      "src/**/*.{ts,tsx}", 
      "!src/**/*.test.{ts,tsx}" // <--- use `!` the same thing as adding to section `ignore`
   ],
  "ignore": [
    "src/api/src/**",
    "src/service-worker.ts"
  ]
}
```

Even if I use [production mode](https://knip.dev/features/production-mode), it won't help me either. After all, I can’t separate the test files from all the files that knip analyzes.

I don't understand why this question hasn't arisen in the community before. After all, this is a very common case when test files interfere with knip searching for unused files.

**Comment by webpro** [comment]
A few remarks:

- The `project` file patterns are meant only to find unused files. The set of `project` files minus the `entry` files + resolved files result in unused files (https://knip.dev/guides/handling-issues#unused-files). In other words, you can't "remove files" from the resolved set of files based on the entry files by adding negated patterns to the `project` files.
- You want to use `--production` to exclude entry files added by plugins.
- Use `--debug` to see what files are added and why (e.g. by Knip core or by one of the plugins).

If this doesn't help enough you can create a [minimal reproduction](https://knip.dev/guides/troubleshooting#minimal-reproduction) and I'm happy to look into it.

> I don't understand why this question hasn't arisen in the community before. After all, this is a very common case when test files interfere with knip searching for unused files.

The issue you are seeing is particular to your project and your understanding of how Knip works. This is definitely something I need to improve in the documentation so your feedback is very useful!

**Comment by pkolt** [comment]
Hi @webpro ! Thanks to your answer!

>  In other words, you can't "remove files" from the resolved set of files based on the entry files by adding negated patterns to the project files.

You are absolutely right! This is my problem.

Now in my project there are test files (`*.test.tsx`) and storybook files (`*.stories.tsx`), because of which knip cannot understand that the code is no longer used.

It would be great if we could separate the test and storybook files into a group - `except`:

```json
{
    "entry": ["src/main.tsx"],
    "project": ["src/**/*.{ts,tsx}"],
    "except": ["src/**/*.test.tsx", "src/**/*.stories.tsx"] // <-- DON'T USE FOR CHECK "DEAD CODE"
}
``` 

If the file you are looking for is used only in test files (`*.test.tsx`) or storybook files (`*.stories.tsx`), then knip should consider it “dead code”.

I have prepared a thread for you in my project where you can experiment:

[[https://github.com/pkolt/bitmap_editor/tree/knip-issue-591]](https://github.com/pkolt/bitmap_editor/tree/knip-issue-591)

Component `src/components/Cat/index.tsx` is only used in the test and is dead code, but knip cannot determine this.

Maybe you can do something about this? In fact, after your last answer, I think that only changes knip can solve my problem.

**Comment by webpro** [comment]
Production mode is designed for this use case. What goes wrong if you use it?

**Comment by pkolt** [comment]
Hi @webpro !

> Production mode is designed for this use case. What goes wrong if you use it?

Can you give an example of a setup for production mode? In the example below, I should exclude tests (`*.test.tsx`) and storybooks (`*.stories.tsx`).

Default setup:

```json
{
    "entry": ["src/main.tsx"],
    "project": ["src/**/*.{ts,tsx}"]
}
```

**Comment by webpro** [comment]
This seems like a good example: https://github.com/invoke-ai/InvokeAI/tree/main/invokeai/frontend/web

Install dependencies with `pnpm` and run knip with `pnpm run lint:knip --debug` and `--debug --production` and see that in production mode, the stories aren't part of the analysis.

**Comment by pkolt** [comment]
Hi @webpro !

My ending knip config:

```json
{
  "entry": ["src/main.tsx!"]
}
```

I use command `knip --production`.

It wasn't obvious, but now it works!

Thank you for help! 👍

**Comment by webpro** [comment]
Glad you found it!

Just adding this for other reading this: `src/main.tsx!` is part of the default settings. But when it needs to be extended and overridden, the exclamation mark needs to be there as well, and this may not be obvious indeed.

**Comment by webpro** [comment]
Also based on the feedback here I just added this page: https://knip.dev/guides/configuring-project-files
