### ISSUE TITLE
How to best detect "test utility" files?

### ISSUE THREAD

**Issue by ryanwilsonperkin** [webpro/knip#592]
Let's say we have a set of 3 files in a workspace:
- `index.js`
- `tests/index.test.js`
- `tests/utilities.js`

The `tests/utilities.js` file is only imported by test files, and so when running `knip` in non-production mode – and having something like the `jest` plugin resolve the test file as an entrypoint – it will correctly find that `tests/utilities.js` is used. But when run in production mode, it is flagged as unused code.

How should we think about configuring Knip to avoid flagging these kinds of files?

**Comment by webpro** [comment]
Roughly this:

```json
{
  "entry": "index.js!",
  "project": "!tests/utilities.js!"
}
```

So you'd need to suffix production `files!` and prefix excluded `!files` and this can be combined.

Does that help?

Btw going to write new docs/guide about this topic as we speak :)

**Comment by ryanwilsonperkin** [comment]
This will work, but would also mean that if the test file ever updates to no longer reference `tests/utilities.js` that it wouldn't be flagged as unused, because it's been explicitly ignored.

I think we almost want something like a `productionIgnore` ability to say that certain paths should be ignored when running in production mode, but still checked in non-production mode, and then we could run both prod & non-prod in CI to be able to catch both "test-setup code" that is unused, and also "project file that is only used in tests"

**Comment by webpro** [comment]
Tbh I'm not sure whether the `!pattern!` is also ignored in non-production mode. Did you try?

**Comment by webpro** [comment]
Either way, if configuration gets messy, one can always resort to a seperate `knip --production --config knip.production.json`

**Comment by webpro** [comment]
I just added this page: https://knip.dev/guides/configuring-project-files

**Comment by webpro** [comment]
Going to close this one after the linked page got another update the other day. Feel free to discuss further, though :)
