### ISSUE TITLE
Are `.mdx` files supported?

### ISSUE THREAD

**Issue by voxpelli** [webpro/knip#60]
I wonder if `.mdx` files are supported?

Would be great to have them included. What would have to be done to add them?

**Comment by webpro** [comment]
Yes, that would be a nice feature indeed. Knip is currently using ts-morph (a wrapper around typescript) and ts-morph-helpers for static analysis. I haven't looked into the intricacies of another file format at all yet. Not using mdx myself either. However, static analysis to resolve its dependencies/imports may be fairly easy if there's packages already doing this. Need to look into how it affects the "core" of Knip as well. Any ideas you may have are welcome :)

**Comment by voxpelli** [comment]
@webpro Would be interested to help you look into it, considering that this package is way ahead of the one I’m currently helping maintaining (https://github.com/dependency-check-team/dependency-check) and it would be better for me to help you than to continue with that effort I think

**Comment by webpro** [comment]
> @webpro Would be interested to help you look into it

That would be great, feel free to dive in or let me know how I can introduce you to the codebase.

> considering that this package is way ahead of the one I’m currently helping maintaining (https://github.com/dependency-check-team/dependency-check) and it would be better for me to help you than to continue with that effort I think

Thanks! I can't remember seeing this lib. Latest release seems >3 years ago? Still >40k downloads a week (https://npm.im/dependency-check). Would be great if you could let me know (or even add fixtures, tests or fixes) so users can migrate easily without getting more false positives. Maybe worth an addition to the readme (comparison table).

But I'll try to stay on-topic :) Working on some other features myself atm, but feel free to look into it and ask me anything.

**Comment by voxpelli** [comment]
> > @webpro Would be interested to help you look into it
> 
> That would be great, feel free to dive in or let me know how I can introduce you to the codebase.

Thanks! I'll try to find some time soon :)

> > considering that this package is way ahead of the one I’m currently helping maintaining (https://github.com/dependency-check-team/dependency-check) and it would be better for me to help you than to continue with that effort I think
> 
> Thanks! I can't remember seeing this lib. Latest release seems >3 years ago? Still >40k downloads a week (https://npm.im/dependency-check). Would be great if you could let me know (or even add fixtures, tests or fixes) so users can migrate easily without getting more false positives. Maybe worth an addition to the readme (comparison table).

The latest pre-release of the new major is from 7 months ago, but I essentially never got really satisfied with how it handled typescript, ESM and such, so never got to fully release and then it has kind of stagnated as I'm currently the only one remaining to maintain it.

> But I'll try to stay on-topic :) Working on some other features myself atm, but feel free to look into it and ask me anything.

🙏

**Comment by webpro** [comment]
Quick dump of what I think might be a feasible route:

- Entry & project files are added in `class ProjectPrincipal`
- Compile `.mdx` to javascript with [@mdx-js/mdx](https://github.com/mdx-js/mdx/blob/main/packages/mdx/readme.md)
- Add resulting string as source file with [project.createSourceFile](https://ts-morph.com/setup/adding-source-files#by-string). Adding valid JS, but not sure whether non-ts extensions and their imports will be accepted/resolved, or how to deal with this.

Just came across an Astro project having `.astro` files, but same goes for `.svelte` etc. I guess, so atm I'm thinking some kind of compiler per file type here. Again, just dumping/thinking out loud.

**Comment by voxpelli** [comment]
And having it be pluggable so that not all languages have to be pulled into the main project (as that would result in maaaany dependencies)

**Comment by webpro** [comment]
Thanks for reminding me, just created https://www.npmjs.com/org/knip before someone else does :)

**Comment by webpro** [comment]
This ticket made me dig into the topic deeper, and at this point I'm thinking ts-morph, although it saved my life in the early phases, is now also becoming a bit of a burden. Looking at similar efforts (astro, mdx-js, vite) and some of my own attempts with providing custom `readFile[Sync]` and `resolveModuleNames` I prefer to get more closer to the bare metal of `typescript` itself here, without working with ts-morph in-between. This will also give this project more freedom/flexility in terms of performance and maintenance, etc. Also looking at the upcoming TS v5 and the fact that ts-morph is currently not under active development.

If there's an easy way to support mdx then that is of course welcome. But right now I'm looking into phasing out ts-morph first.

**Comment by webpro** [comment]
Quick update. Things are progressing pretty well, but it's quite the undertaking. Major improvements in performance though, while also opening up features such as requested here.

**Comment by webpro** [comment]
@voxpelli, maybe you just opened this ticket to only ask a question, but I still dare to ask: do you happen to have a repository at hand where you could maybe try something like the example `knip.ts` below?

```
import { compileSync } from 'mdx-js/mdx';

export default {
  compilers: {
    mdx: compileSync,
  },
};
```

Obviously this depends on the actual MDX compiler available in the project. Variations with `async` functions/compilers should work as well, as long as the function accepts `text` as input, and returns `text` (the JS or TS contents).

In a project that has `mdx-js/mdx` v1.6 this seems to work fine:

```
import compile from '@mdx-js/mdx';

module.exports = {
  compilers: {
    mdx: compile,
  },
};
```

**Comment by voxpelli** [comment]
@webpro I sadly no longer have access to such a codebase :/

**Comment by webpro** [comment]
With support for compilers in knip v2 I'm closing this issue.
