### ISSUE TITLE
File index.js and extensions that are omitted by default

### ISSUE THREAD

**Issue by fatyrify** [webpro/knip#600]
Hello, thanks for developing such a good tool :)

Recently, when I use knip in some js/ts/vue projects (built with webpack), the results of some knip analysis `Unused files` were not as expected.

Some path like:
> import 'src/component/chat'
> import 'src/utils/base-util'

in .vue/.js/.ts file are not successful detected, both paths export as `Unused files`.

Actually, this path means:
> src/component/chat/index.js | ts | jsx | vue
> src/utils/base-util/index.js | ts | jsx | vue

they omit the file's `index` and extension by default because the build tool webpack will look for these omitted file names by default.

Can I ask how knip can be configured to adapt to such a file path? If it is not supported currently, if I want to develop the knip source code by fork repo, which function and file should I start with to modify the path finder code logic?

Thanks!

These are the issues I found that may be similar
[issue_386](https://github.com/webpro/knip/issues/386)
[issue_530](https://github.com/webpro/knip/issues/530)

**Comment by webpro** [comment]
> Actually, this path means

As you mentioned already, this is what it means _to Webpack_. Knip indeed does not copy all module resolution internals out there but has a generic solution.

> Can I ask how knip can be configured to adapt to such a file path?

Regular module resolution should be fine, so I'd expect only the `./index.vue` to be found an issue here, no? Unfortunately this can't be configured with Knip.

In general, I would recommend to go with more ES Modules-like semantics, i.e. don't rely on the `dir/index` lookup and don't omit the extension.

> If it is not supported currently, if I want to develop the knip source code by fork repo, which function and file should I start with to modify the path finder code logic?

1) Some work has been done recently to try and see if custom module resolution is feasible. In https://github.com/webpro/knip/issues/126 a solution for React Native/Metro is discussed, and a working version has been published. That idea could probably be used to cover the use case you are describing as well, maybe by exporting a module resolver from the Webpack plugin. If that effort continues, I'm not yet sure yet how it should be configured. It's in the `feat/react-native-metro` branch of this repo and most of the work is in this commit: bdae3d63139bcda597f5caadce1afd30bfeb71f3).

2) If you're still interested in forking and modifying the current implementation yourself you can start here: https://github.com/webpro/knip/blob/main/packages/knip/src/typescript/resolveModuleNames.ts.

**Comment by fatyrify** [comment]
Thanks for the reply.

> Regular module resolution should be fine, so I'd expect only the ./index.vue to be found an issue here

I checked the knip execution results and found that `**/index.js` or `**/index.vue` were both output as `unused files`, (both path omit index.js | index.vue)

> It's in the feat/react-native-metro branch of this repo and most of the work is in this commit: https://github.com/webpro/knip/commit/bdae3d63139bcda597f5caadce1afd30bfeb71f3).

I looked at this part and tried using `"knip": "^0.0.0-metro.1"`, and this is my `metro.config.js` configuration
```js
module.exports.__KNIP_PLATFORMS__ = {
    vue: [
        ['/index', ''],
        ['.vue', ''],
    ],
    js: [
        ['/index', ''],
        ['.js', ''],
    ],
    ts: [
        ['/index', ''],
        ['.ts', ''],
    ],
};
```
and this is my `knip.json` configuration
```json
{
    "entry": ["src/index.js"],
    "project": ["src/**/*.{js,jsx,ts,tsx,vue}"],
    "paths": {
        "@/*": ["src/*"]
    },
    "includeEntryExports": true,
    "exclude": ["dependencies", "unlisted", "unresolved", "enumMembers", "types", "exports"]
}
```
The analysis results are still not within expectations, and more .vue files appear in `unused files`
I don't know whether the problem is caused by the missing extension of `.vue` or the problem caused by omitting `index.vue`. I need to keep researching this.

I will also take the time to look at the source code you mentioned above.

Thanks

**Comment by webpro** [comment]
> The analysis results are still not within expectations

The module resolver in the Metro plugin is indeed not what you need to suit your needs with your Webpack setup. It does not cater for omitted extensions (because I think it's not needed there). Sorry if that was confusing. I was saying that we would need a new module resolver in the Webpack plugin.

**Comment by fatyrify** [comment]
> Sorry if that was confusing

It's ok :)

>  I was saying that we would need a new module resolver in the Webpack plugin.

Yeah, this may be the solution
