### ISSUE TITLE
Consider the file in package.json types not to be unused

### ISSUE THREAD

**Issue by fcostarodrigo** [webpro/knip#607]
In a lib written in JS with the type declared in an `index.d.ts` referenced in the `package.json` `types` field, knip reports `index.d.ts` as unused.

It would be nice if knip would recognize that this file is used because it exports the types.

Stack Blitz example: https://stackblitz.com/edit/stackblitz-starters-q7yeyg (run npm test)

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.12.2. See [Release 5.12.2](https://github.com/webpro/knip/releases/tag/5.12.2) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._

**Comment by webpro** [comment]
Thanks for the report, @fcostarodrigo!

**Comment by fcostarodrigo** [comment]
Thank you very much @webpro 🙂
