### ISSUE TITLE
Respect .git/info/exclude in addition to .gitignore

### ISSUE THREAD

**Issue by weilbith** [webpro/knip#613]
Hey 👋🏾 

Thank you very much for this nice tool! It is great to see how it develops.

A problem I stumble over is the ignoring of developer local files. So I usually have a few files I don't want to be checked-in to the VCS, but as it is a "personal" thing, I add them to `.git/info/exclude` (see [documentation](https://git-scm.com/docs/gitignore#_synopsis)) rather than polluting the shared `.gitignore` file. As _knip_ already respects the `.gitignore` file, it would be amazing if it could to the same for the `.git/info/exclude` file too. As I don't wanna add these ignore patterns to `.gitignore` I don't wanna add them to _knip_ it's `ignore` configuration either.
Right now I always have issues because _knip_ complains in my git hooks and I can't rely on your amazing autofixing.

Happy to discuss this idea further. 🙃 
Thanks in advance!

**Comment by webpro** [comment]
Thanks @weilbith!

I didn't know about `.git/info/exclude`, that looks useful indeed.

For now, you could consider using a dynamic `knip.ts`, read `.git/info/exclude`, and its items to knip `ignore` patterns (or as [negated entry/project patterns](https://knip.dev/guides/configuring-project-files#negated-patterns)).

**Comment by weilbith** [comment]
Wow, that was a fast reply! 😱 
Thank you very much!

Ah, cool. That actually sounds like a sound idea!
I'll implement that for now. Do you think it will make it as a feature upstream? Should I contribute a PR?

---

In case someone stumbles across this issue and it is not (yet) implemented upstream, here is my version of adding it to my `knip.ts` configuration:

```typescript
import { readFile } from "fs/promises";
import type { KnipConfig } from "knip";

async function readGitInfoExcludePatterns(): Promise<string[]> {
  const buffer = await readFile(".git/info/exclude");
  return buffer
    .toString("utf-8")
    .split(/\r\n|\r|\n/)
    .filter((line) => !!line.trim())
    .filter((line) => !line.startsWith("#"))
    .map((line) => (line.endsWith("/") ? `${line}**` : line));
}

export default async function composeConfiguration(): Promise<KnipConfig> {
  const gitInfoExcludePatterns = await readGitInfoExcludePatterns();

  return {
    ignore: [
      ...gitInfoExcludePatterns,
      // ... more patterns
    ],
    // ... more configuration
  };
}
```

**Comment by weilbith** [comment]
> Feel free to give this a shot. That part of the code is here: https://github.com/webpro/knip/blob/main/packages/knip/src/util/globby.ts#L59

Hui, that's a function 😄 
Let me see. Thinking about how to integrate it best. Because the current logic seem to be quite evolved, acting on various levels including the search for `.gitignore` files, while there is always only a single `.git/info/exclude`. 🤔

**Comment by webpro** [comment]
Maybe you could consider something like moving everything inside the `if` clause of `entryFilter` to a separate function and call that function once for `.git/info/exclude`.

**Comment by webpro** [comment]
@weilbith Is this still something you fancy picking up? I have absolutely no hurries with this one, just checking up.

**Comment by weilbith** [comment]
@webpro I'm theoretically up for it. Just the typical excuse that I'm more than busy right now. Just became father and don't have the time anymore to do such things in my free time anymore. Sorry. 😕 
And as the solution above works atm. the pressure is low. 🙈

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.14.0. See [Release 5.14.0](https://github.com/webpro/knip/releases/tag/5.14.0) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._

**Comment by webpro** [comment]
Thanks @weilbith! Wishing you good health for everyone ❤️

**Comment by weilbith** [comment]
Thank you so much! My configuration just got more lean. 😊
