### ISSUE TITLE
Marked as unused if used only in Vue <template>

### ISSUE THREAD

**Issue by crystalfp** [webpro/knip#619]
I have a typescript file that export a function used only in the `<template>` part of a .vue file like this:
```
<script setup lang="ts">
import {humanFormat} from "@/services/HumanFormat";
</script>
<template>
      <div>{{ `Isosurface value (${humanFormat(value)})` }}</div>
</template>
```
Knip wrongly marks the `HumanFormat.ts` file as unused.

Maybe simply adding a list in the `knip.json` configuration with files that are used ("Trust me these files are used") could help reduce the noise on the output.

knip 5.11.0

Thanks!
mario

**Comment by webpro** [comment]
The named import of `humanFormat` is enough for Knip to consider it referenced/used. So something else might be the culprit here, such as the way the vue file is imported, or the path aliases. So I'd need [a proper reproduction](https://knip.dev/guides/troubleshooting#minimal-reproduction) to look into it and say something more useful about this.

**Comment by messenjer** [comment]
Hello,

May be an issue with the `tsconfig.json` configuration created by https://github.com/vuejs/create-vue

The alias path are in `tsconfig.app.json` and not in the `tsconfig.json`

* `tsconfig.json` : 

```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    }
  ]
}
```

* `tsconfig.app.json` 

```
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue", "src/**/*.json"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
}
```
Repro : https://stackblitz.com/edit/vitejs-vite-dpq56w?file=tsconfig.app.json 

Regards

Mathieu

**Comment by webpro** [comment]
Thanks Mathieu! Repros are great 🙏

There's two different potential solutions to this.

1. Add `knip.json` with the same `paths`:

```json
{
  "paths": {
    "@/*": ["./src/*"]
  }
}
```

2. Use `knip --tsConfig tsconfig.app.json`

With that, I'm going to close issue.

**Comment by crystalfp** [comment]
Nothing changed unfortunately. Added the "path" entry to knip.json and executed knip with --tsConfig
BTW, tsconfig.json already contains the "path" entry.

**Comment by webpro** [comment]
Without a minimal reproduction like @messenjer provided there isn't much to look for me.

**Comment by crystalfp** [comment]
Here is a minimal reproduction. The vue project has been generated with `npm create vue@latest`.
Rename the attached zip file
[unused.txt](https://github.com/user-attachments/files/16105596/unused.txt)
to `unused.zip` and unzip it. This creates the `vue-project` directory. Then do:
```
cd vue-project
npm install
knip
```
You will see that the file `src/HumanFormat.ts` has been marked as unused, but it is imported in `HelloWorld.vue` component where its exported routine is used only in the `<template>` section.

Thanks for your patience!
mario

**Comment by crystalfp** [comment]
```
$ knip --version
5.24.1
```
on Windows

**Comment by webpro** [comment]
Typo? 

```
<script setup lang="ts">
import { numanFormat } from '../HumanFormat.ts';
</script>
```

**Comment by crystalfp** [comment]
Opps, yes.
```
<script setup lang="ts">
import { humanFormat } from '../HumanFormat.ts';
</script>
```

**Comment by crystalfp** [comment]
Red face. Have found why this file (`"@/services/HumanFormat"`) is accounted as unused by knip. Because it is only used by components that are loaded dynamically (with something like: defineAsyncComponent(import(``components/ui/${ui}.vue``) and thus considered unused.
If only knip had a way to manually mark files as used even if they cannot be found by knip!
Anyway, thanks for the patience and continue with this useful tool!

**Comment by webpro** [comment]
Ah yes, indeed dynamic import specifiers like `import("components/ui/${ui}.vue")` are not supported. They might be in the future, though.

There's a few options I can think of:

- Add such files as entry files using something like `entry: ["components/ui/*.vue"]` - entry files are always "used"
- Remove them files from the project files, e.g. `project: ["!components/ui/*.vue"]`
