### ISSUE TITLE
SvelteKit Demo App $app/* unresolved

### ISSUE THREAD

**Issue by benjaminstrasser** [webpro/knip#633]
### Steps to reproduce

- `npm create svelte@6.1.2 my-app`
  - SvelteKit demo app
  - Yes, using TypeScript syntax
  - empty
- `npm i`
- rename `vite.config.ts` -> `vite.config.js`
- `npx knip@5.15.1`

### Result:
```
Unused devDependencies (2)
@fontsource/fira-mono  package.json
tslib                  package.json

Unresolved imports (5)
$app/stores       src/routes/Header.svelte:1:9               
$app/environment  src/routes/about/+page.ts:1:9              
$app/forms        src/routes/sverdle/+page.svelte:2:9        
$app/environment  src/routes/sverdle/how-to-play/+page.ts:1:9
$app/environment  src/routes/sverdle/reduced-motion.ts:2:9
```
### Expected Behavior
Resolve `$app/*` correctly

**Comment by webpro** [comment]
You can try to add the path to the config like so:

https://github.com/webpro/knip/blob/main/packages/knip/fixtures/plugins/svelte/knip.ts#L3-L5

Please let me know how it goes, should at least be documented better.

**Comment by benjaminstrasser** [comment]
> You can try to add the path to the config like so:
> 
> https://github.com/webpro/knip/blob/main/packages/knip/fixtures/plugins/svelte/knip.ts#L3-L5
> 
> Please let me know how it goes, should at least be documented better.

Worked like a charm! Thank you very much.
