### ISSUE TITLE
clashing paths configuration in a monorepo

### ISSUE THREAD

**Issue by gajus** [webpro/knip#67]
Paths were working as expected, until I added a second project to the workspace that uses paths.

So we have two projects with identical `tsconfig.json` configuration:

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "dist",
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  },
  "extends": "@contra/tsconfig/node.json",
  "include": [
    "src",
    "test"
  ]
}
```

Each individually work, but if both workspaces are added to knip.json, then they start failing.

Appears like paths are somehow improperly merged.

I also tried adding `paths` directly to `knip.json` and I confirmed (using `--debug`) that knip sees both configuration, but the outcome is the same.

If I change 2nd project path alias something else (like `$/*`) and update all imports, then knip works as expected. However, it is not desirable to have different aliases per project.

**Comment by webpro** [comment]
This is a flaw in the current setup. I'm working on v2, a major refactor and a fix for this issue will be part of that.

**Comment by webpro** [comment]
Closing this as it should be fixed in v2.
