### ISSUE TITLE
report unused ... unused rules

### ISSUE THREAD

**Issue by gajus** [webpro/knip#69]
This is just a nice to have, but I noticed that if I enter entries to `unusedDependencies` that not produce warnings, knip does not warn about them, i.e.

```
"ignoreDependencies": ["this-module-is-not-used"],
```

I would expect knip to warn me if `this-module-is-not-used` is not installed.

**Comment by webpro** [comment]
Good idea!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.8.0. See [Release 2.8.0](https://github.com/webpro/knip/releases/tag/2.8.0) for release notes._
