### ISSUE TITLE
Knip v2

### ISSUE THREAD

**Issue by webpro** [webpro/knip#73]
For a while now I've been working on a major refactoring of the TypeScript backend in Knip. Which enables a cool new feature: compilers (i.e. transpilers or preprocessors if you prefer).

In general, Knip is now much faster while improving correctness. I also have more control to further improve them.

## TypeScript Backend

While [ts-morph](https://ts-morph.com) did an excellent job abstracting away a lot of complexity of the TypeScript machinery, it eventually became also a bit limiting in terms of performance optimizations and supporting new features such as [compilers](#compilers).

Knip v2 has its own TypeScript v5 based file manager, compiler host and language service host. Most of this is inspired by ts-morph, and the [Svelte Language Tools](https://github.com/sveltejs/language-tools) and [Astro Language Tools](https://github.com/withastro/language-tools). All of this could be kept relatively basic, as Knip only reads files once (no need to cache or write files). In the future, Knip could maybe automatically `--fix` things like ESLint does, such as remove the `export` keyword for unused exports and uninstall unused dependencies.

Knip v1 uses all sorts of helpers to find things like namespaces and class members, but this is not optimal. Knip v2 traverses the AST of each used file only once, and caches some import and export maps to prevent potentially expensive calls to TypeScript's `languageService.findReferences()` (the function that also powers "Find All References" in your IDE).

## Compilers

The new file manager allows to preprocess file contents. Knip can now be configured to compile for instance MDX, Svelte or Astro files so these files and their imports and exports become part of the analysis. Adding a compiler is possible by using a `knip.ts` (or `knip.js`) config file and providing a function for each file extension that should be compiled:

```ts
import { compileSync, compileAsync } from 'compile-to-js';

export default {
  compilers: {
    md: text => compileSync(text),
    mdx: text => compileAsync(text
  }
}
```

- The signature of a compiler function is `string => string`, ie. the function will be called with the file contents as a string and should return the compiled JavaScript or TypeScript as a string.
- The extensions (`.md` and `.mdx` in the example) are automatically added to the default `entry` and `project` glob patterns. But when using custom `entry` and `project` patterns they should be included explicitly.
- Both synchronous and `async` compiler functions are supported.
- Synchronous functions are preferable since the whole TypeScript machinery is synchronous, and the relevant source files don't need to be pre-compiled ahead of time.
- Compiler functions returning a promise needs to be placed in `asyncCompilers`. The `async` functions can be located there explicitly too.

```js
import { compileSync } from '@mdx-js/mdx';

export default {
  asyncCompilers: {
    md: text => Promise.resolve(text),
  },
};
```

Personally I like the explicitness of this API, and the idea that usually no extra dependencies are necessary since the related compilers are probably already in the project (including their correct version). On the other hand, it might make sense to start providing plugins for compilers later on, mostly for easy of configuration. Maybe something like this could be nice:

```json
{
  "compilers": ["@knip/mdx"]
}
```

## New Features

- #60
- #61
- #68

## Bug fixes

- #62
- #65
- #67

## Less dependencies

- `ts-morph`, `ts-morph-helpers` and `get-tsconfig`, by lifting `typescript` to `dependencies`.
- `@esbuild-kit/esm-loader`, `esbuild` and `esbuild-register` have been replaced by [jiti](https://github.com/unjs/jiti); and with that also
  `patch-package` to patch `esbuild-register` is no longer necessary.
- `eslint` was recently moved from `dependencies` to `devDependencies`.

## Breaking Changes

There are some potentially breaking changes. Configuration schema should be unaffected (only extended).

- Knip now runs on every workspace automatically, except for the ones in `ignoreWorkspaces: []`.
- The `--include-entry-exports` flag has been removed. Please let me know if you think it should be restored.
- The "Unlisted or unresolved dependencies" is split in "Unlisted dependencies" and "Unresolved imports"
- Bug fixes and increased correctness impact output, potentially causing CI to now succeed or fail.

## How to use

```
npm install knip@next
```

It will help the project a lot if you run this new version on your projects. Any type of feedback is welcome :)

**Comment by webpro** [comment]
The first release is [v2.0.0-alpha.0](https://github.com/webpro/knip/releases/tag/2.0.0-alpha.0).

If you're curious, you can try it with `npm install knip@alpha`

**Comment by webpro** [comment]
Tagging @voxpelli, @JoshuaKGoldberg, @RebeccaStevens, @gajus, @jalopez526 as you might be interested in the new fixes and/or features :)

**Comment by gajus** [comment]
Truly amazing project!

**Comment by RebeccaStevens** [comment]
I think it would be better to use `src` in this example instead of `lib`.

https://github.com/webpro/knip/blob/v2/README.md?plain=1#L67-L76

**Comment by webpro** [comment]
New docs for v2:

- Writing a plugin: https://github.com/webpro/knip/blob/v2/docs/writing-a-plugin.md
- Compilers: https://github.com/webpro/knip/blob/v2/docs/compilers.md

**Comment by webpro** [comment]
Just released v2! Tomorrow I will look into and close related tickets where applicable.

Special thanks to @RebeccaStevens for adding lots and lots of improvements, plugins and tests! This release wouldn't nearly be as good without your contributions.

**Comment by josephadeabah** [comment]
> The first release is [v2.0.0-alpha.0](https://github.com/webpro/knip/releases/tag/2.0.0-alpha.0).
> 
> If you're curious, you can try it with `npm install knip@next`

Can we install this via `yarn`?

**Comment by webpro** [comment]
You're commenting on a very old issue, but yes. Please see https://knip.dev/overview/getting-started.
