### ISSUE TITLE
Feedback for knip v2

### ISSUE THREAD

**Issue by mcmxcdev** [webpro/knip#74]
Still works and runs noticeable faster, great job!

Most of these were probably also an issue in v1, but thought I would write them down at once:

knip doesn't understand e.g. `~/pages/supplemental-coverage` imports inside a nested next.js project for us. We point knip to the base config in the root of the nx workspace, but it doesn't seem to understand the `~` for some reason.

We use Nest.js and have e.g. `base.dto.ts` defined with `id`, `createdAt` and `updatedAt` properties. Now these properties are flagged as "Unused exported class members" but the DTO itself is extended by other DTOs in other files.

Files like `jest.config.ts`, `webpack.config.js`, `playwright.config.ts`, etc. are flagged throughout the codebase as "Unused files".

Files which are having `__generated__` somewhere in their path should probably be ignored.

Some `getServerSideProps` are flagged as unused exports while others in the monorepo seem to not be reported.

**Comment by webpro** [comment]
> Still works and runs noticeable faster, great job!

Thanks! I appreciate you taking the time to try v2 and report back.

> Most of these were probably also an issue in v1, but thought I would write them down at once:
> 
> knip doesn't understand e.g. `~/pages/supplemental-coverage` imports inside a nested next.js project for us. We point knip to the base config in the root of the nx workspace, but it doesn't seem to understand the `~` for some reason.

In general paths from the TypeScript compiler are taken into account, and also custom `paths` can be provided. Of course there can be a bug, I'm happy to look into something I can check out.

> We use Nest.js and have e.g. `base.dto.ts` defined with `id`, `createdAt` and `updatedAt` properties. Now these properties are flagged as "Unused exported class members" but the DTO itself is extended by other DTOs in other files.

Do you maybe know of some example or documentation or anything I could look into?

> Files like `jest.config.ts`, `webpack.config.js`, `playwright.config.ts`, etc. are flagged throughout the codebase as "Unused files".

This part is not really documented. The idea is that the defaults of plugins usually work (most of them only look in the root directory), but in this type of monorepo it needs some custom configuration. Here's a real-world example from a Nx project (note all the patterns starting with `**/` for files scattered throughout the repo):

```json
{
  "eslint": ["**/.eslintrc", "**/.eslintrc.{js,json}", "config/eslint/*.json"],
  "capacitor": "containers/**/capacitor.config.ts",
  "cypress": {
    "config": ["**/cypress.config.ts", "e2e/nl/internal/sparky-e2e/vite.config.ts"],
    "entry": ["e2e/**/*.cy.ts", "e2e/**/support/{component,e2e}.ts"],
    "project": ["e2e/**/*.ts"]
  },
  "jest": {
    "config": "**/jest.config.{js,ts}",
    "entry": "config/jest/jest-setup.ts"
  },
  "nx": "{apps,libs}/**/project.json",
  "next": {
    "config": "**/next.config.js",
    "entry": ["containers/**/pages/**/*.{ts,tsx}", "containers/**/src/pages/**/*.{ts,tsx}"]
  }
}
```

> Files which are having `__generated__` somewhere in their path should probably be ignored.

You can use `ignore` on a global level or per workspace to ignore certain files and/or directories.

> Some `getServerSideProps` are flagged as unused exports while others in the monorepo seem to not be reported.

Exports from entry files should not be flagged as unused. Maybe where the ones that are flagged are not in files marked as an entry file?

**Comment by mcmxcdev** [comment]
> In general paths from the TypeScript compilerOptions are taken into account, and also custom paths can be provided. Of course there can be a bug, I'm happy to look into something I can check out.

The `~` is not set in the root tsconfig that we point too, but in a nested one that extends the root config. Probably that's the source of the problem. It also doesn't work properly when I point to all existing tsconfigs like:

```
typescript: { config: ['tsconfig.base.json', '**/tsconfig.json', '**/tsconfig.{lib,app,spec}.json'] },
```

***

> Do you maybe know of some example or documentation or anything I could look into?

Didn't find anything 100% fitting, but maybe this helps: https://docs.nestjs.com/openapi/types-and-parameters#types-and-parameters

Here's also an example of how we use it:

```
export class BaseDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID('4')
  @Expose()
  id: string;

  @ApiPropertyOptional()
  createdAt?: Date;

  @ApiPropertyOptional()
  updatedAt?: Date;
}

export class BenefitDto extends BaseDto {
  @ApiProperty({ enum: BenefitType })
  type: BenefitType;
}
```

> Here's a real-world example from a Nx project (note all the patterns starting with **/ for files scattered throughout the repo):

Thanks for this, I was able to copy a lot and modify what's needed.

> Exports from entry files should not be flagged as unused. Maybe where the ones that are flagged are not in files marked as an entry file?

This actually works now that I added a `next` configuration to the knip config.

**Comment by webpro** [comment]
The extended TS configs issue received a fix in [2.0.0-alpha.5](https://github.com/webpro/knip/releases/tag/2.0.0-alpha.5).

Thanks for the examples, I'm seeing some syntax that indeed wasn't covered yet.

**Comment by mcmxcdev** [comment]
I think it's difficult to say what the behavior should be:
Classes in Nest.js are often times exported but not imported directly and should therefore be ignored by Knip.
But on the other hand, then it will be hard to ever spot e.g. actual unused exported DTOs that might be left behind after a refactor or similar.

I guess let's have knip v2 stabilize and mature first, then I would run more checks again and take an in-depth look of what should be tackled of the remaining issues we have reported in our codebase (false positives).

**Comment by webpro** [comment]
My current stance (and what Knip currently does) is this: when things are consumed by external dependencies they should be either in an entry file or marked explicitly using a `@public` JSDoc tag.

Exports of entry files are ignored for a reason: it's impossible to know which exports are used by which framework. This also changes over time (even in minor bumps of frameworks). Currently I think this is too fragile too track.

Still, I'm happy to learn how Knip can help with such refactorings and spot unused exports after the fact. Maybe a way to say "in these files I only allow exports with these specific names" could be useful. This can then also be maintained within the project itself.

**Comment by webpro** [comment]
Most or all things should be addressed, either by bug fixes or documentation, so I'm going to close this issue. Thanks again for the feedback!
