### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by ojeytonwilliams** [webpro/knip#8]
Hi @webpro, when I was testing this out on the freecodecamp repo, node ran out of memory when I used the tool.  The proximate cause was that a bunch of build artifacts were included in the projectFiles, ballooning the memory usage. The ultimate cause (as far as I can see) is that ts-morph has to hold the entire project's AST in memory at once and that gets quite large.

It might be worth saying something in the docs to help mitigate this. Maybe a troubleshooting section?

**Comment by webpro** [comment]
Thanks, this is great feedback. Definitely something for the docs. And probably it makes sense to use `.gitignore` file(s) by default (or optionally).

**Comment by webpro** [comment]
Until that feature lands, you could use pattern(s) like `"!build/**"` in `projectFiles`.

**Comment by ojeytonwilliams** [comment]
Yeah, I think optionally ignoring .gitignored files would be great.

**Comment by webpro** [comment]
Since v0.4 `.gitignore` files should automatically be taken into account (recursively from `--dir` up to and including `cwd`).

**Comment by ojeytonwilliams** [comment]
Nice one, @webpro. That was quick!

**Comment by webpro** [comment]
Knip v4 is about to mitigate some of these memory issues much better: https://knip.dev/blog/slim-down-to-speed-up (you can install and try v4 canary today). Recently added [--isolate-workspaces](https://knip.dev/reference/cli/#--isolate-workspaces) (in v3) which may also help in certain edge cases.
