### ISSUE TITLE
Support knip.js configuration file

### ISSUE THREAD

**Issue by gajus** [webpro/knip#81]
The problem with JSON format is that it is hard to create extendable configuration.

Whereas, if the file was JavaScript executable that simply returns the same configuration, then it would be easy to create shared project config, e.g.

```ts
const base = {
  ignore: [
    "**/*.d.ts",
  ],
  entry: [
    "src/bin/*.ts!"
  ],
  project: [
    "src/**/*.ts!",
    "test/**/*.ts"
  ],
};

module.exports = {
  "workspaces": {
    "apps/foo": {
      ...base,
    },
    "apps/bar": {
      ...base,
      "ignore": [
        ...base.ignore,
        'something-else.ts',
      ],
      "entry": [
        ...base.entry,
        'something-else.ts',
      ],
    },
  }
```

**Comment by webpro** [comment]
[You can already do this](https://github.com/webpro/knip#usage), both `.ts` and `.js` should work!

**Comment by RebeccaStevens** [comment]
> [You can already do this](https://github.com/webpro/knip#usage), both `.ts` and `.js` should work!

Ideally `.cjs` and `.cts` should also be supported (additionally `.mjs` and `.mts` if esm configs are supported).

**Comment by RebeccaStevens** [comment]
@gajus if you replace `module.exports =` with `export default` does it work?

**Comment by gajus** [comment]
Totally somehow missed it!
