### ISSUE TITLE
Use jsonc-parser over strip-json-comments and json parser

### ISSUE THREAD

**Issue by RebeccaStevens** [webpro/knip#83]
Wouldn't it be better to use [jsonc-parser](https://www.npmjs.com/package/jsonc-parser) and do the parsing in a single step?

Though it probably doesn't really matter either way.

**Comment by RebeccaStevens** [comment]
One thing to note is that `jsonc-parser` supports trailing commas while `JSON.parse(stripJsonComments(text))` doesn't.

```jsonc
{
  // comment
  "foo": 1, // <-- tailing comma
}
```

**Comment by webpro** [comment]
I looked at both options and ended up with the other. Also because [strip-json-comments](https://www.npmjs.com/package/strip-json-comments) is much smaller in scope and size. Did you encounter any issues with it?

**Comment by RebeccaStevens** [comment]
I haven't encountered any issues so far, but I do like to use trailing commas in my jsonc files.
Unfortunately, I usually can't as many tools don't support them.

**Comment by RebeccaStevens** [comment]
Feel free to close this issue as it's very minor.

**Comment by webpro** [comment]
I appreciate the flexibility as well (when we're stripping comments we can strip that comma too), but still prefer the tiny dependency.

**Comment by webpro** [comment]
Turns out this is/was already supported (https://github.com/sindresorhus/strip-json-comments#trailingcommas)

**Comment by frantisekhanzlikbl** [comment]
Hey, sorry to necropost, but would you mind adding the non-standard `allowTrailingCommas` to your JSON schema?
It tells VS Code and perhaps other editors that trailing commas are allowed. (ref: https://github.com/microsoft/vscode/issues/102061#issuecomment-656541600)
Tranks! :-)

**Comment by webpro** [comment]
[Seek and ye shall find](https://knip.dev/reference/configuration#json-schema) :)

**Comment by frantisekhanzlikbl** [comment]
Ohhh, I'm so blind, it's unreal. I was using the JSON schema for my JSONC. That's what I get for setting up stuff at one in the morning. Thanks again. :smile:
