### ISSUE TITLE
Help - Nx --affected with targets by modules -  Problem to find package.json file in the root  

### ISSUE THREAD

**Issue by ilucasanderson** [webpro/knip#98]
Hi;

i'm trying to use Knip actually with NX; 
In my project I have more than 20 different modules, so... to have an efficiency running when with Knip I decided to use the `nx --affected` (with this only the modified module will run the knip) and with this I created one target; but I havent sucess, 

If I use the command `nx run someModule:lint:knip --skip-nx-cache` for example, I'll have this following message:

> Unable to find package.json

Project Structure - Base:

```
project/
 apps/
 modules/
  someModule/
   project.json
knip.ts
package.json
```

So, in this case, I havent `package.json` inside of `someModule`, only I have in the root;

___

But when I created an file named `package.json` only with `{ }` inside of `someModule` folder I have success; the Knip run perfectly;

___

So, because this, I understood the problem are with "my Knip cant find the package.json on the root of project and I dont know how to fix that";

Can anyone help with this?

___

Files:

package.json
```
scripts: {
  [...]
     "lint:knip": "nx affected --target=lint:knip --base=$NX_BASE --head=$NX_HEAD",
  [...]
devDependencies: {
  [...]
     "@nrwl/react": "15.8.6",
     "knip": "^1.17.0",
  [...]
}
```

knip.ts

```
import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  nx: {
    config: ["{apps,modules}/**/project.json"]
  }
};

export default config;

```

someModule/project.json
  ```
  "lint:knip": {
      "executor": "nx:run-commands",
      "options": {
        "cwd": "modules/someModule",
        "commands": ["knip"]
      }
    },
```

**Comment by webpro** [comment]
I think I understand what you're trying to do: you are only interested in unused files and exports (and not dependencies). You would also need to add `--include files --exports` otherwise the reported unused (dev) dependencies would be false positives. You want to see unused files and exports from basically any directory, right? I say "any", because Knip does not know about Nx project structure or `project.json` files.

To be honest, what you are trying to do was actually supported in an early version. It is not anymore (and I renamed the `--dir` argument to `--workspace`), because it's confusing for most use cases.

I do think you have a valid use case here, perhaps it's interesting to look into a `--dir` argument that basically ignores `package.json` and (unused) dependencies, but has `--include files --exports`.

(By the way, I would recommend to move to Knip v2 as it is faster and should give more accurate results.)

**Comment by ilucasanderson** [comment]
Hi, thanks for the reply;

"You want to see unused files and exports from basically any directory, right?"
- Yes, by directory;

"To be honest, what you are trying to do was actually supported in an early version."
- You remenber the version number?
___
I`ve done severals tests with the Knip v2, but I run into this same issue;
I set `--include files --exports` and get the error `Unable to find package.json`;

Do you know any options I apply to tell what is the package.json path in the root (because I only have this one)? I just think in something similar with `-t, --tsConfig`;

Thanks again

**Comment by webpro** [comment]
> * You remenber the version number?

The last version before v1: v0.13.3

> I've done severals tests with the Knip v2, but I run into this same issue; I set `--include files --exports` and get the error `Unable to find package.json`;

Sorry if that wasn't clear. What you want is not supported in either v1 or v2. It requires to be ran from the root of the repository with a `package.json`.

> Do you know any options I apply to tell what is the package.json path in the root (because I only have this one)? I just think in something similar with `-t, --tsConfig`;

All options are visible with `knip --help` and I knip does not have this option to provide a different path for `package.json`.

**Comment by ilucasanderson** [comment]
I created a small project (repro) with this problem, you can try to run?

Project: https://github.com/ilucasanderson/nx-knip

Main commit: https://github.com/ilucasanderson/nx-knip/commit/ce46c2652b6984c5d54ba4714759ab7b4984f8d8;

Command: `yarn knip`;

You can see if I forgot to insert some information/code?

**Comment by webpro** [comment]
But I said it is not supported :)

Note that this "integrated repo" setup in your repo with Nx projects is not the same as workspaces ("package based").

I'm going to stay here in this issue to keep things together (to be honest I don't want to get lost in other tooling like Nx). Let me re-iterate on your options:

1. You can go back to v0.13.3 and try using `--dir` with that version.

From the root of the project:

```json
{
  "entryFiles": ["src/index.ts"],
  "projectFiles": ["src/**/*.{ts,tsx}"]
}
```

And run something like this from the root (or with Yarn or Nx or whatever):

```
knip --dir modules/ui/input --include files,exports,nsExports,classMembers,types,nsTypes,enumMembers,duplicates
```

This works, but it's a bit slow. Of course it depends on the size of the actual project. But I strongly recommend to go with Knip v2 and analyze the project as a whole. If you want to use Knip you will need to migrate to v2 sooner or later anyway as you may understand I'm not keen on supporting such an early version.

2. Use the latest v2 and analyze the project as a whole.

```json
{
  "entry": ["apps/*/src/index.tsx", "modules/*/*/src/index.ts"],
  "project": ["{apps,modules}/**/*.{ts,tsx}"],
  "nx": ["{apps,modules}/**/project.json"],
  "babel": ["babel.config.json", "{apps,modules}/**/.babelrc"]
}
```

As this example `knip.json` shows, you will need to override the config files for all plugins that are scattered around the project in this way.

And run Knip from the root:

```
knip --tsConfig tsconfig.base.json 
```

From a Knip (v2) perspective, if you still have the option, a package-based workspaces setup is better. Then you can also use the `--workspace` option with Nx affected.

Hope this helps. Feel free to ask questions :)

**Comment by ilucasanderson** [comment]
Ah, ok... I understood the situation;
Sorry if I got confused haha

My team and I really appreciate all the support you give us;

We changed the proposal on the feature, decided to use Knip running throughout the project;

I need to say thank you again and congratulations for the project :)

**Comment by webpro** [comment]
Thank you! Good luck with the project 🚀
